Repository dodona-edu/dodona, pull requests merged in 2019-12, with the labels that each got.

#1553 redirect_to_default_host should not throw away query parameters
  app/controllers/application_controller.rb
  test/controllers/exercises_controller_test.rb
Labels: bug fix

#1557 Bump puma from 3.11.1 to 4.3.1
  Gemfile
  Gemfile.lock
Labels: dependencies, ruby

#1552 remove rails-ujs dependency
  package.json
  yarn.lock
Labels: dependencies, javascript

#1566 Ignore some long-running requests we know can be slow
  config/initializers/exception_notification.rb
Labels: chore, no-release-notes

#1571 Remove trix dependency
  package.json
  vendor/assets/stylesheets/trix/trix.css.less
  vendor/assets/stylesheets/vendor.less
  yarn.lock
Labels: chore, no-release-notes

#1576 Set charset to utf-8 if sending plaintext media
  app/controllers/exercises_controller.rb
  test/controllers/exercises_controller_test.rb
Labels: bug fix

#1577 Fix searching for courses
  app/controllers/courses_controller.rb
Labels: bug fix

#1594 Remove @rails/actiontext dependency
  package.json
Labels: dependencies, javascript

#1534 tooltips & wrapping
  app/assets/javascripts/code_listing.ts
  app/assets/stylesheets/components/code_listing.css.less
Labels: feature
