Repository dodona-edu/dodona, pull requests merged in 2019-10, with the labels that each got.

#1335 Add release-drafter action
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: chore

#1336 update release drafter settings
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: no-release-notes

#1339 update readme
  README.md
Labels: no-release-notes

#1346 exclude a few lines from test coverage reporting
  app/runners/submission_runner.rb
Labels: no-release-notes

#1337 fix users being unable to subscribe to hidden courses
  app/controllers/courses_controller.rb
  app/models/course.rb
  app/views/courses/_not_a_member_card.html.erb
  test/controllers/courses_controller_test.rb
  test/models/course_test.rb
Labels: bug fix

#1352 Apply rubocop changes to Gemfile
  Gemfile
Labels: no-release-notes

#1345 upgrade to Ruby 2.6.5
  .circleci/config.yml
  .github/workflows/ruby.yml
  .ruby-version
  Gemfile
  Gemfile.lock
Labels: chore

#1355 staging environment changes
  config/deploy/staging.rb
  config/environments/staging.rb
Labels: no-release-notes

#1361 Don't show progress header on xs screens
  app/views/course_members/_members_table.html.erb
Labels: bug fix

#1234 description iframes
  app/assets/stylesheets/layout.css.less
  app/controllers/application_controller.rb
  app/controllers/exercises_controller.rb
  app/helpers/application_helper.rb
  app/helpers/exercise_helper.rb
  app/javascript/packs/description.js
  app/javascript/packs/exercise.js
  app/javascript/packs/frame.js
  app/javascript/packs/series_overview.js
  app/models/application_record.rb
  app/models/course.rb
  app/models/exercise.rb
  app/models/series.rb
  app/policies/exercise_policy.rb
  app/views/exercises/description.html.erb
  app/views/exercises/show.html.erb
  app/views/layouts/application.html.erb
  app/views/layouts/frame.html.erb
  app/views/series/overview.html.erb
  config/application.rb
  config/deploy/staging.rb
  config/environments/staging.rb
  config/routes.rb
  package.json
  test/controllers/exercises_controller_test.rb
  test/factories/exercises.rb
  test/models/exercise_test.rb
  test/renderers/application_helper_test.rb
  vendor/assets/stylesheets/bootstrap/bootstrap.less
  yarn.lock
Labels: feature

#1362 Fix striped tables in dark mode
  app/assets/stylesheets/theme/theme-dark.css.less
Labels: bug fix

#1364 remove double yarn install
  config/deploy/staging.rb
Labels: no-release-notes

#1365 handle newlines in pythia diff ouput
  app/helpers/renderers/pythia_renderer.rb
  test/renderers/renderers_test.rb
Labels: bug fix

#1366 Delete backup-lethe.sh
  scripts/backup-lethe.sh
Labels: no-release-notes

#1330 sanitize submission result
  app/helpers/application_helper.rb
  app/helpers/renderers/feedback_table_renderer.rb
  app/helpers/renderers/lcs_html_differ.rb
  app/helpers/renderers/pythia_renderer.rb
  db/migrate/20190930135628_add_allow_unsafe_to_exercise.rb
  db/schema.rb
  public/schemas/judge_output.json
  public/schemas/partial_output.json
  test/files/output.json
  test/files/pythia_output.json
  test/renderers/renderers_test.rb
Labels: feature

#1279 small text fixes
  config/locales/views/submissions/en.yml
Labels: no-release-notes

#1367 Send a notification if a user's email adress changed
  lib/SAML/my_resource_validator.rb
Labels: feature

#1351 remove runner field from database
  app/models/judge.rb
  app/policies/judge_policy.rb
  db/migrate/20191003073541_remove_runner_column_from_judge.rb
  db/schema.rb
  db/seeds.rb
  test/controllers/judges_controller_test.rb
  test/factories/judges.rb
Labels: for-hotfix

#1371 Allow svg elements in feedback table
  app/helpers/application_helper.rb
Labels: bug fix

#1373 Detect dark mode in iframe if the user hasn't set a preference
  app/helpers/exercise_helper.rb
  app/views/layouts/frame.html.erb
Labels: bug fix

#1374 Don't try to center iframes for now
  app/assets/javascripts/exercise.js
Labels: bug fix

#1380 Fix css in frame for browsers that don't support prefers-color-scheme and don't fall back correctly
  app/views/layouts/frame.html.erb
Labels: bug fix

#1381 Optimize feedback table
  app/helpers/renderers/feedback_table_renderer.rb
  app/helpers/renderers/lcs_html_differ.rb
Labels: bug fix

#1394 Reduce the number of lines required for the simple table
  app/helpers/renderers/lcs_html_differ.rb
Labels: bug fix

#1396 Don't open error emails with letter opener for local requests
  config/environments/development.rb
Labels: no-release-notes

#1398 Measure file operations
  app/models/submission.rb
Labels: no-release-notes

#1408 Also bump caching namespace for naos
  config/environments/staging.rb
Labels: no-release-notes

#1409 Tell capistrano-rvm about our custom rvm location
  config/deploy.rb
Labels: no-release-notes

#1416 fix synchronization issues around timeout detection
  app/runners/submission_runner.rb
  test/factories/exercises.rb
  test/runners/submission_runner_test.rb
Labels: bug fix

#1430 Link to new news site in drawer
  app/views/layouts/_drawer.html.erb
Labels: chore

#1431 Bump rails-html-sanitizer
  Gemfile.lock
Labels: dependencies, ruby

#1435 send emails if users are unable to login via oauth
  app/controllers/omniauth_callbacks_controller.rb
  app/mailers/application_mailer.rb
  test/controllers/omniauth_callbacks_controller_test.rb
Labels: chore

#1436 send better emails when submission status changes to internal error
  app/models/submission.rb
  test/models/submission_test.rb
Labels: chore

#1440 ignore exceptions from crawlers
  config/environments/production.rb
Labels: chore
