Repository dodona-edu/dodona, pull requests merged in 2019-11, with the labels that each got.

#1455 Add token to media urls in feedback table if exercise is private
  app/helpers/exercise_helper.rb
  app/helpers/renderers/feedback_table_renderer.rb
  test/files/output.json
  test/renderers/renderers_test.rb
Labels: bug fix

#1458 Fix some permission issues involving private exercises in moderated courses
  app/assets/javascripts/exercise.js
  app/assets/javascripts/i18n/translations.js
  app/controllers/submissions_controller.rb
  app/models/exercise.rb
  config/locales/js/en.yml
  config/locales/js/nl.yml
  test/controllers/submissions_controller_test.rb
  test/models/exercise_test.rb
Labels: bug fix

#1463 reduce request time limit again
  config/initializers/exception_notification.rb
Labels: chore

#1461 remove posts
  app/assets/javascripts/post.js
  app/assets/stylesheets/libraries.css.less
  app/assets/stylesheets/libraries/actiontext.css.less
  app/controllers/posts_controller.rb
  app/javascript/packs/application.js
  app/javascript/packs/post.js
  app/models/post.rb
  app/policies/post_policy.rb
  app/views/layouts/_drawer.html.erb
  app/views/layouts/_footer.html.erb
  app/views/pages/privacy.en.html.erb
  app/views/pages/privacy.nl.html.erb
  app/views/posts/_form.html.erb
  app/views/posts/_post.html.erb
  app/views/posts/_post.json.jbuilder
  app/views/posts/edit.html.erb
  app/views/posts/index.html.erb
  app/views/posts/index.json.jbuilder
  app/views/posts/new.html.erb
  app/views/posts/show.html.erb
  config/locales/models/en.yml
  config/locales/models/nl.yml
  config/locales/views/posts/en.yml
  config/locales/views/posts/nl.yml
  config/routes.rb
Labels: chore

#1485 fix typo in tool tip
  config/locales/views/courses/nl.yml
Labels: bug fix

#1466 set frame html and body height to fit-content
  app/assets/stylesheets/layout.css.less
  app/views/layouts/frame.html.erb
Labels: bug fix

#1467 use same styling for .test.output as for .code
  app/assets/stylesheets/models/submissions.css.less
Labels: bug fix

#1487 allow words to be broken in feedbacktable if there is no other option
  app/assets/stylesheets/models/submissions.css.less
Labels: bug fix

#1460 GitHub Actions dependency caching
  .circleci/config.yml
  .github/workflows/javascript.yml
  .github/workflows/ruby.yml
Labels: chore, no-release-notes

#1488 enable parallel testing
  .github/workflows/ruby.yml
  test/test_helper.rb
Labels: chore, no-release-notes

#1172 replace submission download actions with export wizard
  app/assets/javascripts/drag_and_drop.js
  app/assets/javascripts/export.js
  app/assets/javascripts/i18n/translations.js
  app/assets/stylesheets/components/card.css.less
  app/assets/stylesheets/models/course.css.less
  app/assets/stylesheets/models/series.css.less
  app/assets/stylesheets/pages.css.less
  app/assets/stylesheets/pages/export.css.less
  app/assets/stylesheets/theme/theme-dark.css.less
  app/assets/stylesheets/theme/theme-light.css.less
  app/controllers/application_controller.rb
  app/controllers/export_controller.rb
  app/controllers/series_controller.rb
  app/javascript/packs/export.js
  app/models/series.rb
  app/models/transient/export.rb
  app/policies/course_policy.rb
  app/policies/export_policy.rb
  app/policies/series_policy.rb
  app/policies/user_policy.rb
  app/views/courses/show.html.erb
  app/views/export/_option.html.erb
  app/views/export/_selection_table.html.erb
  app/views/export/download_submissions.html.erb
  app/views/series/_series.html.erb
  app/views/users/show.html.erb
  config/locales/js/en.yml
  config/locales/js/nl.yml
  config/locales/views/courses/en.yml
  config/locales/views/courses/nl.yml
  config/locales/views/export/en.yml
  config/locales/views/export/nl.yml
  config/locales/views/series/en.yml
  config/locales/views/series/nl.yml
  config/locales/views/users/en.yml
  config/locales/views/users/nl.yml
  config/routes.rb
  test/controllers/export_controller_test.rb
  test/controllers/series_controller_test.rb
  test/factories/exercises.rb
  test/helpers/export_zip_helper.rb
  test/helpers/series_zip_helper.rb
  test/models/series_test.rb
  test/test_helper.rb
Labels: feature

#1500 update i18n-js script
  public/javascripts/i18n.js
Labels: chore, no-release-notes

#1459 add CSP headers
  app/controllers/application_controller.rb
  app/controllers/exercises_controller.rb
  app/controllers/pages_controller.rb
  app/controllers/series_controller.rb
  app/helpers/exercise_helper.rb
  app/views/series/overview.html.erb
  config/initializers/content_security_policy.rb
  config/routes.rb
  test/controllers/exercises_controller_test.rb
  test/controllers/pages_controller_test.rb
Labels: feature

#1501 add applebot to ignored user agents for errors
  config/environments/production.rb
Labels: chore, no-release-notes

#1462 remove posts from database
  db/migrate/20191106142529_remove_posts.rb
  db/schema.rb
Labels: chore, for-hotfix

#1520 Fix selection in Microsoft Edge including the tooltips
  app/assets/javascripts/code_listing.ts
  app/assets/stylesheets/components/code_listing.css.less
Labels: bug fix

#1519 Various code tab style fixes
  app/assets/javascripts/code_listing.ts
  app/assets/stylesheets/components/code_listing.css.less
Labels: bug fix

#1464 fix slow exercise description
  app/assets/javascripts/exercise.js
  app/assets/javascripts/submission.js
  app/helpers/exercise_helper.rb
  app/helpers/renderers/feedback_table_renderer.rb
  app/views/exercises/description.html.erb
  test/renderers/exercise_helper_test.rb
Labels: bug fix
