Repository dodona-edu/dodona, pull requests merged in 2020-04, with the labels that each got.

#1812 Remove spurious top margin in exercise descriptions
  app/assets/stylesheets/models/exercises.css.less
Labels: bug fix

#1813 Fix broken staff/zeus icon on inline submissions
  app/assets/stylesheets/bootstrap_overrides.css.less
Labels: bug fix

#1815 Fix focus issue with lightbox in exercise descriptions
  app/assets/javascripts/exercise.js
  app/views/layouts/application.html.erb
Labels: bug fix

#1830 Fix newlines being stripped from exercise boilerplate
  app/models/exercise.rb
  test/controllers/annotations_controller_test.rb
  test/models/annotation_test.rb
Labels: bug fix

#1832 Update docker instructions in README
  README.md
Labels: documentation

#1831 Intra-series navigation
  app/assets/stylesheets/components/btn.css.less
  app/assets/stylesheets/models/exercises.css.less
  app/controllers/exercises_controller.rb
  app/helpers/exercise_helper.rb
  app/helpers/series_helper.rb
  app/views/exercises/show.html.erb
  config/locales/views/exercises/en.yml
  config/locales/views/exercises/nl.yml
  test/controllers/courses_controller_test.rb
  test/factories/exercises.rb
  test/factories/judges.rb
  test/factories/repositories.rb
  test/helpers/exercise_helper_test.rb
  test/test_helper.rb
  test/testhelpers/.keep
  test/testhelpers/crud_helper.rb
  test/testhelpers/delayed_job_helper.rb
  test/testhelpers/export_zip_helper.rb
  test/testhelpers/git_helper.rb
  test/testhelpers/remote_helper.rb
  test/testhelpers/stub_helper.rb
Labels: feature

#1787 Annotation tweaks
  app/assets/javascripts/code_listing/annotation.ts
  app/assets/javascripts/code_listing/code_listing.ts
  app/assets/javascripts/code_listing/machine_annotation.ts
  app/assets/javascripts/code_listing/user_annotation.ts
  app/assets/javascripts/i18n/translations.js
  app/assets/javascripts/types/index.d.ts
  app/assets/javascripts/util.js
  app/assets/stylesheets/components/code_listing.css.less
  app/helpers/renderers/feedback_code_renderer.rb
  app/helpers/renderers/feedback_table_renderer.rb
  app/models/annotation.rb
  app/models/submission.rb
  config/i18n-js.yml
  config/locales/defaults/en.yml
  config/locales/defaults/nl.yml
  config/locales/js/en.yml
  config/locales/js/nl.yml
  config/locales/views/submissions/en.yml
  config/locales/views/submissions/nl.yml
  db/migrate/20200406155516_add_line_count_to_submission.rb
  db/schema.rb
  jest.config.js
  test/controllers/annotations_controller_test.rb
  test/factories/annotations.rb
  test/javascript/code_listing.test.ts
  test/javascript/setup-jest.ts
  test/models/annotation_test.rb
Labels: feature, student

#1757 Exercise info page improvements
  app/assets/stylesheets/models/exercises.css.less
  app/controllers/exercises_controller.rb
  app/helpers/exercise_helper.rb
  app/models/exercise.rb
  app/views/exercises/_form.html.erb
  app/views/exercises/_navbar_links.html.erb
  app/views/exercises/info.html.erb
  app/views/exercises/show.html.erb
  config/locales/views/exercises/en.yml
  config/locales/views/exercises/nl.yml
  test/controllers/exercises_controller_test.rb
  test/models/exercise_test.rb
  test/testhelpers/stub_helper.rb
Labels: feature, student

#1837 Allow multiple code listings on same page
  app/assets/javascripts/code_listing/code_listing.ts
  app/assets/javascripts/copy.ts
  app/assets/javascripts/util.js
  app/assets/stylesheets/components/code_listing.css.less
  app/helpers/renderers/feedback_code_renderer.rb
  app/helpers/renderers/feedback_table_renderer.rb
  app/javascript/packs/application.js
  app/javascript/packs/frame.js
  app/javascript/packs/submission.js
  app/views/exercises/info.html.erb
  test/javascript/code_listing.test.ts
  test/renderers/feedback_code_renderer_test.rb
Labels: bug fix, student

#1838 Allow course admins to delete (almost) unused courses
  app/assets/stylesheets/components/btn.css.less
  app/models/course.rb
  app/models/course_membership.rb
  app/policies/course_policy.rb
  app/views/courses/edit.html.erb
  config/locales/views/courses/en.yml
  config/locales/views/courses/nl.yml
  test/controllers/courses_controller_test.rb
  test/models/course_test.rb
Labels: feature, student

#1853 Fix intra page links
  app/assets/javascripts/exercise.js
  app/assets/stylesheets/models/exercises.css.less
  app/helpers/exercise_helper.rb
  app/javascript/packs/exercise.js
Labels: bug fix, student

#1834 Caching & deadline displays
  app/assets/stylesheets/models/series.css.less
  app/controllers/exports_controller.rb
  app/helpers/deadlines_helper.rb
  app/helpers/series_helper.rb
  app/models/course.rb
  app/models/exercise.rb
  app/models/exercise_status.rb
  app/models/series.rb
  app/models/submission.rb
  app/models/transient/exercise_summary.rb
  app/models/transient/series_summary.rb
  app/policies/exercise_policy.rb
  app/views/deadlines/_absolute.html.erb
  app/views/deadlines/_relative.html.erb
  app/views/exercises/_exercise.json.jbuilder
  app/views/exercises/_exercises_table.html.erb
  app/views/exercises/_user_status.html.erb
  app/views/exercises/_user_status_icon.html.erb
  app/views/exports/_selection_table.html.erb
  app/views/pages/_course_card.html.erb
  app/views/pages/_user_card.html.erb
  app/views/series/_deadline.html.erb
  app/views/series/_human_deadline.html.erb
  app/views/series/_series.html.erb
  app/views/series/_series_status.html.erb
  app/views/series/overview.html.erb
  config/locales/views/deadline/en.yml
  config/locales/views/deadline/nl.yml
  config/locales/views/series/en.yml
  config/locales/views/series/nl.yml
  db/migrate/20200416111212_create_exercise_statuses.rb
  db/schema.rb
  test/controllers/series_controller_test.rb
  test/factories/courses.rb
  test/factories/exercise_statuses.rb
  test/factories/submissions.rb
  test/models/course_test.rb
  test/models/exercise_status_test.rb
  test/models/exercise_test.rb
  test/models/series_test.rb
  test/models/submission_test.rb
  test/models/transient/exercise_summary.rb
  test/models/transient/series_summary_test.rb
Labels: feature, student

#1863 Add `summary` and `details` to allowed HTML elements
  app/helpers/application_helper.rb
Labels: bug fix

#1864 Remove line count again
  app/models/annotation.rb
  app/models/submission.rb
  db/migrate/20200406155516_add_line_count_to_submission.rb
  db/schema.rb
  test/controllers/annotations_controller_test.rb
Labels: chore

#1871 Fix hiding of correct tests on exercise page
  app/assets/javascripts/submission.js
  app/helpers/renderers/feedback_table_renderer.rb
Labels: bug fix

#1872 Clamp line number of annotation to line count of code
  app/assets/javascripts/code_listing/code_listing.ts
Labels: bug fix

#1876 Fix attempting to display non existent deadlines
  app/views/exercises/_user_status.html.erb
Labels: bug fix

#1880 Fix code not being initialised in code listing sometimes
  app/helpers/renderers/feedback_code_renderer.rb
Labels: bug fix

#1878 Catch race condition with ExerciseStatus
  app/models/exercise.rb
  test/models/exercise_test.rb
Labels: bug fix

#1881 Fix retry mechanism retrying zero times
  app/models/exercise.rb
  test/models/exercise_test.rb
Labels: bug fix

#1882 Disable forgery protection again on exercises#media
  app/controllers/exercises_controller.rb
Labels: bug fix

#1883 Check for existence of user
  app/views/series/overview.html.erb
Labels: bug fix

#1885 Also see SIGABRT as a judge error that shouldn't result in an internal error
  app/runners/submission_runner.rb
Labels: bug fix

#1889 Recalculate ExerciseStatus fully after submission update
  app/models/exercise_status.rb
  app/models/submission.rb
Labels: bug fix

#1890 Add "output limit exceeded" status
  app/helpers/application_helper.rb
  app/models/submission.rb
  app/runners/result_constructor.rb
  app/runners/submission_runner.rb
  config/locales/models/en.yml
  config/locales/models/nl.yml
  public/schemas/judge_output.json
  public/schemas/partial_output.json
  test/runners/submission_runner_test.rb
Labels: feature

#1899 Nullify user email
  app/models/user.rb
  test/models/user_test.rb
Labels: bug fix

#1925 Fix viewing activity removed from repository
  app/models/activity.rb
  test/controllers/activities_controller_test.rb
Labels: bug fix

#1931 Make sure homepage can be loaded when user has submitted to content page
  app/models/user.rb
  test/controllers/pages_controller_test.rb
Labels: bug fix

#1933 Staff should be able to see info pages of public activities in courses they don't administrate
  app/policies/course_policy.rb
  app/policies/series_policy.rb
Labels: bug fix

#1926 Add type field to activity json
  app/views/activities/_activity.json.jbuilder
Labels: feature

#1932 Improve course load performance
  app/controllers/courses_controller.rb
  app/models/series.rb
  app/views/courses/_scoresheet_table.html.erb
  app/views/courses/scoresheet.json.jbuilder
  app/views/series/_course_series_table.html.erb
  app/views/series/_series.html.erb
Labels: bug fix

#1935 Fix filtering of submissions after submit
  app/assets/javascripts/exercise.js
Labels: bug fix

#1934 Don't link to recent exercise that is inaccessible
  app/views/pages/_user_card.html.erb
Labels: bug fix

#1937 Downgrade jQuery
  package.json
  vendor/assets/javascripts/bootstrap/collapse.js
  vendor/assets/javascripts/vendor.js
  yarn.lock
Labels: bug fix

#1942 Fix SVG tooltip placement by not placing tooltips on SVGs
  app/views/application/_progress_chart.html.erb
  app/views/application/_read_chart.html.erb
Labels: bug fix

#1946 Fix performance regression on course page load
  app/views/series/_series.html.erb
Labels: bug fix

#1948 memoize the course admin check
  app/models/user.rb
  test/models/user_test.rb
Labels: bug fix

#1875 Fix copy button location
  app/assets/stylesheets/components/code_listing.css.less
Labels: feature

#1949 Fix activity status invalidation
  app/models/activity.rb
  test/models/activity_status_test.rb
Labels: bug fix

#1955 Add annotation status to submission json
  app/views/submissions/_submission_basic.json.jbuilder
Labels: feature
