Repository dodona-edu/dodona, pull requests merged in 2020-05, with the labels that each got.

#1965 Fix outdated exercise use in course copy
  app/controllers/courses_controller.rb
Labels: bug fix

#1966 Fix CourseMembership foreign keys in db
  db/migrate/20200504090034_course_membership_foreign_keys.rb
  db/schema.rb
Labels: bug fix

#1967 Fix unread notification favicon always being shown
  app/views/layouts/application.html.erb
Labels: bug fix

#1973 Some exercises don't have a programming language
  app/views/activities/info.html.erb
Labels: bug fix

#1974 Change 'open on github' to 'open the repository'
  config/locales/views/activities/en.yml
  config/locales/views/activities/nl.yml
Labels: bug fix

#1976 Add exercise name to page title of submission
  app/controllers/submissions_controller.rb
Labels: feature

#1993 Fix index behaviour in activity status
  app/models/activity_status.rb
  app/models/course_membership.rb
  db/migrate/20200514073357_activity_status_index_series_non_nil.rb
  db/schema.rb
  test/factories/activity_statuses.rb
  test/models/activity_status_test.rb
  test/models/course_membership_test.rb
  test/models/exercise_test.rb
Labels: bug fix

#1998 Fix iframe resizing
  app/javascript/packs/exercise.js
Labels: bug fix

#1999 Only enable datadog in deployed environments
  config/initializers/datadog-tracer.rb
Labels: chore

#2009 Wait for database when running tests
  .github/workflows/ruby.yml
  .github/workflows/system-test.yml
Labels: chore
