Repository dodona-edu/dodona, pull requests merged in 2020-10, with the labels that each got.

#2309 Add some tests for LTI-related stuff
  lib/LTI/jwk.rb
  test/controllers/auth/omniauth_callbacks_controller_test.rb
  test/controllers/lti_controller_test.rb
  test/files/private_key.pem
  test/files/public_key.pem
  test/test_helper.rb
  test/testhelpers/lti_test_helper.rb
Labels: no-release-notes

#2299 UI tweaks for question table
  app/assets/javascripts/code_listing/question_annotation.ts
  app/assets/javascripts/code_listing/user_annotation.ts
  app/assets/javascripts/i18n/translations.js
  app/assets/javascripts/question_table.ts
  app/assets/stylesheets/models/questions.css.less
  app/controllers/annotations_controller.rb
  app/controllers/courses_controller.rb
  app/models/annotation.rb
  app/models/course.rb
  app/models/question.rb
  app/policies/question_policy.rb
  app/views/annotations/_annotation.json.jbuilder
  app/views/courses/_navbar_links.html.erb
  app/views/courses/_question_table.html.erb
  app/views/courses/questions.html.erb
  app/views/courses/questions.js.erb
  config/locales/js/en.yml
  config/locales/js/nl.yml
  config/locales/views/courses/en.yml
  config/locales/views/courses/nl.yml
  db/migrate/20200924072242_add_last_updated_by_to_questions.rb
  db/schema.rb
  test/factories/annotations.rb
  test/models/annotation_test.rb
Labels: feature

#2302 Show number of unanswered questions in title of question page
  app/assets/javascripts/favicon.ts
  app/assets/javascripts/notification.ts
  app/assets/javascripts/util.js
  app/controllers/application_controller.rb
  app/controllers/courses_controller.rb
  app/javascript/packs/application.js
  app/javascript/packs/course.js
  app/views/courses/questions.js.erb
  app/views/layouts/application.html.erb
  app/views/notifications/_notifications_table.html.erb
  app/views/notifications/_small_notifications_table.html.erb
  config/locales/views/courses/en.yml
  config/locales/views/courses/nl.yml
  test/controllers/courses_controller_test.rb
Labels: feature

#2308 Check notifications every minute
  app/assets/javascripts/notification.ts
  app/controllers/notifications_controller.rb
  app/views/layouts/_navbar.html.erb
  app/views/notifications/index.js.erb
Labels: feature

#2310 Periodically reload to watch for new submissions II
  app/assets/javascripts/auto_reload.ts
  app/assets/javascripts/i18n/translations.js
  app/assets/javascripts/index.js
  app/controllers/submissions_controller.rb
  app/javascript/packs/index.js
  app/views/layouts/_searchbar.html.erb
  app/views/submissions/index.html.erb
  config/locales/js/en.yml
  config/locales/js/nl.yml
  config/locales/views/submissions/en.yml
  config/locales/views/submissions/nl.yml
  package.json
  test/controllers/submissions_controller_test.rb
  yarn.lock
Labels: feature

#2323 Handle kid error more gracefully
  app/controllers/concerns/set_lti_message.rb
  config/locales/views/defaults/en.yml
  config/locales/views/defaults/nl.yml
  test/controllers/lti_controller_test.rb
  test/testhelpers/lti_test_helper.rb
Labels: bug fix

#2327 Fix question ordering
  app/controllers/courses_controller.rb
Labels: bug fix

#2328 Update to ruby 2.7.2
  .github/workflows/ruby.yml
  .github/workflows/system-test.yml
  .ruby-version
  Gemfile
  Gemfile.lock
  config/application.rb
  lib/warning.rb
Labels: chore

#2330 Update question notification dot in navbar
  app/assets/javascripts/question_table.ts
  app/javascript/packs/course.js
  app/views/courses/_navbar_links.html.erb
  app/views/courses/questions.js.erb
Labels: bug fix

#2325 Highlight whole lines in code listing
  app/assets/stylesheets/components/code_listing.css.less
Labels: bug fix

#2340 Fix question pagination when refreshing
  app/assets/javascripts/question_table.ts
Labels: bug fix

#2344 Emphasize course registration button
  app/helpers/courses_helper.rb
Labels: feature

#2339 Fix feedback table backgrounds in dark mode
  app/assets/stylesheets/theme/rouge-dark.css.less
Labels: bug fix

#2346 Show link to contact page on login error
  app/controllers/auth/omniauth_callbacks_controller.rb
  app/helpers/application_helper.rb
  app/views/layouts/_main_container.html.erb
  config/locales/views/defaults/en.yml
  config/locales/views/defaults/nl.yml
  config/locales/views/pages/en.yml
  config/locales/views/pages/nl.yml
Labels: feature

#2350 Invalidate series status cache on deadline change
  app/models/series.rb
  app/models/submission.rb
  test/models/series_test.rb
  test/test_helper.rb
  test/testhelpers/cache_helper.rb
Labels: bug fix

#2363 Clear activity status store when performing a new job
  config/initializers/delayed_job_config.rb
Labels: bug

#2365 Create read state within course if content page is opened in course without series
  app/views/activities/show.html.erb
Labels: bug fix, for-hotfix
