Repository dodona-edu/dodona, pull requests merged in 2020-11, with the labels that each got.

#2376 Reword question button in English
  config/locales/views/courses/en.yml
Labels: bug fix

#2354 Question overview page
  app/assets/javascripts/i18n/translations.js
  app/assets/javascripts/index.js
  app/assets/javascripts/question_table.ts
  app/assets/stylesheets/models/questions.css.less
  app/controllers/annotations_controller.rb
  app/javascript/packs/course.js
  app/javascript/packs/questions.js
  app/models/annotation.rb
  app/policies/question_policy.rb
  app/views/annotations/_questions_table.html.erb
  app/views/annotations/question_index.html.erb
  app/views/annotations/question_index.js.erb
  app/views/annotations/question_index.json.jbuilder
  app/views/layouts/_drawer.html.erb
  app/views/layouts/_navbar.html.erb
  app/views/layouts/_searchbar.html.erb
  config/locales/js/en.yml
  config/locales/js/nl.yml
  config/locales/models/en.yml
  config/locales/models/nl.yml
  config/locales/views/annotations/en.yml
  config/locales/views/annotations/nl.yml
  config/locales/views/courses/en.yml
  config/locales/views/courses/nl.yml
  config/locales/views/defaults/en.yml
  config/locales/views/defaults/nl.yml
  config/routes.rb
  test/controllers/annotations_controller_test.rb
  test/factories/submissions.rb
Labels: feature

#2393 Use Rails logger for Omniauth
  config/initializers/omniauth.rb
Labels: no-release-notes

#2395 Add indicator of tab permission
  app/assets/stylesheets/models/submissions.css.less
  app/helpers/renderers/feedback_table_renderer.rb
  config/locales/views/submissions/en.yml
  config/locales/views/submissions/nl.yml
Labels: feature

#2394 Link to student & exercise in evaluation
  app/views/feedbacks/show.html.erb
  config/locales/views/feedbacks/en.yml
  config/locales/views/feedbacks/nl.yml
Labels: feature

#2396 Use activity path for media in submission view
  app/assets/javascripts/pythia_submission.js
  app/helpers/renderers/pythia_renderer.rb
Labels: bug fix

#2404 Reset to origin HEAD instead of hard-coded master branch
  app/models/concerns/gitable.rb
Labels: bug fix
