Repository dodona-edu/dodona, pull requests merged in 2020-08, with the labels that each got.

#2130 Made order of series in course scoresheet logical
  app/models/course.rb
Labels: bug fix

#2144 Zero submission message now uses full row
  app/views/feedbacks/show.html.erb
Labels: bug fix

#2151 Added light-only and dark-only css classes to hide when needed
  app/assets/stylesheets/theme/theme-dark.css.less
  app/assets/stylesheets/theme/theme-light.css.less
Labels: feature

#2176 Add "summary" to the seeded activity data
  db/seeds.rb
Labels: chore

#2188 Fix MathJax crash when feedback is present
  app/assets/javascripts/exercise.js
  app/views/feedbacks/show.html.erb
  app/views/submissions/_description.html.erb
Labels: bug fix

#2189 Fix MathJax
  app/assets/javascripts/exercise.js
  app/helpers/renderers/feedback_code_renderer.rb
  app/views/feedbacks/show.html.erb
  app/views/submissions/_description.html.erb
Labels: bug fix
