Repository dodona-edu/dodona, pull requests merged in 2020-02, with the labels that each got.

#1684 Fix mocha deprecation warning by making sure the timer thread is always killed
  app/runners/submission_runner.rb
Labels: chore, no-release-notes

#1686 Remove outdated option from config and README
  README.md
  config/application.rb
Labels: chore, no-release-notes

#1687 Limit memory usage of statistics calculations
  app/models/submission.rb
Labels: bug fix

#1698 Init tooltips when dynamically loading course members
  app/views/course_members/index.js.erb
Labels: bug fix

#1709 Fix most navbar links showing up for logged out users
  app/helpers/application_helper.rb
Labels: bug fix

#1710 Don't try to read result file if submission is queued or running
  app/models/submission.rb
  test/models/submission_test.rb
  test/renderers/renderers_test.rb
Labels: bug fix

#1541 hide warnings and info messages by default when there are errors in code tab
  app/assets/javascripts/code_listing.ts
  app/assets/javascripts/code_listing/annotation.ts
  app/assets/javascripts/code_listing/code_listing.ts
  app/assets/javascripts/exercise.js
  app/assets/javascripts/i18n/translations.js
  app/assets/stylesheets/components/code_listing.css.less
  app/helpers/renderers/feedback_code_renderer.rb
  app/helpers/renderers/feedback_table_renderer.rb
  app/javascript/packs/submission.js
  config/locales/js/en.yml
  config/locales/js/nl.yml
  config/locales/views/submissions/en.yml
  config/locales/views/submissions/nl.yml
  jest.config.js
  test/javascript/code_listing.test.ts
Labels: feature

#1574 add line numbers to external text file
  app/assets/javascripts/pythia_submission.js
  app/assets/stylesheets/components/tutor.css.less
Labels: feature

#1729 Fix info page crash
  app/helpers/renderers/feedback_code_renderer.rb
  test/helpers/stub_helper.rb
  test/models/exercise_test.rb
  test/remotes/exercises/echo/echo/solution/solution.py
Labels: bug fix

#1731 Force UTF-8 encoding for solutions
  app/models/exercise.rb
Labels: bug fix
