Repository dodona-edu/dodona, pull requests merged in 2020-09, with the labels that each got.

#2202 Fix activities info page
  app/views/activities/info.html.erb
  test/controllers/activities_controller_test.rb
Labels: bug fix

#2232 Fix double border in code blocks in global annotations
  app/assets/stylesheets/components/code_listing.css.less
Labels: bug fix

#2241 Fix bug when wrapping long lines
  app/assets/stylesheets/components/code_listing.css.less
Labels: bug fix

#2243 Allow searching by label, programming language and judge on the repository show page
  app/controllers/repositories_controller.rb
  app/models/activity.rb
  app/models/repository.rb
  app/views/repositories/show.html.erb
Labels: bug fix

#2246 Catch invalid providers
  lib/SAML/setup.rb
  lib/SAML/strategy.rb
Labels: bug fix

#2253 Use editor_name of programming language when rendering with Rouge
  app/helpers/renderers/feedback_table_renderer.rb
  app/views/activities/info.html.erb
Labels: bug fix

#2257 Fix long activity navigations
  app/assets/stylesheets/models/course.css.less
  app/views/activities/show.html.erb
Labels: bug fix

#2262 Small sign-in fixes
  app/assets/javascripts/sign_in.js
  app/controllers/auth/authentication_controller.rb
  app/views/auth/sign_in.html.erb
Labels: bug fix

#2260 Add in-page setting to enable/disable questions
  app/controllers/courses_controller.rb
  app/views/courses/questions.html.erb
  app/views/courses/reload_questions.js.erb
  config/locales/views/courses/en.yml
  config/locales/views/courses/nl.yml
Labels: feature

#2264 Prompt when logging in from LTI
  app/controllers/activities_controller.rb
  app/controllers/concerns/set_lti_message.rb
  app/controllers/courses_controller.rb
  app/controllers/lti_controller.rb
  app/controllers/series_controller.rb
  app/views/activities/show.html.erb
  app/views/courses/_not_a_member_dialog.html.erb
  app/views/courses/show.html.erb
  app/views/series/show.html.erb
  config/locales/views/courses/en.yml
  config/locales/views/courses/nl.yml
  lib/LTI/messages.rb
  lib/LTI/messages/claims.rb
  lib/LTI/messages/types/resource_launch_request.rb
Labels: feature

#2263 Make programming languages editable
  app/assets/stylesheets/models.css.less
  app/assets/stylesheets/models/programming_languages.css.less
  app/policies/programming_language_policy.rb
  app/views/programming_languages/_form.html.erb
  app/views/programming_languages/index.html.erb
  app/views/programming_languages/show.html.erb
Labels: feature

#2280 Fix user link in question table
  app/views/courses/_question_table.html.erb
Labels: bug fix

#2286 Fix network always being disabled on the info page
  app/views/activities/info.html.erb
Labels: bug fix

#2287 Fix webpacker warnings about deprecated config
  config/initializers/webpacker.rb
Labels: chore, no-release-notes

#2285 Respect LTI language if present
  app/controllers/application_controller.rb
  app/controllers/concerns/set_lti_message.rb
  app/helpers/application_helper.rb
  test/helpers/application_helper_test.rb
Labels: feature

#2288 Enable new rubocop cops by default
  .rubocop.yml
  app/controllers/activities_controller.rb
  app/controllers/application_controller.rb
  app/controllers/auth/saml_controller.rb
  app/controllers/concerns/set_lti_message.rb
  app/controllers/courses_controller.rb
  app/controllers/submissions_controller.rb
  app/helpers/activity_helper.rb
  app/helpers/application_helper.rb
  app/helpers/export_helper.rb
  app/helpers/lti_helper.rb
  app/helpers/renderers/feedback_table_renderer.rb
  app/helpers/renderers/pythia_renderer.rb
  app/models/activity.rb
  app/models/activity_status.rb
  app/models/annotation.rb
  app/models/concerns/gitable.rb
  app/models/concerns/tokenable.rb
  app/models/course_membership.rb
  app/models/evaluation.rb
  app/models/feedback.rb
  app/models/repository.rb
  app/models/series.rb
  app/models/submission.rb
  app/models/transient/aggregated_config_errors.rb
  app/models/transient/config_parse_error.rb
  app/models/user.rb
  app/policies/application_policy.rb
  app/runners/result_constructor.rb
  app/runners/submission_runner.rb
  test/controllers/activities_controller_test.rb
  test/controllers/application_controller_test.rb
  test/controllers/exports_controller_test.rb
  test/factories/content_pages.rb
  test/factories/exercises.rb
  test/factories/judges.rb
  test/factories/providers.rb
  test/factories/repositories.rb
  test/models/exercise_test.rb
  test/models/repository_test.rb
  test/models/user_test.rb
  test/renderers/renderers_test.rb
  test/testhelpers/delayed_job_helper.rb
  test/testhelpers/remote_helper.rb
  test/testhelpers/stub_helper.rb
Labels: chore, no-release-notes

#2291 Only show manage series message to course admins
  app/views/courses/show.html.erb
  config/locales/views/courses/en.yml
  config/locales/views/courses/nl.yml
Labels: bug fix

#2292 Fixes for LTI series URL
  app/helpers/lti_helper.rb
  test/helpers/lti_helper_test.rb
Labels: bug fix

#2293 Revert rework of homepage cards
  app/assets/javascripts/favorite_course_buttons.js
  app/assets/javascripts/masonry.ts
  app/assets/stylesheets/pages/home.css.less
  app/javascript/packs/favorite_course_buttons.js
  app/javascript/packs/home_page.js
  app/views/pages/home.html.erb
Labels: bug fix

#2294 Rework MathJax initialisation
  app/assets/javascripts/code_listing/annotation.ts
  app/assets/javascripts/code_listing/code_listing.ts
  app/assets/javascripts/exercise.js
  app/helpers/renderers/feedback_code_renderer.rb
  app/javascript/packs/description.js
  app/views/activities/description.html.erb
  app/views/feedbacks/show.html.erb
  app/views/submissions/_description.html.erb
Labels: bug fix

#2289 Small refactor in questions
  app/assets/javascripts/code_listing/annotation.ts
  app/assets/javascripts/code_listing/question_annotation.ts
  app/assets/javascripts/question_table.ts
  app/controllers/annotations_controller.rb
  app/models/question.rb
  app/policies/annotation_policy.rb
  app/policies/question_policy.rb
  app/views/annotations/_annotation.json.jbuilder
  app/views/courses/_question_table.html.erb
  config/routes.rb
  test/controllers/annotations_controller_test.rb
Labels: no-release-notes

#2295 Prevent crash if creating annotation while logged out
  app/controllers/annotations_controller.rb
  test/controllers/annotations_controller_test.rb
Labels: bug fix

#2297 Fix MathJax not being loaded on activity page
  app/assets/javascripts/exercise.js
  app/helpers/renderers/feedback_code_renderer.rb
  app/views/activities/show.html.erb
  app/views/feedbacks/show.html.erb
Labels: bug fix

#2303 Flip page & site name in page title
  app/views/layouts/application.html.erb
Labels: feature

#2298 Configure base href on medusa
  app/views/layouts/frame.html.erb
Labels: bug fix

#2304 (Some) login page improvements
  app/assets/javascripts/sign_in.js
  app/controllers/auth/authentication_controller.rb
  app/views/auth/sign_in.html.erb
Labels: bug fix
