Repository dodona-edu/dodona, pull requests merged in 2020-07, with the labels that each got.

#2072 Rework SAML authentication
  Gemfile
  Gemfile.lock
  app/controllers/application_controller.rb
  app/controllers/omniauth_callbacks_controller.rb
  app/controllers/pages_controller.rb
  app/controllers/saml_sessions_controller.rb
  app/models/user.rb
  app/views/layouts/_drawer.html.erb
  app/views/layouts/_navbar.html.erb
  app/views/pages/sign_in_page.html.erb
  config/attribute-map.yml
  config/initializers/devise.rb
  config/routes.rb
  lib/SAML/attributes.rb
  lib/SAML/idp_settings_adapter.rb
  lib/SAML/metadata.rb
  lib/SAML/my_resource_validator.rb
  lib/SAML/saml_controller.rb
  lib/SAML/settings.rb
  lib/SAML/setup.rb
  lib/SAML/strategy.rb
  test/controllers/pages_controller_test.rb
  test/controllers/saml_controller_test.rb
Labels: feature

#2065 Authentication rework [depends on #2072]
  app/controllers/application_controller.rb
  app/controllers/auth/authentication_controller.rb
  app/controllers/auth/omniauth_callbacks_controller.rb
  app/controllers/auth/saml_controller.rb
  app/controllers/omniauth_callbacks_controller.rb
  app/controllers/pages_controller.rb
  app/controllers/saml_sessions_controller.rb
  app/models/identity.rb
  app/models/institution.rb
  app/models/provider.rb
  app/models/provider/g_suite.rb
  app/models/provider/office365.rb
  app/models/provider/saml.rb
  app/models/provider/smartschool.rb
  app/models/user.rb
  app/views/auth/sign_in.html.erb
  app/views/layouts/_drawer.html.erb
  app/views/layouts/_navbar.html.erb
  config/locales/views/auth/en.yml
  config/locales/views/auth/nl.yml
  config/locales/views/pages/en.yml
  config/locales/views/pages/nl.yml
  config/routes.rb
  db/migrate/20200618115755_create_providers.rb
  db/migrate/20200618115756_create_identities.rb
  db/migrate/20200619201239_extract_institution_auth_to_providers.rb
  db/migrate/20200625150204_extract_usernames_to_identities.rb
  db/schema.rb
  db/seeds.rb
  lib/SAML/settings.rb
  lib/SAML/setup.rb
  lib/SAML/strategy.rb
  test/controllers/auth/authentication_controller_test.rb
  test/controllers/auth/omniauth_callbacks_controller_test.rb
  test/controllers/auth/saml_controller_test.rb
  test/controllers/omniauth_callbacks_controller_test.rb
  test/controllers/pages_controller_test.rb
  test/controllers/saml_controller_test.rb
  test/factories/identities.rb
  test/factories/institutions.rb
  test/factories/providers.rb
  test/models/identity_test.rb
  test/models/institution_test.rb
  test/models/provider_test.rb
  test/models/saml_provider_test.rb
  test/models/user_test.rb
  test/test_helper.rb
  test/testhelpers/constants.rb
Labels: feature

#2102 Fix institution views
  app/controllers/institutions_controller.rb
  app/models/provider.rb
  app/models/provider/saml.rb
  app/views/institutions/_form.html.erb
  app/views/institutions/edit.html.erb
  app/views/institutions/index.html.erb
  app/views/institutions/show.html.erb
  config/locales/models/en.yml
  config/locales/models/nl.yml
  config/locales/views/institutions/en.yml
  config/locales/views/institutions/nl.yml
  test/controllers/institution_controller_test.rb
Labels: bug fix

#2103 Disable multithreading in system tests
  .github/workflows/system-test.yml
Labels: chore

#2104 Fix static home json
  app/controllers/pages_controller.rb
  app/views/pages/_static_home.json.jbuilder
  app/views/pages/home.json.jbuilder
  test/controllers/pages_controller_test.rb
Labels: bug fix

#2128 Fix broken deploy caused by "Bump eslint from 7.4.0 to 7.5.0"
  yarn.lock
Labels: bug fix
