Repository dodona-edu/dodona, pull requests merged in 2020-01, with the labels that each got.

#1625 Docker: don't limit device IO in development env
  .rubocop.yml
  app/runners/submission_runner.rb
Labels: chore

#1626 Element type of tr, not class tr
  app/assets/javascripts/code_listing.ts
Labels: bug fix

#1630 Fix double newline by overriding the copy behaviour of browsers
  app/assets/javascripts/code_listing.ts
  app/assets/stylesheets/components/code_listing.css.less
Labels: bug fix

#1598 Fix inaccessible private hidden exercise media
  app/assets/javascripts/exercise.js
  app/assets/javascripts/submission.js
  app/controllers/exercises_controller.rb
  app/controllers/submissions_controller.rb
  app/helpers/renderers/pythia_renderer.rb
  app/models/exercise.rb
  app/models/user.rb
  app/policies/course_policy.rb
  app/views/exercises/description.html.erb
  config/routes.rb
  test/controllers/exercises_controller_test.rb
  test/controllers/submissions_controller_test.rb
Labels: bug fix

#1631 Automatically scroll into view when highlighting a line
  app/assets/javascripts/code_listing.ts
  app/assets/javascripts/submission.js
Labels: feature

#1635 Generalize token generation
  app/controllers/series_controller.rb
  app/models/concerns/tokenable.rb
  app/models/course.rb
  app/models/exercise.rb
  app/models/series.rb
  app/models/series_membership.rb
  app/models/user.rb
  db/migrate/20181113103618_add_access_token_to_all_series.rb
  test/controllers/exercises_controller_test.rb
  test/controllers/export_controller_test.rb
  test/controllers/series_controller_test.rb
  test/controllers/submissions_controller_test.rb
  test/factories/series.rb
  test/helpers/stub_helper.rb
  test/models/exercise_test.rb
  test/models/series_test.rb
  test/models/transient/series_summary_test.rb
Labels: bug fix

#1651 Fix login for Smartschool users
  app/controllers/omniauth_callbacks_controller.rb
Labels: bug fix

#1659 Fix typo
  config/locales/views/series/nl.yml
Labels: bug fix

#1674 Fix page jumps after an iframe resize
  app/assets/javascripts/exercise.js
  app/helpers/exercise_helper.rb
  app/javascript/packs/exercise.js
  yarn.lock
Labels: bug fix

#1673 Fix a styling issue
  test/helpers/stub_helper.rb
Labels: chore, no-release-notes

#1672 Only our own iframes should be 100% width
  app/assets/stylesheets/layout.css.less
  app/helpers/exercise_helper.rb
Labels: bug fix

#1676 Fix wrong translation key in course scoresheet header
  app/views/courses/_scoresheet_table.html.erb
Labels: bug fix

#1675 Show a message on the scoresheet when a series doesn't contain any exercises
  app/views/series/scoresheet.html.erb
  config/locales/views/series/en.yml
  config/locales/views/series/nl.yml
Labels: bug fix

#1489 exercise information page
  app/assets/stylesheets/models/exercises.css.less
  app/controllers/exercises_controller.rb
  app/helpers/application_helper.rb
  app/helpers/exercise_helper.rb
  app/helpers/renderers/feedback_code_renderer.rb
  app/helpers/renderers/feedback_table_renderer.rb
  app/helpers/repository_helper.rb
  app/models/concerns/gitable.rb
  app/models/exercise.rb
  app/models/repository.rb
  app/models/user.rb
  app/policies/course_policy.rb
  app/policies/exercise_policy.rb
  app/policies/series_policy.rb
  app/runners/submission_runner.rb
  app/views/exercises/_navbar_links.html.erb
  app/views/exercises/edit.html.erb
  app/views/exercises/info.html.erb
  config/locales/models/en.yml
  config/locales/models/nl.yml
  config/locales/views/defaults/en.yml
  config/locales/views/defaults/nl.yml
  config/locales/views/exercises/en.yml
  config/locales/views/exercises/nl.yml
  config/routes.rb
  db/seeds.rb
  test/controllers/exercises_controller_test.rb
  test/helpers/stub_helper.rb
  test/models/exercise_test.rb
  test/remotes/exercises/lasagna/exercises/dirconfig.json
  test/remotes/exercises/lasagna/exercises/extra/echo/config.json
  test/remotes/exercises/lasagna/exercises/extra/echo/description/description.en.html
  test/remotes/exercises/lasagna/exercises/extra/echo/description/description.nl.html
  test/remotes/exercises/lasagna/exercises/series/ISBN/config.json
  test/remotes/exercises/lasagna/exercises/series/ISBN/description/description.en.html
  test/remotes/exercises/lasagna/exercises/series/ISBN/description/description.nl.html
  test/remotes/exercises/lasagna/exercises/series/ISBN/description/media/ISBN.gif
  test/remotes/exercises/lasagna/exercises/series/ISBN/description/media/evaluation_barcode.jpg
  test/remotes/exercises/lasagna/exercises/series/dirconfig.json
Labels: feature

#1677 Allow normal users to search submissions
  app/controllers/submissions_controller.rb
  app/views/submissions/index.html.erb
  test/controllers/submissions_controller_test.rb
Labels: bug fix

#1679 Fix rubocop warning: unused variable
  .github/workflows/ruby.yml
  .rubocop.yml
  test/controllers/submissions_controller_test.rb
Labels: chore, no-release-notes

#1678 Fix asymmetry of brand logo
  app/assets/stylesheets/layout/navbar.css.less
Labels: bug fix
