Repository dodona-edu/dodona, pull requests merged in 2021-07, with the labels that each got.

#2905 Fix typo: ask question instead of pose question
  config/locales/views/courses/en.yml
  test/system/questions_test.rb
Labels: bug

#2904 Add dark mode sponsor logos
  app/assets/images/idp/UGent.png
  app/assets/images/ugent.en.white.png
  app/assets/images/ugent.nl.png
  app/assets/images/ugent.nl.white.png
  app/assets/images/we.en.white.png
  app/assets/images/we.nl.white.png
  app/assets/stylesheets/theme/theme-dark.css.scss
  app/assets/stylesheets/theme/theme-light.css.scss
  app/views/pages/_about.html.erb
  app/views/pages/_team.en.html.erb
  app/views/pages/_team.nl.html.erb
  app/views/pages/support.html.erb
  db/seeds.rb
Labels: bug

#2909 Use built-in yarn cache for GitHub Actions
  .github/workflows/lint.yml
  .github/workflows/test.yml
Labels: chore

#2908 Change clipboard icon to avoid confusion
  app/helpers/application_helper.rb
  app/helpers/renderers/feedback_code_renderer.rb
Labels: enhancement

#2917 Fix spinning score items
  app/assets/javascripts/feedback/score.ts
  app/views/feedbacks/_score_actions.html.erb
  test/system/feedbacks_test.rb
Labels: bug

#2907 Add icons to all dropdown menus
  app/views/courses/show.html.erb
  app/views/evaluations/show.html.erb
  app/views/score_items/new.html.erb
  app/views/users/show.html.erb
Labels: enhancement
