Repository dodona-edu/dodona, pull requests merged in 2021-09, with the labels that each got.

#3024 Dodona 5.0 design tweaks
  app/assets/stylesheets/bootstrap_variable_overrides.css.scss
  app/assets/stylesheets/components/btn.css.scss
  app/assets/stylesheets/components/card.css.scss
  app/assets/stylesheets/components/heatmap.css.scss
  app/assets/stylesheets/pages/home.css.scss
  app/assets/stylesheets/theme/theme-light.css.scss
  app/models/course.rb
  app/policies/course_policy.rb
  app/views/courses/_form.html.erb
  app/views/pages/_user_card.html.erb
  config/locales/models/en.yml
  config/locales/models/nl.yml
Labels: feature

#3054 Show stats about questions on statistics page
  app/controllers/courses_controller.rb
  app/views/courses/statistics.html.erb
  config/locales/views/courses/en.yml
  config/locales/views/courses/nl.yml
Labels: feature

#3059 Make sure institutions get merged even if there are users with no email
  app/models/institution.rb
  test/models/institution_test.rb
Labels: bug

#3056 Fix searching users using labels
  app/assets/javascripts/util.js
  app/controllers/courses_controller.rb
  test/javascript/util.test.js
Labels: bug

#3062 Remove "created" and "last edited" in activity info
  app/views/activities/info.html.erb
  config/locales/views/activities/en.yml
  config/locales/views/activities/nl.yml
Labels: enhancement

#3058 Enable user search in evaluations
  app/controllers/evaluations_controller.rb
  app/views/evaluations/_evaluation_grade_table.html.erb
  app/views/evaluations/_evaluation_table.html.erb
  app/views/evaluations/show.html.erb
  app/views/evaluations/show.js.erb
Labels: feature

#3061 Support multiple callout message formats
  app/helpers/renderers/feedback_table_renderer.rb
  public/schemas/judge_output.json
  public/schemas/partial_output.json
Labels: feature

#3064 Filter scoresheet also on reading activities
  app/controllers/courses_controller.rb
  app/controllers/series_controller.rb
  app/models/user.rb
Labels: feature

#3084 Reduce requested scope when LTI provider is Ufora
  lib/LTI/auth/settings.rb
Labels: bug

#3083 New office365 client secret
  config/credentials.yml.enc
Labels: enhancement

#3081 Change default course permissions
  app/controllers/courses_controller.rb
Labels: enhancement

#3080 Make evaluation creation a full stepper
  app/assets/javascripts/evaluation.ts
  app/assets/stylesheets/components/stepper.css.scss
  app/controllers/evaluations_controller.rb
  app/controllers/score_items_controller.rb
  app/javascript/packs/evaluation.js
  app/views/evaluations/_add_users.html.erb
  app/views/evaluations/_edit_users.html.erb
  app/views/evaluations/_form.html.erb
  app/views/evaluations/_members_table.html.erb
  app/views/evaluations/_score_items.html.erb
  app/views/evaluations/add_user.js.erb
  app/views/evaluations/add_users.html.erb
  app/views/evaluations/create.js.erb
  app/views/evaluations/edit.html.erb
  app/views/evaluations/edit.js.erb
  app/views/evaluations/new.html.erb
  app/views/evaluations/new.js.erb
  app/views/evaluations/refresh_users.js.erb
  app/views/evaluations/remove_user.js.erb
  app/views/evaluations/show.html.erb
  app/views/score_items/add_all.js.erb
  app/views/score_items/index.html.erb
  app/views/score_items/new.html.erb
  config/locales/views/evaluations/en.yml
  config/locales/views/evaluations/nl.yml
  config/routes.rb
  test/controllers/evaluations_controller_test.rb
  test/controllers/score_items_controller_test.rb
  test/system/score_items_test.rb
Labels: feature

#3087 Expose accepted status of exercises via API
  app/views/activities/_activity.json.jbuilder
Labels: feature

#3085 Change wording for incomplete submissions in grading overview
  config/locales/views/evaluations/en.yml
  config/locales/views/evaluations/nl.yml
Labels: bug

#3086 Make sure info page for invalid exercises can still be viewed
  app/controllers/activities_controller.rb
  config/locales/views/activities/en.yml
  config/locales/views/activities/nl.yml
  test/controllers/activities_controller_test.rb
Labels: bug

#3100 Update HOGENT logo
  app/assets/images/idp/HoGent.png
Labels: enhancement

#3101 Fix stray left margin in series dropdown
  app/assets/stylesheets/components/card.css.scss
Labels: bug

#3091 Minor grading fixes
  app/assets/javascripts/evaluation.ts
  app/assets/stylesheets/components/evaluations.css.scss
  app/models/evaluation.rb
  app/views/evaluations/_evaluation_grade_table.html.erb
  app/views/evaluations/_form.html.erb
  app/views/evaluations/create.js.erb
  app/views/evaluations/new.html.erb
  app/views/evaluations/show.html.erb
  app/views/feedbacks/_feedback_actions.html.erb
  config/locales/views/evaluations/en.yml
  config/locales/views/evaluations/nl.yml
  config/locales/views/score_items/en.yml
  config/locales/views/score_items/nl.yml
Labels: bug

#3105 Fix timeseries graph only showing the last batch of data
  app/models/submission.rb
Labels: bug

#3106 Don't wrap visualisations nav buttons
  app/assets/stylesheets/components/card.css.scss
Labels: bug

#3065 Displaying & diffing judge CSV output
  app/assets/stylesheets/models/submissions.css.scss
  app/helpers/renderers/csv_differ.rb
  app/helpers/renderers/feedback_table_renderer.rb
  app/helpers/renderers/text_differ.rb
  app/runners/result_constructor.rb
  public/schemas/judge_output.json
  public/schemas/partial_output.json
  test/helpers/renderers/diff_csv_test.rb
Labels: feature

#3111 Make sure that destroying a course moves data files of affected submissions
  app/models/course.rb
  test/models/course_test.rb
Labels: bug

#3122 Fix height of series card after showing "not enough data"
  app/assets/javascripts/visualisations/series_graph.ts
Labels: bug
