Repository dodona-edu/dodona, pull requests merged in 2021-08, with the labels that each got.

#2906 Allow merging of institutions and add secondary providers
  Gemfile
  app/assets/javascripts/course.js
  app/assets/javascripts/institution.ts
  app/controllers/institutions_controller.rb
  app/javascript/packs/institution.js
  app/models/institution.rb
  app/models/provider.rb
  app/policies/institution_policy.rb
  app/views/institutions/_form.html.erb
  app/views/institutions/_merge_changes.html.erb
  app/views/institutions/_merge_table.html.erb
  app/views/institutions/edit.html.erb
  app/views/institutions/merge.html.erb
  app/views/institutions/merge.js.erb
  app/views/institutions/merge_changes.js.erb
  app/views/institutions/show.html.erb
  config/locales/views/institutions/en.yml
  config/locales/views/institutions/nl.yml
  config/routes.rb
  test/controllers/auth/omniauth_callbacks_controller_test.rb
  test/controllers/institution_controller_test.rb
  test/models/institution_test.rb
Labels: feature

#2938 Make sure `data` folder exists so that seeds can run
  .gitignore
  data/.keep
Labels: chore

#2949 Reduce use of light colors for scoring in dark mode
  app/assets/stylesheets/theme/theme-dark.css.scss
  app/views/feedbacks/_feedback_actions.html.erb
  app/views/feedbacks/_score_actions.html.erb
Labels: enhancement

#2951 Use alternative background color for line highlighting in dark mode
  app/assets/stylesheets/components/code_listing.css.scss
  app/assets/stylesheets/theme/theme-dark.css.scss
  app/assets/stylesheets/theme/theme-light.css.scss
Labels: bug

#2952 Make sure progress is updated when entering the last score while grading
  app/views/feedbacks/_feedback_actions.html.erb
  app/views/feedbacks/_progress_row.html.erb
  app/views/scores/show.js.erb
  config/locales/views/feedbacks/en.yml
  config/locales/views/feedbacks/nl.yml
Labels: bug

#2956 Fix system tests failing randomly
  test/system/score_items_test.rb
Labels: chore

#2927 Show feedback status when grading
  app/assets/javascripts/feedback/actions.ts
  app/assets/stylesheets/components/evaluations.css.scss
  app/views/feedbacks/_feedback_actions.html.erb
  app/views/scores/show.js.erb
Labels: feature

#2953 Rename annotations by users to comments in user interface
  app/assets/javascripts/i18n/translations.js
  config/locales/js/en.yml
  config/locales/js/nl.yml
  config/locales/views/annotations/en.yml
  config/locales/views/evaluations/en.yml
  config/locales/views/evaluations/nl.yml
  config/locales/views/feedbacks/en.yml
  config/locales/views/feedbacks/nl.yml
  config/locales/views/submissions/en.yml
  config/locales/views/submissions/nl.yml
  test/system/annotations_test.rb
Labels: feature

#2959 Don't allow out of bounds values when grading
  app/models/score.rb
  app/views/feedbacks/_score_actions.html.erb
  test/models/score_test.rb
  test/system/feedbacks_test.rb
Labels: enhancement

#2955 Improve user selection for evaluations
  app/assets/javascripts/evaluation.ts
  app/assets/stylesheets/components/evaluations.css.scss
  app/controllers/evaluations_controller.rb
  app/javascript/packs/evaluation.js
  app/views/evaluations/_member_row.html.erb
  app/views/evaluations/_members_table.html.erb
  app/views/evaluations/add_user.js.erb
  app/views/evaluations/add_users.html.erb
  app/views/evaluations/add_users.js.erb
  app/views/evaluations/edit.html.erb
  app/views/evaluations/edit.js.erb
  app/views/evaluations/remove_user.js.erb
  config/locales/views/evaluations/en.yml
  config/locales/views/evaluations/nl.yml
Labels: feature

#2958 Make background color of code blocks in annotations consistent
  app/assets/stylesheets/components/code_listing.css.scss
Labels: bug

#2960 Fix scrolling of iFrames on mobile
  app/helpers/activity_helper.rb
Labels: bug

#2962 Add a link to our facebook page to the footer
  app/views/layouts/_footer.html.erb
Labels: enhancement

#2964 Don't allow browsers to store cached versions of evaluation feedback pages
  app/controllers/feedbacks_controller.rb
Labels: bug

#2963 Update the copy of the right request emails
  app/views/rights_request_mailer/approved.en.html.erb
  app/views/rights_request_mailer/approved.en.text.erb
  app/views/rights_request_mailer/approved.nl.html.erb
  app/views/rights_request_mailer/approved.nl.text.erb
  app/views/rights_request_mailer/rejected.en.html.erb
  app/views/rights_request_mailer/rejected.en.text.erb
  app/views/rights_request_mailer/rejected.nl.html.erb
  app/views/rights_request_mailer/rejected.nl.text.erb
Labels: enhancement

#2966 Truncate column names in Grade overview
  app/assets/stylesheets/components/evaluations.css.scss
Labels: bug

#2967 Set current user's name as default value when creating a course
  app/controllers/courses_controller.rb
Labels: enhancement

#2954 Re-implement util functions using URL API
  app/assets/javascripts/exercise.js
  app/assets/javascripts/util.js
  app/views/activities/show.html.erb
  app/views/courses/index.html.erb
  test/javascript/util.test.js
Labels: enhancement

#2982 Add .editorconfig file
  .editorconfig
Labels: chore

#2961 Align rows in scoresheet
  app/assets/stylesheets/components/table.css.scss
Labels: bug

#2983 Move to hcaptcha
  Gemfile
  Gemfile.lock
  app/controllers/pages_controller.rb
  app/views/pages/contact.html.erb
  config/credentials.yml.enc
  config/credentials/staging.yml.enc
  config/initializers/hcaptcha.rb
  config/initializers/recaptcha.rb
  config/locales/views/pages/en.yml
  config/locales/views/pages/nl.yml
Labels: enhancement

#2994 Add profile scope to the LTI settings
  lib/LTI/auth/settings.rb
  test/controllers/lti_controller_test.rb
Labels: bug

#2976 Add feature `Add score item to all exercises` when editing score items
  app/controllers/score_items_controller.rb
  app/views/score_items/index.html.erb
Labels: bug

#3001 Remove puts from tests
  test/controllers/evaluations_controller_test.rb
Labels: chore

#3013 Update supported browsers
  .browserslistrc
Labels: chore

#2996 Use GLightbox instead of Strip as lightbox
  app/assets/javascripts/application.js
  app/assets/javascripts/exercise.js
  app/assets/stylesheets/libraries.css.scss
  app/assets/stylesheets/libraries/glightbox.css.scss
  package.json
  vendor/assets/javascripts/.keep
  vendor/assets/javascripts/strip/strip.pkgd.min.js
  vendor/assets/javascripts/vendor.js
  vendor/assets/stylesheets/strip/strip.css.scss
  vendor/assets/stylesheets/vendor.scss
  yarn.lock
Labels: enhancement

#2598 Exercise statistics visualisation
  app/assets/javascripts/i18n/translations.js
  app/assets/javascripts/series.js
  app/assets/javascripts/visualisations/cumulative_timeseries.ts
  app/assets/javascripts/visualisations/series_exercise_graph.ts
  app/assets/javascripts/visualisations/series_graph.ts
  app/assets/javascripts/visualisations/stacked_status.ts
  app/assets/javascripts/visualisations/timeseries.ts
  app/assets/javascripts/visualisations/violin.ts
  app/assets/stylesheets/components.css.scss
  app/assets/stylesheets/components/card.css.scss
  app/assets/stylesheets/components/heatmap.css.scss
  app/assets/stylesheets/components/visualisations.css.scss
  app/assets/stylesheets/models/series.css.scss
  app/controllers/statistics_controller.rb
  app/javascript/packs/series.js
  app/models/submission.rb
  app/policies/series_policy.rb
  app/views/application/icons/_heatmap.html.erb
  app/views/application/icons/_stacked-bar-chart.html.erb
  app/views/application/icons/_stacked-line-chart.html.erb
  app/views/application/icons/_violin.html.erb
  app/views/courses/show.html.erb
  app/views/series/_series.html.erb
  app/views/series/show.html.erb
  config/locales/defaults/en.yml
  config/locales/defaults/nl.yml
  config/locales/js/en.yml
  config/locales/js/nl.yml
  config/locales/views/series/en.yml
  config/locales/views/series/nl.yml
  config/routes.rb
  jest.config.js
  test/javascript/visualisations.test.ts
  test/models/submission_test.rb
  test/system/series_visualisations_test.rb
  tsconfig.json
Labels: feature

#3015 Provide correct user URL in submissions.json
  app/views/course_members/_course_member_data.json.jbuilder
  app/views/course_members/index.json.jbuilder
  app/views/course_members/show.json.jbuilder
  app/views/submissions/_submission_basic.json.jbuilder
Labels: bug

#2979 Add iCal link for syncing deadlines with external calendar
  Gemfile
  Gemfile.lock
  app/controllers/courses_controller.rb
  app/policies/course_policy.rb
  app/views/courses/show.html.erb
  config/locales/views/courses/en.yml
  config/locales/views/courses/nl.yml
  config/routes.rb
  test/controllers/courses_controller_test.rb
Labels: feature

#3027 Check if python judge should be used when seeding the database
  README.md
  db/seeds.rb
Labels: chore

#3012 Add student label to evaluation interface
  app/assets/stylesheets/components/evaluations.css.scss
  app/controllers/feedbacks_controller.rb
  app/views/feedbacks/_feedback_actions.html.erb
Labels: feature

#3055 Init institution merge table when loading table via JS
  app/views/institutions/merge.js.erb
Labels: bug
