Repository dodona-edu/dodona, pull requests merged in 2021-10, with the labels that each got.

#3136 Add info icon when question has newer submission
  app/assets/javascripts/code_listing/annotation.ts
  app/assets/javascripts/code_listing/code_listing.ts
  app/assets/javascripts/code_listing/question_annotation.ts
  app/assets/javascripts/i18n/translations.js
  app/assets/stylesheets/components/code_listing.css.scss
  app/models/question.rb
  app/views/annotations/_annotation.json.jbuilder
  config/locales/js/en.yml
  config/locales/js/nl.yml
Labels: feature

#3079 Implement OIDC identity provider
  Gemfile
  Gemfile.lock
  app/controllers/application_controller.rb
  app/controllers/auth/omniauth_callbacks_controller.rb
  app/models/institution.rb
  app/models/provider.rb
  app/models/provider/oidc.rb
  app/models/user.rb
  config/initializers/devise.rb
  config/locales/models/en.yml
  config/locales/models/nl.yml
  lib/LTI/jwk.rb
  lib/OIDC/auth.rb
  lib/OIDC/auth/settings.rb
  lib/OIDC/auth/setup.rb
  lib/OIDC/auth/strategy.rb
  lib/OIDC/client.rb
  test/controllers/lti_controller_test.rb
  test/factories/providers.rb
  test/files/keys/private_key.pem
  test/files/keys/public_key.pem
  test/integration/auth/vlaanderen/oidc_vlaanderen_test.rb
  test/integration/auth/vlaanderen/openid-configuration.json
  test/test_helper.rb
  test/testhelpers/jwks_helper.rb
  test/testhelpers/lti_test_helper.rb
Labels: feature

#3125 Rewrite series graph legends in HTML instead of SVG
  app/assets/javascripts/visualisations/cumulative_timeseries.ts
  app/assets/javascripts/visualisations/stacked_status.ts
  app/assets/stylesheets/components/visualisations.css.scss
Labels: enhancement

#3179 Make the scope of the readme and solutions clear
  app/views/activities/info.html.erb
  config/locales/views/activities/en.yml
  config/locales/views/activities/nl.yml
Labels: enhancement

#3192 Fix some typos
  README.md
  app/assets/stylesheets/components/tutor.css.scss
  app/helpers/renderers/csv_differ.rb
  app/javascript/packs/exercise.js
  app/javascript/packs/pythia_submission.js
  app/javascript/packs/series_overview.js
  app/models/api_token.rb
  app/views/pages/_description.en.html.erb
  app/views/users/_token_explanation.nl.html.erb
  config/locales/devise.nl.yml
  config/locales/views/course_members/nl.yml
  config/locales/views/courses/nl.yml
  config/locales/views/defaults/en.yml
  config/locales/views/defaults/nl.yml
  config/locales/views/pages/en.yml
  config/locales/views/pages/nl.yml
  config/locales/views/series/nl.yml
  public/javascripts/translations.js
Labels: bug
