Repository dodona-edu/dodona, pull requests merged in 2021-03, with the labels that each got.

#2522 Add UAntwerpen to sign in page
  app/assets/images/idp/ua.png
  app/views/auth/sign_in.html.erb
Labels: feature

#2526 Fix activity completion fields not being scoped to series (when available)
  app/views/activities/_activity.json.jbuilder
  test/controllers/activities_controller_test.rb
Labels: bug fix

#2527 Remove foreman entirely
  Procfile.dev
  bin/server
Labels: chore

#2541 Denormalize course_id into annotations
  app/models/activity.rb
  app/models/annotation.rb
  app/models/content_page.rb
  app/models/course.rb
  app/models/exercise.rb
  app/models/programming_language.rb
  app/models/provider.rb
  app/models/provider/g_suite.rb
  app/models/provider/lti.rb
  app/models/provider/office365.rb
  app/models/provider/saml.rb
  app/models/provider/smartschool.rb
  app/models/question.rb
  app/models/series.rb
  db/migrate/20210308102217_add_index_to_annotation.rb
  db/schema.rb
  test/controllers/annotations_controller_test.rb
  test/factories/annotations.rb
  test/factories/content_pages.rb
  test/factories/courses.rb
  test/factories/exercises.rb
  test/factories/programming_languages.rb
  test/factories/providers.rb
  test/factories/series.rb
  test/models/activity_test.rb
  test/models/annotation_test.rb
  test/models/course_test.rb
  test/models/exercise_test.rb
  test/models/provider_test.rb
  test/models/series_test.rb
  test/system/annotations_test.rb
Labels: bug fix

#2543 Fix English translation on question page
  config/locales/views/annotations/en.yml
Labels: bug fix

#2546 Fix n+1 loading evaluations for series on course show
  app/controllers/courses_controller.rb
Labels: bug fix

#2504 Improvements to institution management
  app/assets/stylesheets/models.css.less
  app/assets/stylesheets/models/institutions.css.less
  app/controllers/auth/authentication_controller.rb
  app/controllers/auth/omniauth_callbacks_controller.rb
  app/controllers/institutions_controller.rb
  app/models/institution.rb
  app/models/provider.rb
  app/models/provider/g_suite.rb
  app/models/provider/lti.rb
  app/models/provider/office365.rb
  app/models/provider/saml.rb
  app/models/provider/smartschool.rb
  app/views/institutions/_institution_table.html.erb
  app/views/institutions/index.html.erb
  app/views/institutions/index.js.erb
  app/views/institutions/show.html.erb
  config/locales/views/institutions/en.yml
  config/locales/views/institutions/nl.yml
  db/migrate/20210223200809_add_generated_name_to_institutions.rb
  db/schema.rb
  test/controllers/institution_controller_test.rb
  test/factories/institutions.rb
  test/factories/providers.rb
  test/models/institution_test.rb
  test/models/provider_test.rb
Labels: feature

#2547 Add test server to our infrastructure
  .github/workflows/deploy.yml
  config/deploy/mestra.rb
  config/deploy/staging.rb
  config/environments/development.rb
  public/robots.development.txt
Labels: chore

#2563 Don't require credentials key on mestra
  config/deploy/mestra.rb
Labels: chore, no-release-notes

#2562 Reorganize github action workflows
  .github/workflows/lint.yml
  .github/workflows/ruby.yml
  .github/workflows/system-test.yml
  .github/workflows/test.yml
Labels: chore

#2577 Fix missing <li> in view feedback link on series
  app/views/series/_series.html.erb
Labels: bug fix

#2578 Don't queue cache clear when destroying series
  app/models/series.rb
  app/models/series_membership.rb
  test/controllers/series_controller_test.rb
Labels: bug fix
