Repository dodona-edu/dodona, pull requests merged in 2021-11, with the labels that each got.

#3200 Capitalise first letter of getting started card action
  config/locales/views/pages/en.yml
  config/locales/views/pages/nl.yml
Labels: bug

#3127 Visualisation y-axis range toggle
  app/assets/javascripts/visualisations/cumulative_timeseries.ts
Labels: enhancement

#3205 Run CI actions on pull request instead of on push
  .github/workflows/lint.yml
  .github/workflows/test.yml
Labels: chore

#3203 Make email address on user profiles a mailto link
  app/views/course_members/_members_table.html.erb
  app/views/course_members/show.html.erb
  app/views/users/show.html.erb
  config/locales/views/course_members/en.yml
  config/locales/views/course_members/nl.yml
Labels: enhancement

#3217 Catch some bad API usage that should not result in internal error
  app/controllers/application_controller.rb
  test/controllers/submissions_controller_test.rb
Labels: bug

#3214 Rephrase message when there is no submission selected in an evaluation
  config/locales/views/feedbacks/en.yml
  config/locales/views/feedbacks/nl.yml
Labels: enhancement

#3230 Fix rendering of sets with nested structures in python tutor
  public/tutorviz/javascript/pytutor.js
Labels: bug
