Repository dodona-edu/dodona, pull requests merged in 2021-12, with the labels that each got.

#3223 Bump ruby to 2.7.5
  .ruby-version
  Gemfile
Labels: enhancement

#3207 Fix average dot of violin plot being placed outside of the graph when it is high
  app/assets/javascripts/i18n/translations.js
  app/assets/javascripts/visualisations/violin.ts
  config/locales/js/en.yml
  config/locales/js/nl.yml
Labels: bug

#3166 Finalize the heatmap in the series visualization
  app/assets/javascripts/i18n/translations.js
  app/assets/javascripts/visualisations/series_graph.ts
  app/assets/javascripts/visualisations/timeseries.ts
  app/models/submission.rb
  app/views/series/_series.html.erb
  config/locales/defaults/en.yml
  config/locales/defaults/nl.yml
  config/locales/js/en.yml
  config/locales/js/nl.yml
  test/javascript/visualisations.test.ts
  test/models/submission_test.rb
Labels: feature

#3243 Make sure seeded courses can use seeded activities
  Gemfile.lock
  db/seeds.rb
Labels: chore
