Repository dodona-edu/dodona, pull requests merged in 2021-04, with the labels that each got.

#2584 Don't deploy on review requested
  .github/workflows/deploy.yml
Labels: chore

#2591 Handle Unicode URLs in Smartschool name extraction
  test/factories/institutions.rb
Labels: bug fix

#2592 Take dark mode into account for list items
  app/assets/stylesheets/bootstrap_overrides.css.less
Labels: bug fix

#2594 Add docker configuration
  .dockerignore
  .github/workflows/publish.yml
  Dockerfile
  docker-compose.yml
  docker-entrypoint.sh
Labels: chore

#2606 Enable dependabot for Github Actions
  .github/dependabot.yml
Labels: chore

#2615 Never allow annotations on submissions outside a course
  app/policies/annotation_policy.rb
  test/controllers/annotations_controller_test.rb
Labels: bug

#2616 Use "bug" instead of "bug fix" in release drafter
  .github/release-drafter.yml
Labels: chore, no-release-notes

#2617 Uncomplete feedback if submission is changed
  app/models/feedback.rb
  test/models/feedback_test.rb
Labels: bug

#2618 Clean package.json file
  app/assets/javascripts/auto_reload.ts
  app/assets/javascripts/code_listing/code_listing.ts
  app/assets/javascripts/code_listing/question_annotation.ts
  app/assets/javascripts/code_listing/user_annotation.ts
  app/assets/javascripts/lti.ts
  app/assets/javascripts/question_table.ts
  jest.config.js
  package.json
  yarn.lock
Labels: chore, no-release-notes

#2620 Disable spring in github actions
  .github/workflows/test.yml
Labels: chore, no-release-notes

#2619 Make calculating recent exercises deterministic
  app/models/user.rb
  test/models/user_test.rb
Labels: bug

#2621 Make activities in hidden series inaccessible to non-members
  app/models/activity.rb
  app/models/course.rb
  test/controllers/submissions_controller_test.rb
  test/models/exercise_test.rb
Labels: bug

#2622 Add `.html` to some filenames that should have them
  app/views/activities/_content_page_read_button.html.erb
  app/views/activities/_series_activities_table.html.erb
Labels: chore

#2623 Fix more caching issues
  .rubocop.yml
  app/models/series.rb
  app/models/series_membership.rb
  test/controllers/series_controller_test.rb
  test/models/series_test.rb
Labels: bug

#2624 Change dependabot labels key name
  .github/dependabot.yml
Labels: chore, no-release-notes

#2627 Add retry mechanism to docker start
  app/runners/submission_runner.rb
  test/runners/submission_runner_test.rb
Labels: bug

#2628 Reduce database seed time to about 45 seconds
  db/seeds.rb
Labels: chore, no-release-notes

#2632 Make sure cache is invalidated when series has deadline
  app/models/series.rb
  test/models/series_test.rb
Labels: bug, high priority

#2635 Make sure any leftover containers are removed before retrying execution
  app/runners/submission_runner.rb
  test/runners/submission_runner_test.rb
Labels: bug

#2636 Clone exercise on conversion to content page
  app/models/activity.rb
  app/models/repository.rb
  test/models/repository_test.rb
Labels: bug

#2637 Add recaptcha.net to frame_src on contact page
  app/controllers/pages_controller.rb
Labels: bug

#2643 Don't activate drawer if it isn't there
  app/assets/javascripts/drawer.ts
Labels: bug

#2644 Lower the number of workers on mestra
  config/deploy/mestra.rb
Labels: chore

#2639 Add a "support us" page
  .github/FUNDING.yml
  app/assets/stylesheets/pages/home.css.less
  app/controllers/pages_controller.rb
  app/views/layouts/_footer.html.erb
  app/views/pages/_about.html.erb
  app/views/pages/_description.en.html.erb
  app/views/pages/_description.nl.html.erb
  app/views/pages/_metrics.html.erb
  app/views/pages/_team.en.html.erb
  app/views/pages/_team.nl.html.erb
  app/views/pages/support.html.erb
  config/locales/views/defaults/en.yml
  config/locales/views/defaults/nl.yml
  config/locales/views/pages/en.yml
  config/locales/views/pages/nl.yml
  config/routes.rb
  test/controllers/pages_controller_test.rb
Labels: feature

#2646 Tweak Support Us url
  .github/FUNDING.yml
  app/views/layouts/_footer.html.erb
  app/views/pages/_team.en.html.erb
  app/views/pages/_team.nl.html.erb
  config/routes.rb
  test/controllers/pages_controller_test.rb
Labels: no-release-notes

#2640 Create request system for teacher rights
  app/assets/stylesheets/base.css.less
  app/controllers/rights_requests_controller.rb
  app/helpers/rights_requests_helper.rb
  app/helpers/users_helper.rb
  app/mailers/rights_request_mailer.rb
  app/models/rights_request.rb
  app/models/user.rb
  app/policies/rights_request_policy.rb
  app/views/layouts/_drawer.html.erb
  app/views/pages/contact.html.erb
  app/views/rights_request_mailer/approved.en.html.erb
  app/views/rights_request_mailer/approved.en.text.erb
  app/views/rights_request_mailer/approved.nl.html.erb
  app/views/rights_request_mailer/approved.nl.text.erb
  app/views/rights_request_mailer/new_request.text.erb
  app/views/rights_request_mailer/rejected.en.html.erb
  app/views/rights_request_mailer/rejected.en.text.erb
  app/views/rights_request_mailer/rejected.nl.html.erb
  app/views/rights_request_mailer/rejected.nl.text.erb
  app/views/rights_requests/_form.html.erb
  app/views/rights_requests/_requests_table.html.erb
  app/views/rights_requests/approve.js.erb
  app/views/rights_requests/index.html.erb
  app/views/rights_requests/new.html.erb
  app/views/rights_requests/reject.js.erb
  app/views/users/_form.html.erb
  config/environments/development.rb
  config/environments/production.rb
  config/environments/test.rb
  config/locales/models/en.yml
  config/locales/models/nl.yml
  config/locales/views/defaults/en.yml
  config/locales/views/defaults/nl.yml
  config/locales/views/pages/en.yml
  config/locales/views/pages/nl.yml
  config/locales/views/rights_request_mailer/en.yml
  config/locales/views/rights_request_mailer/nl.yml
  config/locales/views/rights_requests/en.yml
  config/locales/views/rights_requests/nl.yml
  config/locales/views/users/en.yml
  config/locales/views/users/nl.yml
  config/routes.rb
  db/migrate/20210416085755_create_rights_requests.rb
  db/schema.rb
  test/controllers/rights_requests_controller_test.rb
  test/factories/rights_requests.rb
  test/models/rights_request_test.rb
Labels: feature

#2648 Small fixes for support us page
  app/views/pages/_metrics.html.erb
  config/locales/views/pages/nl.yml
Labels: bug

#2661 Fix typos on support us page
  config/locales/views/pages/en.yml
Labels: bug

#2662 Fix documentation links
  README.md
  app/views/activities/info.html.erb
  app/views/layouts/_drawer.html.erb
  app/views/layouts/_footer.html.erb
  app/views/pages/_description.en.html.erb
  app/views/pages/_description.nl.html.erb
  app/views/pages/privacy.en.html.erb
  app/views/pages/privacy.nl.html.erb
Labels: bug

#2664 Update sandbox urls
  config/environments/production.rb
  config/environments/staging.rb
Labels: chore

#2634 Let mestra deploy itself
  .github/workflows/deploy.yml
Labels: chore

#2670 Don't add IP and UA to contact form emails
  app/models/contact_form.rb
Labels: bug

#2671 Make sure series#new 404s when course does not exist
  Gemfile
  Gemfile.lock
  app/controllers/series_controller.rb
  app/helpers/activity_helper.rb
  test/controllers/series_controller_test.rb
Labels: bug

#2672 Fix CSP error for JS exercises
  app/controllers/activities_controller.rb
Labels: bug
