Repository dodona-edu/dodona, pull requests merged in 2021-05, with the labels that each got.

#2673 Use the sandbox domain for the tutor iframe
  app/assets/javascripts/pythia_submission.js
  app/controllers/feedbacks_controller.rb
  app/controllers/submissions_controller.rb
  app/javascript/packs/pythia_submission.js
  app/javascript/packs/series_overview.js
  app/views/layouts/application.html.erb
  public/tutorviz/javascript/iframe.min.js
  public/tutorviz/tutorviz.html
Labels: security

#2688 Remove daemons dependency
  Gemfile
  Gemfile.lock
Labels: chore

#2677 Add additional deploy scripts
  .github/workflows/deploy-images.yml
  .github/workflows/deploy-mestra.yml
  .github/workflows/deploy-naos.yml
  .github/workflows/restart-workers.yml
Labels: chore

#2689 Tweak deploy scripts
  .github/workflows/deploy-mestra.yml
  .github/workflows/deploy-naos.yml
Labels: chore

#2693 Update rails
  Gemfile.lock
Labels: dependencies

#2722 Raise ConfigParseError if config.json does not contain a JSON object
  app/models/repository.rb
  app/models/transient/config_parse_error.rb
  test/models/repository_test.rb
Labels: bug

#2723 Fix use of outdated var name in environment-specific config file
  config/environments/development.rb
  config/environments/production.rb
  config/environments/staging.rb
  config/environments/test.rb
Labels: bug

#2718 Add custom scrollspy implementation
  app/assets/javascripts/course.js
  app/assets/javascripts/scrollspy.ts
  app/javascript/packs/application.js
  app/javascript/packs/frame.js
Labels: no-release-notes

#2738 Add polyfills and update browserlist
  .browserslistrc
  app/javascript/packs/application.js
  app/javascript/packs/frame.js
  babel.config.js
  browserlist
Labels: bug

#2740 Scope exercise path in evaluation overview
  app/views/evaluations/overview.html.erb
Labels: bug

#2742 Use a random suffix for container names to avoid even more conflicts
  app/runners/submission_runner.rb
Labels: bug

#2744 Fix some grading bugs
  app/views/feedbacks/_feedback_actions.html.erb
  app/views/feedbacks/_score_actions.html.erb
  app/views/feedbacks/_user_feedback_row.html.erb
  app/views/scores/show.js.erb
  config/locales/views/feedbacks/en.yml
  config/locales/views/feedbacks/nl.yml
Labels: bug

#2747 Make sure $development variable is defined in prod as well
  app/assets/stylesheets/application-dark.css.scss.erb
  app/assets/stylesheets/application.css.scss.erb
Labels: bug

#2746 Handle score creating conflicts
  app/assets/javascripts/feedback/actions.ts
  app/controllers/feedbacks_controller.rb
  app/controllers/scores_controller.rb
  app/models/score.rb
  test/controllers/feedbacks_controller_test.rb
  test/controllers/scores_controller_test.rb
  test/models/score_test.rb
Labels: bug

#2755 Style issues fixes
  app/assets/stylesheets/base.css.scss
  app/assets/stylesheets/bootstrap_style_overrides.css.scss
  app/assets/stylesheets/models/course.css.scss
  app/helpers/renderers/feedback_table_renderer.rb
Labels: bug

#2757 Fix python tutor not showing up
  app/assets/javascripts/pythia_submission.js
  app/assets/stylesheets/components/modal.css.scss
  app/assets/stylesheets/components/tutor.css.scss
  app/helpers/renderers/pythia_renderer.rb
Labels: bug

#2741 Update the readme
  README.md
Labels: chore

#2758 Make sure we never generate an id starting with - in the feedback table
  app/helpers/renderers/feedback_table_renderer.rb
Labels: bug, high priority

#2774 Don't enable the scrollspy if there is no side nav
  app/assets/javascripts/course.js
Labels: bug
