Repository dodona-edu/dodona, pull requests merged in 2021-06, with the labels that each got.

#2793 Fix about page width on medium screens
  app/assets/stylesheets/pages/home.css.scss
  app/views/pages/_about.html.erb
  app/views/pages/support.html.erb
Labels: bug

#2796 Fix filtering submissions by user label
  app/controllers/submissions_controller.rb
Labels: bug

#2794 Check for jquery usage with eslint
  .eslintrc
  app/assets/javascripts/course.js
  app/assets/javascripts/exercise.js
  app/assets/javascripts/export.js
  app/assets/javascripts/favorite_course_buttons.js
  app/assets/javascripts/index.js
  app/assets/javascripts/pythia_submission.js
  app/assets/javascripts/repository.js
  app/assets/javascripts/scoresheet.js
  app/assets/javascripts/series.js
  app/assets/javascripts/submission.js
  app/assets/javascripts/util.js
  package.json
  yarn.lock
Labels: chore

#2795 Fix code tab not automatically loading during feedback
  app/views/feedbacks/show.html.erb
Labels: bug

#2798 Public beta of grading
  app/controllers/score_items_controller.rb
  app/policies/score_item_policy.rb
  app/views/evaluations/add_users.html.erb
  app/views/evaluations/show.html.erb
  app/views/score_items/index.html.erb
  app/views/score_items/new.html.erb
  config/locales/views/score_items/en.yml
  config/locales/views/score_items/nl.yml
  test/controllers/score_items_controller_test.rb
  test/system/score_items_test.rb
Labels: feature

#2810 Make sure allowed courses renders
  app/views/repositories/courses.html.erb
  test/controllers/repositories_controller_test.rb
Labels: bug

#2812 Clear data dirs when deploying to mestra
  config/deploy/mestra.rb
Labels: chore

#2829 Allow byte ranges of media to be requested
  app/controllers/activities_controller.rb
  app/controllers/repositories_controller.rb
  test/controllers/activities_controller_test.rb
  test/controllers/repositories_controller_test.rb
Labels: bug

#2836 Fix error on loading courses page when not signed in
  app/controllers/courses_controller.rb
Labels: bug

#2837 Fix missing select arrow on score item copy modal
  app/views/score_items/_copy.html.erb
Labels: bug

#2839 Create issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: chore

#2840 Add contact links to the create issue page
  .github/ISSUE_TEMPLATE/config.yml
Labels: chore

#2841 Move docker files to separate repo
  .dockerignore
  .github/workflows/publish.yml
  Dockerfile
  docker-compose.yml
  docker-entrypoint.sh
Labels: chore

#2844 html-encode the text of machine annotations
  app/assets/javascripts/code_listing/machine_annotation.ts
  test/javascript/code_listing.test.ts
Labels: bug

#2846 Tweak annotations style
  app/assets/javascripts/code_listing/annotation.ts
  app/assets/stylesheets/components/code_listing.css.scss
Labels: bug

#2847 Tweak teacher rights request flow
  app/policies/rights_request_policy.rb
  app/views/pages/contact.html.erb
  app/views/rights_requests/new.html.erb
  config/locales/views/rights_requests/en.yml
  config/locales/views/rights_requests/nl.yml
Labels: bug

#2843 Upgrade checkboxes and radios to bootstrap 5
  app/assets/stylesheets/bootstrap_style_overrides.css.scss
  app/assets/stylesheets/bootstrap_variable_overrides.css.scss
  app/assets/stylesheets/components.css.scss
  app/assets/stylesheets/components/form.css.scss
  app/assets/stylesheets/theme/theme-light.css.scss
  app/views/courses/_copy_courses_table.html.erb
  app/views/courses/_copy_option.html.erb
  app/views/courses/_form.html.erb
  app/views/courses/questions.html.erb
  app/views/exports/_option.html.erb
  app/views/exports/_selection_table.html.erb
  app/views/exports/download_submissions.html.erb
  app/views/feedbacks/_feedback_actions.html.erb
  app/views/layouts/_navbar.html.erb
  app/views/layouts/application.html.erb
  app/views/score_items/_exercise.html.erb
  app/views/score_items/_form.html.erb
  app/views/series/_form.html.erb
Labels: feature

#2849 Add featured courses
  app/controllers/courses_controller.rb
  app/models/course.rb
  app/policies/course_policy.rb
  app/views/courses/_copy_courses_table.html.erb
  app/views/courses/_courses_table.html.erb
  app/views/courses/_form.html.erb
  app/views/courses/index.html.erb
  app/views/courses/show.html.erb
  config/locales/models/en.yml
  config/locales/models/nl.yml
  config/locales/views/courses/en.yml
  config/locales/views/courses/nl.yml
  db/migrate/20210612104516_add_featured_to_courses.rb
  db/schema.rb
  db/seeds.rb
  test/controllers/courses_controller_test.rb
  test/factories/courses.rb
  test/models/course_test.rb
  test/system/courses_test.rb
Labels: feature

#2857 Fix failing tests due to codecov
  test/test_helper.rb
Labels: chore

#2858 Fix export scoping
  app/controllers/series_controller.rb
  app/helpers/export_helper.rb
  app/models/export.rb
  test/controllers/exports_controller_test.rb
Labels: bug, high priority, security

#2859 Restore stickyness of feedback metadata
  app/assets/stylesheets/components/evaluations.css.scss
Labels: bug

#2863 Add links to markdown documentation where appropriate
  app/assets/javascripts/i18n/translations.js
  app/views/courses/_form.html.erb
  app/views/score_items/_form.html.erb
  app/views/series/_form.html.erb
  config/locales/js/en.yml
  config/locales/js/nl.yml
  config/locales/views/courses/en.yml
  config/locales/views/courses/nl.yml
  config/locales/views/score_items/en.yml
  config/locales/views/score_items/nl.yml
  config/locales/views/series/en.yml
  config/locales/views/series/nl.yml
Labels: feature

#2864 Make sure tabs in feedback table always start with a letter
  app/helpers/renderers/feedback_table_renderer.rb
Labels: bug

#2870 Hide messages from search engine snippets
  app/views/layouts/_main_container.html.erb
Labels: enhancement

#2871 Add courses link to signed out navbar
  app/views/layouts/_breadcrumbs.html.erb
  config/locales/views/courses/en.yml
  config/locales/views/courses/nl.yml
  config/locales/views/defaults/en.yml
  config/locales/views/defaults/nl.yml
Labels: enhancement

#2880 Use built-in concurrency checks for deployments
  .github/workflows/deploy-images.yml
  .github/workflows/deploy-mestra.yml
  .github/workflows/deploy-naos.yml
  .github/workflows/restart-workers.yml
Labels: chore

#2883 Fix some dutch strings in the english translation files for grading
  config/locales/views/score_items/en.yml
Labels: bug

#2865 Debounce grade clicks
  app/assets/javascripts/feedback/score.ts
  test/system/feedbacks_test.rb
Labels: bug

#2885 Create codeowners file
  .github/CODEOWNERS
Labels: chore

#2884 Make sign-in when the provider doesn't match clearer
  app/controllers/auth/omniauth_callbacks_controller.rb
  app/views/layouts/_main_container.html.erb
  config/locales/devise.en.yml
  config/locales/devise.nl.yml
Labels: bug

#2887 Increase drawer width
  app/assets/stylesheets/layout/drawer.css.scss
  app/views/layouts/_drawer.html.erb
Labels: enhancement

#2889 Show extra emoji feedback after submitting
  app/assets/javascripts/exercise.js
  app/assets/stylesheets/components/btn.css.scss
Labels: feature

#2776 Rework how grading results are shown to students
  app/assets/stylesheets/components/evaluations.css.scss
  app/assets/stylesheets/models/score_items.css.scss
  app/policies/score_item_policy.rb
  app/views/evaluations/overview.html.erb
  app/views/feedbacks/_score_link.html.erb
  config/locales/views/evaluations/en.yml
  config/locales/views/evaluations/nl.yml
  test/policies/score_item_policy_test.rb
  test/policies/score_policy_test.rb
Labels: enhancement

#2892 Add structured data
  app/views/courses/show.html.erb
  app/views/pages/_about.html.erb
Labels: enhancement
