Repository dodona-edu/dodona, pull requests merged in 2022-05, with the labels that each got.

#3577 Add Safari-specific CSP headers to allow web worker to be loaded
  app/controllers/activities_controller.rb
Labels: bug

#3498 Refactor index.js to webcomponents
  Gemfile
  Gemfile.lock
  app/assets/javascripts/components/dropdown_filter.ts
  app/assets/javascripts/components/filter_button.ts
  app/assets/javascripts/components/filter_collection_element.ts
  app/assets/javascripts/components/search_actions.ts
  app/assets/javascripts/components/search_field.ts
  app/assets/javascripts/components/search_token.ts
  app/assets/javascripts/components/shadowless_lit_element.ts
  app/assets/javascripts/course.js
  app/assets/javascripts/exercise.js
  app/assets/javascripts/index.js
  app/assets/javascripts/search.ts
  app/assets/javascripts/series.js
  app/assets/javascripts/types/index.d.ts
  app/assets/javascripts/util.js
  app/assets/stylesheets/components.css.scss
  app/assets/stylesheets/components/dropdown.css.scss
  app/assets/stylesheets/components/search_field.css.scss
  app/assets/stylesheets/components/tokenfield.css.scss
  app/assets/stylesheets/material_icons.css.scss
  app/helpers/application_helper.rb
  app/javascript/packs/activities.js
  app/javascript/packs/application_pack.js
  app/javascript/packs/exercise.js
  app/javascript/packs/index.js
  app/javascript/packs/questions.js
  app/javascript/packs/search.js
  app/views/activities/_activities_table.html.erb
  app/views/activities/_labels.html.erb
  app/views/activities/_series_activities_add_table.html.erb
  app/views/activity_read_states/_read_states_table.html.erb
  app/views/annotations/_questions_table.html.erb
  app/views/course_members/index.html.erb
  app/views/courses/_reload_users.js.erb
  app/views/courses/index.html.erb
  app/views/evaluations/new.html.erb
  app/views/evaluations/refresh_users.js.erb
  app/views/layouts/_searchbar.html.erb
  app/views/repositories/show.html.erb
  app/views/submissions/_submission.html.erb
  app/views/submissions/_submissions_table.html.erb
  babel.config.js
  config/environments/production.rb
  config/environments/staging.rb
  test/system/courses_test.rb
  tsconfig.json
Labels: feature

#3591 Remove first-input-delay package
  app/assets/javascripts/application_old.js
  package.json
  yarn.lock
Labels: chore

#3592 Use send instead of play as hand in icon
  app/assets/javascripts/exercise.js
  app/assets/stylesheets/components/card.css.scss
  app/assets/stylesheets/material_icons.css.scss
  app/views/activities/show.html.erb
  config/locales/views/activities/en.yml
  config/locales/views/activities/nl.yml
  public/javascripts/translations.js
Labels: enhancement

#3580 Add sort buttons to submissions tables within the context of a course
  app/assets/javascripts/components/sort_button.ts
  app/controllers/submissions_controller.rb
  app/javascript/packs/search.js
  app/models/submission.rb
  app/views/submissions/_submissions_table.html.erb
  test/models/submission_test.rb
Labels: feature

#3595 Fix changing the submission of a feedback record with a lot of scores
  app/models/feedback.rb
  app/models/score.rb
  test/controllers/feedbacks_controller_test.rb
Labels: bug

#3596 Make sure the search javascript is correctly loaded on the new evaluation page
  app/views/evaluations/new.html.erb
Labels: bug

#3622 Prevent closing Papyros when pressing Escape
  app/views/activities/_coding_scratchpad.html.erb
Labels: bug

#3597 Add sort buttons to scoresheets
  app/assets/javascripts/components/sort_button.ts
  app/controllers/courses_controller.rb
  app/controllers/series_controller.rb
  app/controllers/submissions_controller.rb
  app/models/course.rb
  app/models/series.rb
  app/models/user.rb
  app/views/courses/_scoresheet_table.html.erb
  app/views/series/_scoresheet_table.html.erb
  app/views/submissions/_submissions_table.html.erb
  test/models/user_test.rb
Labels: feature

#3636 Hide progress on series submission export for students when series progress is set to be hidden
  app/policies/series_policy.rb
  app/views/activities/_series_activities_table.html.erb
  app/views/exports/_selection_table.html.erb
Labels: bug

#3637 Only show submissions without course in the submission history of a submission without a course
  app/controllers/submissions_controller.rb
  app/models/submission.rb
Labels: bug

#3533 Create dismissable announcements for all dodona users
  app/assets/javascripts/components/datalist_input.ts
  app/assets/javascripts/i18n/translations.js
  app/assets/javascripts/series.js
  app/assets/javascripts/util.js
  app/assets/stylesheets/models.css.scss
  app/assets/stylesheets/models/announcements.css.scss
  app/controllers/announcements_controller.rb
  app/controllers/application_controller.rb
  app/helpers/application_helper.rb
  app/javascript/packs/announcement.js
  app/models/announcement.rb
  app/models/announcement_view.rb
  app/models/provider/surf.rb
  app/policies/announcement_policy.rb
  app/views/announcements/_announcement.html.erb
  app/views/announcements/_announcement_table.html.erb
  app/views/announcements/_form.html.erb
  app/views/announcements/edit.html.erb
  app/views/announcements/index.html.erb
  app/views/announcements/mark_as_read.js.erb
  app/views/announcements/new.html.erb
  app/views/layouts/_drawer.html.erb
  app/views/layouts/_main_container.html.erb
  config/locales/defaults/en.yml
  config/locales/defaults/nl.yml
  config/locales/models/en.yml
  config/locales/models/nl.yml
  config/locales/views/announcements/en.yml
  config/locales/views/announcements/nl.yml
  config/locales/views/defaults/en.yml
  config/locales/views/defaults/nl.yml
  config/routes.rb
  db/migrate/20220413130927_create_announcement_tables.rb
  db/schema.rb
  test/controllers/announcement_controller_test.rb
  test/factories/announcement.rb
  test/models/announcement_test.rb
Labels: feature

#3648 Fix sorting by activity read states for series and course scoresheet
  app/controllers/series_controller.rb
  app/models/user.rb
  test/models/user_test.rb
Labels: bug

#3642 Add summary column to series scoresheets
  app/assets/stylesheets/components/table.css.scss
  app/controllers/series_controller.rb
  app/models/user.rb
  app/views/series/_scoresheet_table.html.erb
  app/views/series/scoresheet.html.erb
  app/views/series/scoresheet.js.erb
  config/locales/views/series/en.yml
  config/locales/views/series/nl.yml
  test/models/user_test.rb
Labels: feature

#3669 Fix CSV differ crashing on CSV with a newline in a field on the first row
  app/helpers/renderers/csv_differ.rb
  test/helpers/renderers/diff_csv_test.rb
Labels: bug
