Repository dodona-edu/dodona, pull requests merged in 2022-01, with the labels that each got.

#3274 Rights request: Show correct error message when motivation is not filled out
  app/views/rights_requests/_form.html.erb
  app/views/rights_requests/new.html.erb
Labels: bug

#3276 Fix babel 'loose' warning
  babel.config.js
Labels: chore

#3273 Update readme to improve setup script for new users
  README.md
Labels: chore

#3222 Add dynamic binning to the cumulative graph
  app/assets/javascripts/i18n/translations.js
  app/assets/javascripts/visualisations/cumulative_timeseries.ts
  app/assets/javascripts/visualisations/series_graph.ts
  app/assets/javascripts/visualisations/timeseries.ts
  app/models/submission.rb
  config/locales/js/en.yml
  config/locales/js/nl.yml
  test/javascript/visualisations.test.ts
  test/models/submission_test.rb
Labels: enhancement

#3285 Fix issue in right requests policy method instead of previous workaround
  app/policies/rights_request_policy.rb
  app/views/rights_requests/new.html.erb
Labels: bug

#3287 Mark score item as busy before delay, to let page wait until delay finish
  app/assets/javascripts/feedback/score.ts
Labels: bug

#3278 Add external URL to machine annotations
  app/assets/javascripts/code_listing/annotation.ts
  app/assets/javascripts/code_listing/machine_annotation.ts
  app/assets/javascripts/i18n/translations.js
  app/helpers/renderers/pythia_renderer.rb
  app/runners/result_constructor.rb
  config/locales/js/en.yml
  config/locales/js/nl.yml
  public/schemas/judge_output.json
  public/schemas/partial_output.json
  test/runners/result_constructor_test.rb
Labels: feature

#3288 Add visual confirmation that a score has been saved when grading
  app/assets/javascripts/feedback/score.ts
  app/assets/stylesheets/base.css.scss
  app/assets/stylesheets/components/evaluations.css.scss
  app/views/feedbacks/_score_actions.html.erb
Labels: feature

#3290 Fix the amount of pixels of total score input on the grading page
  app/assets/stylesheets/components/evaluations.css.scss
Labels: bug

#3291 Fix image captions for exercises
  app/assets/javascripts/exercise.js
Labels: bug

#3300 add line blur on hover
  app/assets/javascripts/visualisations/cumulative_timeseries.ts
Labels: enhancement

#3313 Fix typo
  config/locales/views/exports/nl.yml
Labels: no-release-notes

#3312 Give same height to all elements in status table
  app/assets/stylesheets/components/table.css.scss
Labels: bug

#3314 Move minitest from development to test gem
  Gemfile
Labels: bug

#3315 Automate annotations
  app/models/institution.rb
  lib/tasks/auto_annotate_models.rake
  test/factories/institutions.rb
  test/fixtures/institutions.yml
  test/models/institution_test.rb
Labels: chore

#3317 Fix pagination of the copy course list
  app/controllers/courses_controller.rb
Labels: bug

#3204 Allow users to set time bounds of series visualisations
  app/assets/javascripts/i18n/translations.js
  app/assets/javascripts/series.js
  app/assets/javascripts/visualisations/cumulative_timeseries.ts
  app/assets/javascripts/visualisations/series_graph.ts
  app/assets/javascripts/visualisations/timeseries.ts
  app/assets/javascripts/visualisations/violin.ts
  app/assets/stylesheets/components/visualisations.css.scss
  app/controllers/statistics_controller.rb
  app/models/submission.rb
  app/views/series/_series.html.erb
  config/locales/defaults/en.yml
  config/locales/defaults/nl.yml
  config/locales/views/series/en.yml
  config/locales/views/series/nl.yml
  test/javascript/visualisations.test.ts
Labels: feature

#3295 Make cloning git repository asynchronous
  app/controllers/repositories_controller.rb
  app/models/concerns/gitable.rb
  app/models/judge.rb
  app/models/repository.rb
  app/views/judges/show.html.erb
  app/views/repositories/_form.html.erb
  app/views/repositories/show.html.erb
  config/deploy/production.rb
  config/environments/test.rb
  config/locales/views/judges/en.yml
  config/locales/views/judges/nl.yml
  config/locales/views/repositories/en.yml
  config/locales/views/repositories/nl.yml
  db/migrate/20220120102649_add_clone_status_to_judges.rb
  db/migrate/20220120102810_add_clone_status_to_repositories.rb
  db/schema.rb
  db/seeds.rb
  test/factories/judges.rb
  test/factories/repositories.rb
  test/fixtures/judges.yml
  test/models/judge_test.rb
  test/models/repository_test.rb
  test/testhelpers/stub_helper.rb
Labels: enhancement

#3328 Store last seen and last sign in in the database
  app/controllers/application_controller.rb
  app/controllers/users_controller.rb
  app/models/user.rb
  db/migrate/20220124145914_add_seen_at_to_users.rb
  db/migrate/20220124145930_add_sign_in_at_to_users.rb
  db/schema.rb
  test/factories/users.rb
  test/fixtures/users.yml
  test/models/user_test.rb
Labels: feature
