Repository dodona-edu/dodona, pull requests merged in 2022-03, with the labels that each got.

#3437 End series visualizations on series deadline
  app/assets/javascripts/visualisations/cumulative_timeseries.ts
  app/assets/javascripts/visualisations/timeseries.ts
  app/controllers/statistics_controller.rb
Labels: bug

#3455 Remove unused dependency on @rails/webpacker
  package.json
  yarn.lock
Labels: dependencies

#3483 Display special characters in evaluation description
  app/views/feedbacks/_feedback_actions.html.erb
Labels: bug

#3470 Add vertical submission history to submission detail view
  app/assets/javascripts/submission.js
  app/assets/stylesheets/components/card.css.scss
  app/assets/stylesheets/models/submissions.css.scss
  app/controllers/submissions_controller.rb
  app/javascript/packs/submission.js
  app/views/submissions/_description.html.erb
  config/locales/views/submissions/en.yml
  config/locales/views/submissions/nl.yml
Labels: feature

#3485 Number submissions by user, exercise and course
  app/models/submission.rb
  app/views/submissions/_description.html.erb
  app/views/submissions/_submission.html.erb
  app/views/submissions/_submissions_table.html.erb
  config/locales/views/submissions/en.yml
  config/locales/views/submissions/nl.yml
  db/migrate/20220317120756_add_number_to_submissions.rb
  db/schema.rb
  test/factories/submissions.rb
  test/models/submission_test.rb
Labels: feature
