Repository dodona-edu/dodona, pull requests merged in 2022-08, with the labels that each got.

#3805 Fix the institution search bar on the sign in page
  app/views/auth/sign_in.html.erb
  db/seeds.rb
Labels: bug

#3792 Make long dropdowns searchable and scrollable
  app/assets/javascripts/components/dropdown_filter.ts
  app/assets/javascripts/i18n/translations.js
  app/assets/stylesheets/components/dropdown-filter.css.scss
  app/controllers/annotations_controller.rb
  app/views/activities/index.html.erb
  app/views/annotations/question_index.html.erb
  app/views/series/edit.html.erb
  app/views/users/index.html.erb
  config/locales/js/en.yml
  config/locales/js/nl.yml
Labels: feature

#3838 Remove json-jwt pin
  Gemfile
  Gemfile.lock
Labels: chore

#3848 Update github actions to node 16
  .github/workflows/lint.yml
  .github/workflows/test.yml
Labels: chore

#3839 Readme update for development setup
  README.md
Labels: chore

#3849 Provide the correct activity id for submissions on an activity page
  app/views/submissions/_submissions_table.html.erb
Labels: bug

#3807 Use default text buttons for user selection in the evaluation wizard
  app/assets/javascripts/evaluation.ts
  app/views/evaluations/_add_users.html.erb
Labels: bug

#3850 Add TypeScript type check
  .github/workflows/lint.yml
  README.md
  app/assets/javascripts/components/search_actions.ts
  app/assets/javascripts/evaluation.ts
  app/assets/javascripts/feedback/actions.ts
  app/assets/javascripts/institution.ts
  app/assets/javascripts/question_table.ts
  app/assets/javascripts/types/index.d.ts
  package.json
  tsconfig.json
  yarn.lock
Labels: chore, enhancement

#3854 Ignore errors triggered by bingbot
  config/environments/production.rb
Labels: bug

#3856 Disable ace editor search
  app/assets/javascripts/exercise.js
Labels: bug

#3851 Show an activity not found error for activities no longer present in a course
  app/controllers/activities_controller.rb
Labels: bug

#3853 Create bash script for releasing
  bin/release
Labels: chore

#3858 Only show that the activity is not present to course admins
  app/controllers/activities_controller.rb
Labels: bug

#3857 Fix the native browser back button when using pagination
  app/assets/javascripts/course.js
  app/assets/javascripts/search.ts
Labels: bug

#3860 Handle errors when Dodona has no push rights to exercise repo
  app/mailers/error_mailer.rb
  app/models/repository.rb
  app/models/transient/dodona_git_error.rb
  app/views/error_mailer/git_error.html.erb
  app/views/error_mailer/git_error.text.erb
  config/locales/views/error_mailer/en.yml
  config/locales/views/error_mailer/nl.yml
  config/locales/views/repositories/en.yml
  config/locales/views/repositories/nl.yml
  test/models/repository_test.rb
Labels: bug

#3874 Don't prefix dependabot commit messages
  .github/dependabot.yml
Labels: chore

#3875 Fix XSS in course copy
  app/assets/javascripts/course.js
Labels: bug

#3861 Fix institution create failed on staging
  app/controllers/auth/omniauth_callbacks_controller.rb
  app/models/institution.rb
Labels: bug

#3880 Merge announcement views when merging users
  app/models/user.rb
  test/models/user_test.rb
Labels: bug

#3879 Don't update search bar on page changes when the search bar does not use the page url
  app/assets/javascripts/search.ts
Labels: bug

#3752 Add a setting to courses to limit registration to institutional accounts
  app/controllers/courses_controller.rb
  app/helpers/courses_helper.rb
  app/models/activity.rb
  app/models/course.rb
  app/models/user.rb
  bin/server
  config/locales/models/en.yml
  config/locales/models/nl.yml
  config/locales/views/courses/en.yml
  config/locales/views/courses/nl.yml
  db/seeds.rb
  test/controllers/courses_controller_test.rb
  test/fixtures/courses.yml
Labels: feature

#3893 Change default dependency reviewer to Jorg
  .github/CODEOWNERS
Labels: chore

#3855 Update privacy declaration to also cover personal accounts
  app/views/pages/data.en.html.erb
  app/views/pages/data.nl.html.erb
  app/views/pages/privacy.en.html.erb
  app/views/pages/privacy.nl.html.erb
Labels: feature

#3806 Allow personal accounts
  app/controllers/auth/authentication_controller.rb
  app/controllers/auth/omniauth_callbacks_controller.rb
  app/models/identity.rb
  app/models/provider.rb
  app/models/provider/g_suite.rb
  app/models/provider/lti.rb
  app/models/provider/office365.rb
  app/models/provider/oidc.rb
  app/models/provider/saml.rb
  app/models/provider/smartschool.rb
  app/models/provider/surf.rb
  app/models/user.rb
  app/views/auth/sign_in.html.erb
  config/initializers/office365.rb
  config/locales/views/auth/en.yml
  config/locales/views/auth/nl.yml
  db/migrate/20220715082910_change_provider_institution_id.rb
  db/migrate/20220715111838_add_identifier_based_on_email_to_identity.rb
  db/migrate/20220818074900_prepare_for_personal_users.rb
  db/schema.rb
  db/seeds.rb
  test/controllers/auth/omniauth_callbacks_controller_test.rb
  test/factories/identities.rb
  test/factories/providers.rb
  test/models/identity_test.rb
  test/models/provider_test.rb
  test/models/user_test.rb
Labels: feature

#3859 Force new private users to accept the privacy policy before creating an account
  app/controllers/application_controller.rb
  app/controllers/auth/omniauth_callbacks_controller.rb
  app/views/auth/privacy_prompt.html.erb
  app/views/pages/home.html.erb
  config/locales/views/auth/en.yml
  config/locales/views/auth/nl.yml
  config/routes.rb
  test/controllers/auth/omniauth_callbacks_controller_test.rb
Labels: feature

#3892 Allow sign in using personal accounts
  app/controllers/application_controller.rb
  app/controllers/auth/authentication_controller.rb
  app/controllers/auth/omniauth_callbacks_controller.rb
  app/controllers/courses_controller.rb
  app/helpers/courses_helper.rb
  app/models/activity.rb
  app/models/course.rb
  app/models/identity.rb
  app/models/provider.rb
  app/models/provider/g_suite.rb
  app/models/provider/lti.rb
  app/models/provider/office365.rb
  app/models/provider/oidc.rb
  app/models/provider/saml.rb
  app/models/provider/smartschool.rb
  app/models/provider/surf.rb
  app/models/user.rb
  app/views/auth/_provider_button.html.erb
  app/views/auth/privacy_prompt.html.erb
  app/views/auth/redirect_to_known_provider.html.erb
  app/views/auth/sign_in.html.erb
  app/views/pages/data.en.html.erb
  app/views/pages/data.nl.html.erb
  app/views/pages/home.html.erb
  app/views/pages/privacy.en.html.erb
  app/views/pages/privacy.nl.html.erb
  bin/server
  config/initializers/office365.rb
  config/locales/models/en.yml
  config/locales/models/nl.yml
  config/locales/views/auth/en.yml
  config/locales/views/auth/nl.yml
  config/locales/views/courses/en.yml
  config/locales/views/courses/nl.yml
  config/routes.rb
  db/migrate/20220715082910_change_provider_institution_id.rb
  db/migrate/20220715111838_add_identifier_based_on_email_to_identity.rb
  db/migrate/20220818074900_prepare_for_personal_users.rb
  db/schema.rb
  db/seeds.rb
  test/controllers/auth/omniauth_callbacks_controller_test.rb
  test/controllers/courses_controller_test.rb
  test/factories/identities.rb
  test/factories/providers.rb
  test/fixtures/courses.yml
  test/models/identity_test.rb
  test/models/provider_test.rb
  test/models/user_test.rb
Labels: feature

#3899 Fix the wrapping of very long identifiers on the profile page
  app/assets/stylesheets/models/users.css.scss
  app/views/users/show.html.erb
  db/seeds.rb
Labels: bug

#3901 Give users a friendlier message about why they cannot register for a course
  app/helpers/courses_helper.rb
  app/views/courses/_not_a_member_card.html.erb
Labels: feature

#3903 Fix legacy office sign in
  app/controllers/auth/omniauth_callbacks_controller.rb
  test/controllers/auth/omniauth_callbacks_controller_test.rb
Labels: bug

#3902 Automatically filter on courses for which you can register when relevant
  app/controllers/courses_controller.rb
  app/models/course.rb
  app/views/courses/_courses_table.html.erb
  app/views/courses/index.html.erb
  app/views/pages/_getting_started_card.html.erb
  app/views/pages/home.html.erb
  config/locales/views/courses/en.yml
  config/locales/views/courses/nl.yml
  test/models/course_test.rb
Labels: feature

#3924 Fix readable_name error for Google Workspace accounts
  app/models/provider/g_suite.rb
  test/models/provider_test.rb
Labels: bug

#3881 Use local storage to save filter in edit series to add exercises
  app/assets/javascripts/search.ts
  app/views/layouts/_searchbar.html.erb
  app/views/series/edit.html.erb
Labels: feature

#3929 No more teal in token colors
  app/views/layouts/_searchbar.html.erb
Labels: enhancement

#3927 Fix shift in rows in evaluation overview table
  app/assets/stylesheets/components/table.css.scss
Labels: bug

#3862 Obscure reviewers name in feedback evaluation
  app/assets/javascripts/code_listing/user_annotation.ts
  app/assets/javascripts/i18n/translations.json
  app/policies/annotation_policy.rb
  app/views/annotations/_annotation.json.jbuilder
  config/locales/js/en.yml
  config/locales/js/nl.yml
  test/factories/annotations.rb
  test/policies/annotation_policy_test.rb
Labels: feature

#3896 Add references to manual
  app/assets/javascripts/code_listing/code_listing.ts
  app/assets/javascripts/i18n/translations.json
  app/views/courses/new.html.erb
  app/views/repositories/_form.html.erb
  app/views/repositories/show.html.erb
  config/locales/js/en.yml
  config/locales/js/nl.yml
  config/locales/views/courses/en.yml
  config/locales/views/courses/nl.yml
  config/locales/views/evaluations/en.yml
  config/locales/views/evaluations/nl.yml
  config/locales/views/repositories/en.yml
  config/locales/views/repositories/nl.yml
  config/locales/views/users/en.yml
  config/locales/views/users/nl.yml
Labels: feature

#3926 Improve buttons in choose submission screen for evaluation
  app/assets/stylesheets/components/btn.css.scss
  app/assets/stylesheets/components/table.css.scss
  app/views/feedbacks/_submissions_table.html.erb
  config/locales/views/submissions/en.yml
  config/locales/views/submissions/nl.yml
Labels: feature

#3918 Clear all grades button
  app/assets/javascripts/feedback/actions.ts
  app/assets/stylesheets/components/btn.css.scss
  app/controllers/feedbacks_controller.rb
  app/policies/feedback_policy.rb
  app/views/feedbacks/_feedback_actions.html.erb
  app/views/feedbacks/_score_actions.html.erb
  config/locales/views/feedbacks/en.yml
  config/locales/views/feedbacks/nl.yml
  config/routes.rb
  test/controllers/feedbacks_controller_test.rb
Labels: enhancement

#3921 Course.js: remove jquery and convert to typescript
  .eslintrc
  app/assets/javascripts/course.js
  app/assets/javascripts/course.ts
  app/javascript/packs/course.js
  tsconfig.json
Labels: chore
