Repository dodona-edu/dodona, pull requests merged in 2022-04, with the labels that each got.

#3459 Add surf sign method
  app/assets/images/idp/surf-logo.svg
  app/controllers/auth/authentication_controller.rb
  app/controllers/auth/omniauth_callbacks_controller.rb
  app/models/provider.rb
  app/models/provider/surf.rb
  app/models/user.rb
  app/views/auth/sign_in.html.erb
  config/credentials.yml.enc
  config/credentials/staging.yml.enc
  config/initializers/devise.rb
  config/locales/views/auth/en.yml
  config/locales/views/auth/nl.yml
  lib/Surf/setup.rb
  lib/Surf/strategy.rb
  test/models/provider_test.rb
Labels: feature

#3514 Use surf test environment on staging
  config/credentials/staging.yml.enc
  lib/Surf/setup.rb
Labels: enhancement

#3549 Improve UI of summary row on series status overview
  app/views/series/_scoresheet_table.html.erb
  config/locales/views/series/en.yml
  config/locales/views/series/nl.yml
Labels: enhancement

#3553 Fix authenticity token verification not being skipped for media requests
  app/controllers/activities_controller.rb
Labels: bug

#3563 Correctly handle each asset type
  app/controllers/activities_controller.rb
Labels: bug

#3573 Remove Cross-Origin headers to fix loading of external resources in exercise descriptions
  app/controllers/activities_controller.rb
  config/environments/development.rb
Labels: bug
