Repository dodona-edu/dodona, pull requests merged in 2022-02, with the labels that each got.

#3327 Merge users through the console
  app/models/user.rb
  lib/tasks/merge_users.rake
  test/models/user_test.rb
  test/tasks/merge_users_test.rb
Labels: feature

#3331 Merge complex institutions with overlapping users
  Gemfile
  Gemfile.lock
  app/models/institution.rb
  app/models/submission.rb
  app/models/user.rb
  db/seeds.rb
  lib/tasks/merge_institutions.rake
  lib/tasks/merge_institutions.rb
  lib/tasks/merge_users.rake
  lib/tasks/merge_users.rb
  test/tasks/merge_institutions_test.rb
  test/tasks/merge_users_test.rb
Labels: feature

#3339 Remove unused column color from courses
  app/models/course.rb
  db/migrate/20220203085509_remove_color_from_courses.rb
  db/schema.rb
  test/factories/courses.rb
  test/fixtures/courses.yml
  test/models/course_test.rb
Labels: chore

#3343 Fix deadline warning not showing up
  app/assets/javascripts/exercise.js
Labels: bug

#3340 Remove Google Analytics
  app/assets/javascripts/exercise.js
  app/assets/javascripts/pythia_submission.js
  app/assets/javascripts/submission.js
  app/assets/javascripts/util.js
  app/views/layouts/_ga_analytics.html.erb
  app/views/layouts/application.html.erb
  app/views/layouts/lti.html.erb
  app/views/pages/privacy.en.html.erb
  app/views/pages/privacy.nl.html.erb
  config/initializers/content_security_policy.rb
Labels: enhancement

#3338 Change sort order for students with teacher rights
  app/controllers/course_members_controller.rb
  app/views/course_members/_members_table.html.erb
Labels: enhancement

#3349 Merge usernames which match case insensitively when merging institutions
  lib/tasks/merge_institutions.rb
  test/tasks/merge_institutions_test.rb
Labels: bug

#3336 Replace sassc-rails with css-bundling and dart sass
  .github/workflows/test.yml
  .gitignore
  Gemfile
  Gemfile.lock
  README.md
  app/assets/builds/.keep
  app/assets/config/manifest.js
  app/assets/stylesheets/application-dark.css.scss.erb
  app/assets/stylesheets/application-dark.sass.scss
  app/assets/stylesheets/application.css.scss.erb
  app/assets/stylesheets/application.sass.scss
  app/assets/stylesheets/components/tokenfield.css.scss
  app/assets/stylesheets/layout/navbar.css.scss
  app/assets/stylesheets/mails.sass.scss
  bin/build-css
  bin/server
  config/environments/production.rb
  config/environments/staging.rb
  package.json
  vendor/assets/stylesheets/vendor.scss
  yarn.lock
Labels: chore

#3364 Add test to courses controller to verify if filters work
  test/controllers/courses_controller_test.rb
Labels: enhancement

#2721 Bump ruby to 3.0.3
  .ruby-version
  Gemfile
  Gemfile.lock
  app/controllers/repositories_controller.rb
  app/models/repository.rb
  app/views/exports/index.html.erb
  app/views/notifications/_small_notifications_table.html.erb
  app/views/repositories/courses.html.erb
  app/views/series/_series.html.erb
  test/controllers/courses_controller_test.rb
  test/controllers/lti_controller_test.rb
Labels: chore

#3293 Enable additional host names
  app/controllers/activities_controller.rb
  app/controllers/application_controller.rb
  app/controllers/auth/saml_controller.rb
  config/credentials/staging.yml.enc
  config/environments/development.rb
  config/environments/production.rb
  config/environments/staging.rb
  config/environments/test.rb
  config/routes.rb
  lib/LTI/auth/settings.rb
  lib/LTI/auth/setup.rb
  lib/OIDC/auth/settings.rb
  lib/OIDC/auth/setup.rb
  lib/SAML/metadata.rb
  lib/SAML/settings.rb
  lib/SAML/setup.rb
Labels: chore

#3373 Fix rendering of manage series
  app/views/series/_course_series_table.html.erb
  test/controllers/courses_controller_test.rb
Labels: bug

#3374 Fix faker deprecation warning in tests
  test/factories/events.rb
Labels: chore

#3365 Include build-css in README
  README.md
Labels: chore

#3372 Bump typescript-eslint to 5.11.0
  package.json
  yarn.lock
Labels: chore

#3370 Sort activity read states by id
  app/models/activity_read_state.rb
Labels: bug

#3371 Add pagination buttons to activity read states index page
  app/views/activity_read_states/_read_states_table.html.erb
Labels: bug

#3368 Remove development dependency spring
  .github/workflows/test.yml
  Gemfile
  Gemfile.lock
  bin/rails
  bin/rake
  bin/spring
  config/spring.rb
Labels: enhancement

#3341 Upgrade to rails 7
  .github/workflows/test.yml
  Gemfile
  Gemfile.lock
  app/controllers/exports_controller.rb
  app/controllers/score_items_controller.rb
  app/views/series/show.js.erb
  bin/rails
  bin/rake
  bin/spring
  config/application.rb
  config/environments/development.rb
  config/environments/production.rb
  config/environments/staging.rb
  config/initializers/content_security_policy.rb
  config/initializers/new_framework_defaults_5.2.rb
  config/initializers/new_framework_defaults_6_1.rb
  config/spring.rb
  db/migrate/20220203123959_remove_not_null_on_active_storage_blobs_checksum.active_storage.rb
  db/schema.rb
  package.json
  yarn.lock
Labels: chore

#3394 Check the user institution when logging in from a new provider
  app/controllers/auth/omniauth_callbacks_controller.rb
  app/models/user.rb
  test/controllers/auth/omniauth_callbacks_controller_test.rb
Labels: bug

#3399 Update to rails 7.0.2.2
  Gemfile
  Gemfile.lock
  app/assets/javascripts/i18n/translations.js
  package.json
  public/javascripts/i18n.js
  yarn.lock
Labels: chore

#3402 Replace use of ActiveRecord::Associations::Preloader by includes
  app/controllers/score_items_controller.rb
Labels: chore

#3397 Replace unsafe method in exports controller by explicit permitting
  app/controllers/exports_controller.rb
Labels: bug

#3403 Don't fetch first and last submission for timeseries if none are present
  app/models/submission.rb
  test/models/submission_test.rb
Labels: bug

#3409 Make sure redirect from sandbox to default host is allowed
  app/controllers/application_controller.rb
Labels: bug

#3404 Adjust color scale of timeseries graph if the time period is updated
  app/assets/javascripts/visualisations/timeseries.ts
Labels: bug

#3405 Clear scores when another submission is selected to grade
  app/models/feedback.rb
  db/seeds.rb
  test/controllers/feedbacks_controller_test.rb
Labels: bug

#3407 Improve labeling of time periods on cumulative plot
  app/assets/javascripts/visualisations/cumulative_timeseries.ts
  app/assets/javascripts/visualisations/timeseries.ts
Labels: bug

#3410 Fix allow_other_host paramater passing
  app/controllers/application_controller.rb
Labels: bug

#3425 Include exercises without any submissions in series analytics
  app/assets/javascripts/visualisations/cumulative_timeseries.ts
  app/assets/javascripts/visualisations/violin.ts
  app/controllers/statistics_controller.rb
  test/controllers/statistics_controller_test.rb
Labels: bug

#3426 Improve color scheme of dark mode for the cumulative time series and heatmap
  app/assets/javascripts/heatmap.ts
  app/assets/javascripts/visualisations/timeseries.ts
Labels: bug

#3429 Fix the link in the popup notice to set series activities visible
  app/views/series/_series.html.erb
Labels: bug

#3428 Remove the thick black borders on top of some tables
  app/assets/stylesheets/bootstrap_style_overrides.css.scss
  app/views/repositories/show.html.erb
Labels: bug

#3427 Verify the email of git users is set before sending them errors
  app/controllers/repositories_controller.rb
  test/controllers/repositories_controller_test.rb
Labels: bug

#3435 Fix reloading pending users after mass accept/decline
  app/views/courses/mass_accept_pending.json.jbuilder
  app/views/courses/mass_decline_pending.json.jbuilder
  test/controllers/courses_controller_test.rb
Labels: bug

#3436 Fix copy courses index method when no user is detected
  app/controllers/courses_controller.rb
Labels: bug
