Repository dodona-edu/dodona, pull requests merged in 2022-09, with the labels that each got.

#3947 Migrate smartschool identifiers from username to userID
  app/controllers/auth/omniauth_callbacks_controller.rb
  app/models/identity.rb
  config/initializers/smartschool.rb
  db/migrate/20220830124315_add_identifier_based_on_username_to_identity.rb
  db/schema.rb
  test/controllers/auth/omniauth_callbacks_controller_test.rb
  test/factories/identities.rb
  test/models/identity_test.rb
Labels: bug

#3958 Revert "Course.js: remove jquery and convert to typescript"
  .eslintrc
  app/assets/javascripts/course.js
  app/assets/javascripts/course.ts
  app/javascript/packs/course.js
  tsconfig.json
Labels: bug

#3961 Fix empty series in course crash
  .eslintrc
  app/assets/javascripts/course.js
  app/assets/javascripts/course.ts
  app/javascript/packs/course.js
  tsconfig.json
Labels: bug

#3971 Fix course user tabs
  app/assets/javascripts/course.ts
Labels: bug

#3963 favorite_course_buttons.js: remove jquery and use typescript
  app/assets/javascripts/favorite_course_buttons.js
  app/assets/javascripts/favorite_course_buttons.ts
  app/javascript/packs/favorite_course_buttons.js
Labels: chore

#3964 Update .browserslist
  .browserslistrc
Labels: chore

#3957 Update identitities for correct provider in migration
  db/migrate/20220830124315_add_identifier_based_on_username_to_identity.rb
Labels: bug

#3956 Rename private to personal accounts
  config/locales/views/auth/en.yml
  config/locales/views/auth/nl.yml
  config/locales/views/courses/en.yml
  config/locales/views/courses/nl.yml
Labels: enhancement

#3972 Use state variable to detect whether popstate should trigger
  app/assets/javascripts/search.ts
Labels: enhancement

#3955 Update microsoft sign in button name and logo for personal accounts
  app/assets/images/idp/microsoft.png
  app/models/provider/g_suite.rb
  app/models/provider/office365.rb
  config/locales/views/auth/en.yml
  config/locales/views/auth/nl.yml
Labels: enhancement

#3977 Fix submitting to an exercise outside the context of a course
  app/assets/javascripts/exercise.ts
Labels: bug

#3975 Replace i18n-js by polyglot
  app/assets/javascripts/code_listing/code_listing.ts
  app/assets/javascripts/code_listing/question_annotation.ts
  app/assets/javascripts/code_listing/user_annotation.ts
  app/assets/javascripts/i18n/i18n.ts
  app/assets/javascripts/i18n/translations.json
  app/assets/javascripts/types/index.d.ts
  app/assets/javascripts/visualisations/series_graph.ts
  app/assets/javascripts/visualisations/timeseries.ts
  app/javascript/packs/application_pack.js
  config/locales/defaults/en.yml
  config/locales/defaults/nl.yml
  package.json
  test/javascript/setup-jest.ts
  test/javascript/visualisations.test.ts
  tsconfig.json
  yarn.lock
Labels: enhancement

#4000 Revert bootstrap to 5.2.0
  package.json
  yarn.lock
Labels: dependencies

#4001 Block smartschool co-accounts
  app/controllers/auth/omniauth_callbacks_controller.rb
  config/initializers/smartschool.rb
  config/locales/devise.en.yml
  config/locales/devise.nl.yml
  test/controllers/auth/omniauth_callbacks_controller_test.rb
Labels: bug

#4003 Allow the same email accross different institutions after user confirmation
  app/controllers/auth/omniauth_callbacks_controller.rb
  app/models/user.rb
  app/views/auth/confirm_new_user.html.erb
  config/initializers/office365.rb
  config/locales/views/auth/en.yml
  config/locales/views/auth/nl.yml
  config/routes.rb
  db/migrate/20220914075029_update_index_to_users_to_email.rb
  db/schema.rb
  lib/LTI/auth/strategy.rb
  lib/SAML/strategy.rb
  test/controllers/auth/omniauth_callbacks_controller_test.rb
Labels: enhancement

#4005 Don't store current location for confirm new user page
  app/controllers/application_controller.rb
Labels: bug

#4006 Silently discard captcha spam
  app/controllers/pages_controller.rb
  test/controllers/pages_controller_test.rb
Labels: bug

#4022 Improve evaluation sidebar size on vertical screens
  app/views/feedbacks/show.html.erb
  app/views/submissions/show.html.erb
Labels: bug

#4028 Fix ufora LTI authentication
  Gemfile
  Gemfile.lock
  app/controllers/auth/omniauth_callbacks_controller.rb
  app/views/auth/_provider_button.html.erb
  app/views/auth/sign_in.html.erb
  lib/LTI/auth/settings.rb
  test/controllers/auth/omniauth_callbacks_controller_test.rb
  test/integration/auth/vlaanderen/oidc_vlaanderen_test.rb
Labels: bug

#4025 Redirect from confirm new user and privacy page to root if no session info is available
  app/controllers/auth/omniauth_callbacks_controller.rb
Labels: bug

#4044 Ask questions link to guide was not interpreted
  app/assets/javascripts/components/annotations/annotation_form.ts
Labels: bug

#4046 Fix width of questions table actions
  app/assets/stylesheets/models/questions.css.scss
Labels: bug

#4045 Fix listgroup background color in dark mode
  app/assets/stylesheets/bootstrap_style_overrides.css.scss
Labels: bug
