Repository dodona-edu/dodona, pull requests merged in 2022-07, with the labels that each got.

#3758 Replace green by a less fluorecent version and use it as success color
  app/assets/stylesheets/theme/m3-colors.css.scss
  app/assets/stylesheets/theme/m3-theme.css.scss
Labels: enhancement

#3760 Only allow submissions within the same course to be considered within an evaluation
  app/models/feedback.rb
  test/controllers/feedbacks_controller_test.rb
  test/models/feedback_test.rb
Labels: bug

#3684 Update Papyros
  app/assets/javascripts/coding_scratchpad.ts
  app/assets/stylesheets/components/scratchpad.css.scss
  package.json
  test/system/scratchpad_test.rb
  yarn.lock
Labels: dependencies

#3778 Improve the color scheme of heatmaps
  app/assets/javascripts/heatmap.ts
  app/assets/javascripts/visualisations/timeseries.ts
Labels: enhancement

#3762 Add announcement in database seed with login tokens
  db/seeds.rb
Labels: chore

#3779 Add stylelint as scss linter
  .github/workflows/lint.yml
  .stylelintrc
  app/assets/stylesheets/base.css.scss
  app/assets/stylesheets/bootstrap_style_overrides.css.scss
  app/assets/stylesheets/bootstrap_variable_overrides.css.scss
  app/assets/stylesheets/components.css.scss
  app/assets/stylesheets/components/btn.css.scss
  app/assets/stylesheets/components/callout.css.scss
  app/assets/stylesheets/components/card.css.scss
  app/assets/stylesheets/components/code_listing.css.scss
  app/assets/stylesheets/components/evaluations.css.scss
  app/assets/stylesheets/components/histogram.css.scss
  app/assets/stylesheets/components/img.css.scss
  app/assets/stylesheets/components/notification.css.scss
  app/assets/stylesheets/components/progress-chart.css.scss
  app/assets/stylesheets/components/scratchpad.css.scss
  app/assets/stylesheets/components/search_field.css.scss
  app/assets/stylesheets/components/stepper.css.scss
  app/assets/stylesheets/components/table-toolbar.css.scss
  app/assets/stylesheets/components/table.css.scss
  app/assets/stylesheets/components/tokenfield.css.scss
  app/assets/stylesheets/components/visualisations.css.scss
  app/assets/stylesheets/layout.css.scss
  app/assets/stylesheets/layout/drawer.css.scss
  app/assets/stylesheets/layout/footer.css.scss
  app/assets/stylesheets/layout/navbar.css.scss
  app/assets/stylesheets/libraries/dragula.css.scss
  app/assets/stylesheets/libraries/glightbox.css.scss
  app/assets/stylesheets/mails.sass.scss
  app/assets/stylesheets/material_icons.css.scss
  app/assets/stylesheets/mixins.css.scss
  app/assets/stylesheets/models/activities.css.scss
  app/assets/stylesheets/models/announcements.css.scss
  app/assets/stylesheets/models/course.css.scss
  app/assets/stylesheets/models/programming_languages.css.scss
  app/assets/stylesheets/models/repository.css.scss
  app/assets/stylesheets/models/series.css.scss
  app/assets/stylesheets/models/submissions.css.scss
  app/assets/stylesheets/models/users.css.scss
  app/assets/stylesheets/pages/home.css.scss
  app/assets/stylesheets/pages/sign-in.css.scss
  app/assets/stylesheets/print.css.scss
  app/assets/stylesheets/theme/ace.css.scss
  app/assets/stylesheets/theme/m3-theme-dark.css.scss
  app/assets/stylesheets/theme/rouge.css.scss
  package.json
  yarn.lock
Labels: chore

#3764 Fix about page header layout when it contains alerts
  app/assets/stylesheets/pages/home.css.scss
Labels: bug

#3781 Revert to legacy color css notation for browser support
  .stylelintrc
  app/assets/stylesheets/components/btn.css.scss
  app/assets/stylesheets/components/card.css.scss
  app/assets/stylesheets/components/table-toolbar.css.scss
  app/assets/stylesheets/components/table.css.scss
  app/assets/stylesheets/components/tokenfield.css.scss
  app/assets/stylesheets/mixins.css.scss
Labels: chore

#3783 Fix CSS style to stop linter from complaining
  app/assets/stylesheets/pages/home.css.scss
Labels: chore

#3784 Fix response message for mass rejudge
  app/assets/javascripts/components/search_actions.ts
Labels: bug

#3787 Remove dropdowns where they were too large for practical use in production
  app/views/activities/index.html.erb
  app/views/annotations/question_index.html.erb
  app/views/series/edit.html.erb
  app/views/users/index.html.erb
Labels: bug

#3786 Send error email when user signs in with duplicate email for provider
  app/controllers/auth/omniauth_callbacks_controller.rb
Labels: bug

#3789 Fix typo on user show page
  config/locales/views/users/en.yml
Labels: bug

#3790 Prevent default redirect after click on close token
  app/assets/javascripts/components/search_token.ts
Labels: bug

#3788 Improve the database seed for development
  db/seeds.rb
Labels: chore
