Repository dodona-edu/dodona, pull requests merged in 2022-11, with the labels that each got.

#4151 Fix rendering of strikethrough on the remove course admin button
  app/assets/stylesheets/material_icons.css.scss
Labels: bug

#4152 Fix support for exercise config in the repository root
  app/models/repository.rb
  test/models/repository_test.rb
Labels: bug

#4153 Add `unstarted_by` scope to exercise model
  app/models/exercise.rb
  test/models/exercise_test.rb
Labels: enhancement

#4166 Update the contact information of the VTC
  app/views/pages/privacy.en.html.erb
  app/views/pages/privacy.nl.html.erb
Labels: enhancement

#4176 Add ESLint rules for Web & Lit Components
  .eslintrc
  package.json
  yarn.lock
Labels: chore

#4083 course_membership.js: replace with webcomponent
  app/assets/javascripts/components/course_labels_search_bar.ts
  app/assets/javascripts/components/datalist_input.ts
  app/assets/javascripts/course_membership.js
  app/assets/javascripts/i18n/translations.json
  app/assets/stylesheets/components.css.scss
  app/assets/stylesheets/components/courselabel-edit.css.scss
  app/javascript/packs/course_membership.js
  app/views/course_members/_form.html.erb
  config/locales/js/en.yml
  config/locales/js/nl.yml
Labels: chore

#4170 Fix series preview table height on the course page
  app/assets/javascripts/course.ts
  app/assets/stylesheets/models/series.css.scss
  app/models/course.rb
  app/models/series.rb
  app/models/submission.rb
  app/views/series/_series.html.erb
  db/migrate/20221117132148_add_exercise_status_course_index_to_submissions.rb
  db/schema.rb
  test/factories/courses.rb
  test/factories/series.rb
  test/fixtures/courses.yml
  test/models/course_test.rb
  test/models/series_test.rb
Labels: bug

#4189 Remove tokenfield typeahead
  Gemfile
  Gemfile.lock
  app/assets/javascripts/application_old.js
  app/assets/stylesheets/base.css.scss
  app/assets/stylesheets/components.css.scss
  app/assets/stylesheets/components/table-toolbar.css.scss
  app/assets/stylesheets/components/token.css.scss
  app/assets/stylesheets/components/tokenfield.css.scss
  bin/build-css
  config/deploy.rb
  package.json
  tsconfig.json
  vendor/assets/stylesheets/.keep
  vendor/assets/stylesheets/bootstrap-tokenfield/tokenfield-typeahead.css.scss
  vendor/assets/stylesheets/vendor.scss
  yarn.lock
Labels: chore

#4163 Use OIDC for elixir login
  app/controllers/auth/authentication_controller.rb
  app/controllers/auth/omniauth_callbacks_controller.rb
  app/models/provider.rb
  app/models/provider/elixir.rb
  app/models/user.rb
  app/views/auth/_provider_button.html.erb
  app/views/auth/sign_in.html.erb
  config/credentials.yml.enc
  config/credentials/staging.yml.enc
  config/initializers/devise.rb
  config/locales/models/en.yml
  config/locales/models/nl.yml
  lib/Elixir/setup.rb
  lib/Elixir/strategy.rb
Labels: bug

#4127 submission.js: remove jquery and convert to typescript
  app/assets/javascripts/submission.js
  app/assets/javascripts/submission.ts
  app/javascript/packs/submission.js
Labels: chore

#4186 Show teacher rights notification on public contact page
  app/views/pages/contact.html.erb
Labels: enhancement

#4188 Seasonal series completion icon
  app/assets/images/seasonal/series_status_overlays/christmas-hover.svg
  app/assets/images/seasonal/series_status_overlays/christmas.svg
  app/assets/stylesheets/base.css.scss
  app/assets/stylesheets/seasonal/christmas.css.scss
  app/helpers/seasonal_helper.rb
  app/views/series/_series_status.html.erb
Labels: feature

#4193 Fix elixir production credentials
  config/credentials.yml.enc
Labels: bug, high priority

#4194 Fix merge institutions when there are users with overlapping email addresses
  app/models/institution.rb
  lib/tasks/merge_institutions.rb
  test/tasks/merge_institutions_test.rb
Labels: bug

#4205 Ignore invalid mime types by responding with bad request
  app/controllers/application_controller.rb
Labels: bug
