Repository dodona-edu/dodona, pull requests merged in 2022-10, with the labels that each got.

#4048 Fix annotations not shown bug for submissions outside a course
  app/assets/javascripts/code_listing/code_listing.ts
  app/helpers/renderers/feedback_code_renderer.rb
Labels: bug

#4049 SAML: Allow clock drift to account for clock skew between servers
  lib/SAML/strategy.rb
Labels: bug

#4047 Remove direct dependency on sinatra
  Gemfile
  Gemfile.lock
Labels: chore

#4029 Fix ufora LTI authentication without revert
  Gemfile
  Gemfile.lock
  app/views/auth/_provider_button.html.erb
  app/views/auth/sign_in.html.erb
  lib/LTI/auth/strategy.rb
  test/controllers/auth/omniauth_callbacks_controller_test.rb
  test/integration/auth/vlaanderen/oidc_vlaanderen_test.rb
Labels: bug

#4023 Replace sign_in.js by webcomponent
  app/assets/javascripts/components/datalist_input.ts
  app/assets/javascripts/components/sign_in_search_bar.ts
  app/assets/javascripts/i18n/translations.json
  app/assets/javascripts/sign_in.js
  app/assets/javascripts/util.js
  app/assets/stylesheets/pages/sign-in.css.scss
  app/javascript/packs/sign_in.js
  app/views/auth/sign_in.html.erb
  config/locales/js/en.yml
  config/locales/js/nl.yml
  config/locales/views/auth/en.yml
  config/locales/views/auth/nl.yml
  db/seeds.rb
Labels: chore

#4061 Correctly set scores and completed states when a new user is added to an evaluation
  app/models/feedback.rb
  test/models/evaluation_test.rb
Labels: bug

#4074 Remove variable signature around non variable text on confirm new user page
  config/locales/views/auth/nl.yml
Labels: bug

#4080 punchcard.js: convert to typescript
  app/assets/javascripts/punchcard.ts
  app/javascript/packs/visualisations.js
Labels: chore

#4070 Fix wrong hostname used when using rails `object_url` helper
  app/controllers/application_controller.rb
Labels: bug

#4069 Store auth hash in cache instead of session to fix cookie overflow
  app/controllers/auth/omniauth_callbacks_controller.rb
  test/controllers/auth/omniauth_callbacks_controller_test.rb
Labels: bug

#4082 Allow get requests for ILearn authentication
  config/routes.rb
  lib/LTI/auth/strategy.rb
Labels: bug

#4112 Rename 'demo mode' to 'anonymous mode'
  config/locales/views/defaults/en.yml
  config/locales/views/defaults/nl.yml
Labels: enhancement

#4111 Throw a 406 error instead of a 500 error when trying to load a json description
  app/controllers/activities_controller.rb
  test/controllers/activities_controller_test.rb
Labels: bug

#4093 Create github action for deploying the database backup to naos
  .github/workflows/deploy-db-backup-to-naos.yml
Labels: chore
