Repository dodona-edu/dodona, pull requests merged in 2022-06, with the labels that each got.

#3688 Force office 365 sign in to prompt user selection before sign in
  config/initializers/office365.rb
Labels: bug

#3689 Improve webcomponent naming and documentation
  app/assets/javascripts/components/datalist_input.ts
  app/assets/javascripts/components/dropdown_filter.ts
  app/assets/javascripts/components/filter_button.ts
  app/assets/javascripts/components/filter_collection_element.ts
  app/assets/javascripts/components/histogram.ts
  app/assets/javascripts/components/search_actions.ts
  app/assets/javascripts/components/search_field.ts
  app/assets/javascripts/components/search_token.ts
  app/assets/javascripts/components/sort_button.ts
  app/assets/stylesheets/components/histogram.css.scss
  app/views/activities/_activities_table.html.erb
  app/views/activities/_labels.html.erb
  app/views/activities/_series_activities_add_table.html.erb
  app/views/activity_read_states/_read_states_table.html.erb
  app/views/annotations/_questions_table.html.erb
  app/views/announcements/_form.html.erb
  app/views/course_members/_members_table.html.erb
  app/views/courses/_scoresheet_table.html.erb
  app/views/layouts/_searchbar.html.erb
  app/views/series/_scoresheet_table.html.erb
  app/views/submissions/_submission.html.erb
  app/views/submissions/_submissions_table.html.erb
Labels: chore

#3647 Remove io-wait pin
  Gemfile
  Gemfile.lock
Labels: chore

#3690 Minimize js bundle sizes
  app/assets/javascripts/heatmap.ts
  app/assets/javascripts/util.js
  app/assets/javascripts/visualisations/series_graph.ts
  app/views/layouts/application.html.erb
  app/views/layouts/frame.html.erb
  app/views/layouts/lti.html.erb
  config/webpack/webpack.config.js
  package.json
  yarn.lock
Labels: chore

#3692 Remove jquery usage for detecting if the dom is ready
  app/assets/javascripts/copy.ts
  app/assets/javascripts/util.js
  app/helpers/renderers/feedback_code_renderer.rb
  app/helpers/renderers/pythia_renderer.rb
  app/javascript/packs/application_pack.js
  app/javascript/packs/frame.js
  app/views/activities/_coding_scratchpad.html.erb
  app/views/activities/description.html.erb
  app/views/activities/show.html.erb
  app/views/annotations/_questions_table.html.erb
  app/views/announcements/_form.html.erb
  app/views/course_members/_form.html.erb
  app/views/course_members/index.html.erb
  app/views/course_members/index.js.erb
  app/views/course_members/show.html.erb
  app/views/courses/_not_a_member_dialog.html.erb
  app/views/courses/index.html.erb
  app/views/courses/manage_series.html.erb
  app/views/courses/new.html.erb
  app/views/courses/scoresheet.html.erb
  app/views/courses/show.html.erb
  app/views/evaluations/_form.html.erb
  app/views/evaluations/edit.html.erb
  app/views/evaluations/new.html.erb
  app/views/exports/download_submissions.html.erb
  app/views/feedbacks/_feedback_actions.html.erb
  app/views/feedbacks/show.html.erb
  app/views/institutions/merge.html.erb
  app/views/layouts/_navbar.html.erb
  app/views/layouts/_searchbar.html.erb
  app/views/notifications/_notifications_table.html.erb
  app/views/notifications/_small_notifications_table.html.erb
  app/views/pages/home.html.erb
  app/views/repositories/admins.html.erb
  app/views/repositories/courses.html.erb
  app/views/series/_form.html.erb
  app/views/series/_series.html.erb
  app/views/series/edit.html.erb
  app/views/series/scoresheet.html.erb
  app/views/series/show.js.erb
  app/views/submissions/show.html.erb
  app/views/visualizations/_heatmap.html.erb
  app/views/visualizations/_punchcard.html.erb
Labels: chore

#3694 Format scss files
  app/assets/stylesheets/bootstrap_variable_overrides.css.scss
  app/assets/stylesheets/components.css.scss
  app/assets/stylesheets/components/callout.css.scss
  app/assets/stylesheets/components/card.css.scss
  app/assets/stylesheets/components/code_listing.css.scss
  app/assets/stylesheets/components/dropdown-filter.css.scss
  app/assets/stylesheets/components/evaluations.css.scss
  app/assets/stylesheets/components/img.css.scss
  app/assets/stylesheets/components/notification.css.scss
  app/assets/stylesheets/components/progress-chart.css.scss
  app/assets/stylesheets/components/scratchpad.css.scss
  app/assets/stylesheets/components/search_field.css.scss
  app/assets/stylesheets/components/stepper.css.scss
  app/assets/stylesheets/components/table-toolbar.css.scss
  app/assets/stylesheets/components/table.css.scss
  app/assets/stylesheets/components/tokenfield.css.scss
  app/assets/stylesheets/components/tutor.css.scss
  app/assets/stylesheets/components/visualisations.css.scss
  app/assets/stylesheets/layout.css.scss
  app/assets/stylesheets/layout/drawer.css.scss
  app/assets/stylesheets/layout/footer.css.scss
  app/assets/stylesheets/layout/navbar.css.scss
  app/assets/stylesheets/material_icons.css.scss
  app/assets/stylesheets/models/course.css.scss
  app/assets/stylesheets/models/programming_languages.css.scss
  app/assets/stylesheets/models/questions.css.scss
  app/assets/stylesheets/models/series.css.scss
  app/assets/stylesheets/models/submissions.css.scss
  app/assets/stylesheets/models/users.css.scss
  app/assets/stylesheets/pages/export.css.scss
  app/assets/stylesheets/pages/home.css.scss
  app/assets/stylesheets/pages/sign-in.css.scss
  app/assets/stylesheets/print.css.scss
Labels: chore

#3695 Implement Material 3 colors
  app/assets/javascripts/code_listing/code_listing.ts
  app/assets/javascripts/heatmap.ts
  app/assets/javascripts/visualisations/timeseries.ts
  app/assets/stylesheets/application-dark.sass.scss
  app/assets/stylesheets/application.sass.scss
  app/assets/stylesheets/base.css.scss
  app/assets/stylesheets/bootstrap_style_overrides.css.scss
  app/assets/stylesheets/bootstrap_variable_overrides.css.scss
  app/assets/stylesheets/components.css.scss
  app/assets/stylesheets/components/btn.css.scss
  app/assets/stylesheets/components/callout.css.scss
  app/assets/stylesheets/components/card.css.scss
  app/assets/stylesheets/components/code_listing.css.scss
  app/assets/stylesheets/components/evaluations.css.scss
  app/assets/stylesheets/components/favorite.css.scss
  app/assets/stylesheets/components/heatmap.css.scss
  app/assets/stylesheets/components/histogram.css.scss
  app/assets/stylesheets/components/modal.css.scss
  app/assets/stylesheets/components/notification.css.scss
  app/assets/stylesheets/components/progress-chart.css.scss
  app/assets/stylesheets/components/punchcard.css.scss
  app/assets/stylesheets/components/scratchpad.css.scss
  app/assets/stylesheets/components/stepper.css.scss
  app/assets/stylesheets/components/table-toolbar.css.scss
  app/assets/stylesheets/components/table.css.scss
  app/assets/stylesheets/components/toast.css.scss
  app/assets/stylesheets/components/tokenfield.css.scss
  app/assets/stylesheets/components/tutor.css.scss
  app/assets/stylesheets/components/visualisations.css.scss
  app/assets/stylesheets/layout/drawer.css.scss
  app/assets/stylesheets/layout/footer.css.scss
  app/assets/stylesheets/layout/navbar.css.scss
  app/assets/stylesheets/libraries/dragula.css.scss
  app/assets/stylesheets/libraries/flatpickr.css.scss
  app/assets/stylesheets/mails.sass.scss
  app/assets/stylesheets/material_icons.css.scss
  app/assets/stylesheets/models/activities.css.scss
  app/assets/stylesheets/models/announcements.css.scss
  app/assets/stylesheets/models/course.css.scss
  app/assets/stylesheets/models/institutions.css.scss
  app/assets/stylesheets/models/programming_languages.css.scss
  app/assets/stylesheets/models/score_items.css.scss
  app/assets/stylesheets/models/series.css.scss
  app/assets/stylesheets/models/submissions.css.scss
  app/assets/stylesheets/pages/home.css.scss
  app/assets/stylesheets/pages/sign-in.css.scss
  app/assets/stylesheets/theme/colors.css.scss
  app/assets/stylesheets/theme/development.css.scss
  app/assets/stylesheets/theme/m3-colors.css.scss
  app/assets/stylesheets/theme/m3-theme-dark.css.scss
  app/assets/stylesheets/theme/m3-theme-light.css.scss
  app/assets/stylesheets/theme/m3-theme.css.scss
  app/assets/stylesheets/theme/theme-dark.css.scss
  app/assets/stylesheets/theme/theme-light.css.scss
  app/models/course.rb
  app/models/label.rb
  app/views/layouts/_searchbar.html.erb
  app/views/pages/_pending_courses_card.html.erb
  app/views/users/show.html.erb
  db/seeds.rb
Labels: feature

#3663 Merge users when they try to sign in with the same username into the same institution
  app/controllers/auth/omniauth_callbacks_controller.rb
  app/models/event.rb
  app/models/user.rb
  config/locales/devise.en.yml
  config/locales/devise.nl.yml
Labels: feature

#3748 Set browser color scheme to dark in dark mode
  app/assets/stylesheets/theme/m3-theme-dark.css.scss
  app/assets/stylesheets/theme/m3-theme-light.css.scss
Labels: enhancement

#3749 Set indigo as 22-23 course card color
  app/models/course.rb
  app/views/pages/_course_card.html.erb
Labels: enhancement

#3646 Update to ruby 3.1
  .rubocop.yml
  .ruby-version
  Gemfile
  Gemfile.lock
  app/controllers/application_controller.rb
  app/helpers/application_helper.rb
  app/models/repository.rb
  app/models/transient/aggregated_config_errors.rb
  test/testhelpers/delayed_job_helper.rb
  test/testhelpers/stub_helper.rb
Labels: chore

#3751 Add required bioschema keys to course metadata
  app/views/courses/show.html.erb
Labels: feature

#3725 Color code thumbs up/down on hover in evaluation
  app/assets/stylesheets/components/btn.css.scss
Labels: enhancement

#3670 Let users sign in with a known provider before linking a new provider to the user
  app/assets/stylesheets/components/card.css.scss
  app/assets/stylesheets/models/users.css.scss
  app/controllers/auth/authentication_controller.rb
  app/controllers/auth/omniauth_callbacks_controller.rb
  app/controllers/users_controller.rb
  app/models/provider.rb
  app/models/provider/g_suite.rb
  app/models/provider/office365.rb
  app/models/provider/smartschool.rb
  app/models/provider/surf.rb
  app/models/user.rb
  app/views/auth/_provider_button.html.erb
  app/views/auth/redirect_to_known_provider.html.erb
  app/views/auth/sign_in.html.erb
  app/views/layouts/_main_container.html.erb
  app/views/users/_user_short.html.erb
  app/views/users/show.html.erb
  config/locales/devise.en.yml
  config/locales/devise.nl.yml
  config/locales/views/auth/en.yml
  config/locales/views/auth/nl.yml
  config/locales/views/users/en.yml
  config/locales/views/users/nl.yml
  test/controllers/auth/omniauth_callbacks_controller_test.rb
Labels: feature

#3754 Never link to activity when viewing inside course and not accessible
  app/views/activities/_series_activities_table.html.erb
Labels: bug

#3755 Show banner on hidden series with unregistered user instead of redirecting
  app/controllers/series_controller.rb
  app/policies/series_policy.rb
  config/locales/views/series/en.yml
  config/locales/views/series/nl.yml
Labels: bug

#3756 Slightly darker danger and success in dark mode
  app/assets/stylesheets/theme/m3-theme-dark.css.scss
Labels: enhancement

#3759 Tweak the rainbow status color
  app/assets/stylesheets/models/series.css.scss
Labels: enhancement
