Repository dodona-edu/dodona, pull requests merged in 2022-12, with the labels that each got.

#4203 Add scoping tabs to activity list pages to improve usability
  app/assets/javascripts/components/filter_tabs.ts
  app/assets/javascripts/course.ts
  app/assets/javascripts/search.ts
  app/controllers/activities_controller.rb
  app/controllers/series_controller.rb
  app/javascript/packs/course.js
  app/javascript/packs/search.js
  app/models/activity.rb
  app/models/repository.rb
  app/policies/repository_policy.rb
  app/views/activities/index.html.erb
  app/views/courses/index.html.erb
  app/views/repositories/_form.html.erb
  app/views/series/edit.html.erb
  config/locales/views/activities/en.yml
  config/locales/views/activities/nl.yml
  config/locales/views/repositories/en.yml
  config/locales/views/repositories/nl.yml
  db/migrate/20221129091433_add_featured_to_repository.rb
  db/schema.rb
  db/seeds.rb
  test/controllers/courses_controller_test.rb
  test/controllers/repositories_controller_test.rb
  test/factories/repositories.rb
  test/models/activity_test.rb
  test/models/repository_test.rb
  test/system/courses_test.rb
Labels: feature

#4209 drag_and_drop.js: remove jquery and convert to typescript
  app/assets/javascripts/course.ts
  app/assets/javascripts/drag_and_drop.js
  app/assets/javascripts/drag_and_drop.ts
  app/assets/javascripts/favorite_course_buttons.ts
  app/assets/javascripts/series.js
  app/assets/javascripts/submission.ts
  app/assets/javascripts/util.js
  package.json
Labels: chore

#4233 Add alt host `dodona.be` to config hosts
  config/environments/production.rb
Labels: chore

#4235 Fix activities index page when not signed in
  app/controllers/activities_controller.rb
  test/controllers/activities_controller_test.rb
Labels: bug

#4236 Set assets host to current host on production
  config/environments/production.rb
Labels: chore

#4238 Fix my_institution activities tab when not signed in
  app/models/activity.rb
  app/models/repository.rb
  test/models/activity_test.rb
Labels: bug

#4239 Don't reset filter text field every time other params change
  app/assets/javascripts/components/filter_collection_element.ts
  app/assets/javascripts/components/search_field.ts
Labels: bug

#4245 Only show course from latest year on home page
  app/assets/javascripts/components/standalone-dropdown-filter.ts
  app/assets/javascripts/favorite_course_buttons.ts
  app/assets/javascripts/search.ts
  app/controllers/pages_controller.rb
  app/javascript/packs/application_pack.js
  app/views/pages/_course_cards.html.erb
  app/views/pages/home.html.erb
  app/views/pages/home.js.erb
Labels: feature

#4260 Remove popularity icon when adding an activity to a series
  app/assets/javascripts/series.js
Labels: bug
