Repository dodona-edu/dodona, pull requests merged in 2023-04, with the labels that each got.

#4547 Use `create_or_find_by` to reduce activity status deadlocks
  app/models/activity.rb
  app/models/activity_status.rb
  app/models/series_membership.rb
  test/models/activity_status_test.rb
Labels: bug

#4549 Improve the UX for restoring boilerplate
  app/assets/javascripts/exercise.ts
  app/views/activities/show.html.erb
  config/locales/views/activities/en.yml
  config/locales/views/activities/nl.yml
  test/system/activities_test.rb
Labels: enhancement

#4550 Fix broken links from feedback tab to code-tab
  app/assets/javascripts/submission.ts
  app/helpers/renderers/feedback_table_renderer.rb
  app/views/submissions/show.html.erb
Labels: bug

#4567 Fix mestra deploy
  config/deploy/mestra.rb
  db/seeds.rb
Labels: bug, chore

#4463 pythia_submissions.js: remove jquery and convert to typescript
  app/assets/javascripts/pythia_submission.js
  app/assets/javascripts/pythia_submission.ts
  app/assets/javascripts/types/index.d.ts
  app/javascript/packs/pythia_submission.js
Labels: chore

#4568 Render machine annotations for multiple lines or columns
  app/assets/javascripts/code_listing.ts
  app/assets/javascripts/components/annotations/annotations_cell.ts
  app/assets/javascripts/components/annotations/code_listing_row.ts
  app/assets/javascripts/components/annotations/hidden_annotations_dot.ts
  app/assets/javascripts/components/annotations/machine_annotation_marker.ts
  app/assets/javascripts/components/saved_annotations/saved_annotations_sidecard.ts
  app/assets/javascripts/mark.ts
  app/assets/javascripts/state/Annotations.ts
  app/assets/javascripts/state/MachineAnnotations.ts
  app/assets/stylesheets/components/code_listing.css.scss
  app/javascript/packs/submission.js
  app/runners/result_constructor.rb
  app/views/feedbacks/show.html.erb
  package.json
  test/javascript/mark.test.ts
  test/runners/result_constructor_test.rb
  yarn.lock
Labels: feature

#4586 Process rows and columns for python judge annotations
  app/helpers/renderers/pythia_renderer.rb
Labels: enhancement
