Repository dodona-edu/dodona, pull requests merged in 2023-05, with the labels that each got.

#4600 Delete issues to project workflow
  .github/workflows/issuesToProject.yml
Labels: chore

#4613 Don't suggest completed activities, sereis or courses on homepage
  app/models/user.rb
  test/models/user_test.rb
Labels: bug

#4627 Allow connection to mathjax in CSP
  config/initializers/content_security_policy.rb
Labels: bug

#4628 Allow mathjax to fail without breaking annotations
  app/assets/javascripts/components/annotations/user_annotation.ts
  app/assets/javascripts/exercise.ts
  app/assets/javascripts/types/index.d.ts
  app/helpers/renderers/feedback_code_renderer.rb
Labels: bug

#4639 Only validate judge output when errors are encountered
  app/assets/javascripts/i18n/translations.json
  app/runners/result_constructor.rb
  test/runners/result_constructor_test.rb
Labels: enhancement

#4581 Create hotfix script
  bin/hotfix
Labels: chore, no-release-notes

#4596 Allow creation of user annotations based on a selection
  app/assets/javascripts/code_listing.ts
  app/assets/javascripts/components/annotations/annotation_marker.ts
  app/assets/javascripts/components/annotations/annotations_cell.ts
  app/assets/javascripts/components/annotations/annotations_count_badge.ts
  app/assets/javascripts/components/annotations/code_listing_row.ts
  app/assets/javascripts/components/annotations/create_annotation_button.ts
  app/assets/javascripts/components/annotations/machine_annotation.ts
  app/assets/javascripts/components/annotations/machine_annotation_marker.ts
  app/assets/javascripts/components/annotations/select.ts
  app/assets/javascripts/components/annotations/selection_marker.ts
  app/assets/javascripts/components/annotations/thread.ts
  app/assets/javascripts/i18n/translations.json
  app/assets/javascripts/mark.ts
  app/assets/javascripts/state/Annotations.ts
  app/assets/javascripts/state/MachineAnnotations.ts
  app/assets/javascripts/state/UserAnnotations.ts
  app/assets/stylesheets/components/btn.css.scss
  app/assets/stylesheets/components/card.css.scss
  app/assets/stylesheets/components/code_listing.css.scss
  app/models/annotation.rb
  app/models/question.rb
  app/policies/annotation_policy.rb
  app/views/annotations/_annotation.json.jbuilder
  config/locales/js/en.yml
  config/locales/js/nl.yml
  db/migrate/20230425073306_add_range_to_annotations.rb
  db/schema.rb
  test/factories/annotations.rb
  test/javascript/code_listing.test.ts
  test/javascript/components/annotations/select.test.ts
  test/models/annotation_test.rb
  test/system/annotations_test.rb
  test/system/questions_test.rb
  test/system/saved_annotation_test.rb
Labels: feature

#4642 Smoothly transition to larger create annotation button
  app/assets/javascripts/components/annotations/create_annotation_button.ts
  app/assets/stylesheets/components/code_listing.css.scss
Labels: enhancement

#4646 Don't define values to be nil when json validation expects undefined
  app/runners/result_constructor.rb
Labels: bug

#4647 Revert #4646 and #4639
  app/assets/javascripts/i18n/translations.json
  app/runners/result_constructor.rb
  test/runners/result_constructor_test.rb
Labels: bug, high priority

#4657 Show zero indexed machine annotations on first line instead of global
  app/assets/javascripts/state/MachineAnnotations.ts
Labels: bug

#4658 Use vertical dots for the annotation context menu
  app/assets/javascripts/components/annotations/user_annotation.ts
Labels: enhancement

#4660 Fix unselecting code by clicking outside code
  app/assets/javascripts/components/annotations/select.ts
Labels: bug

#4661 Fix `@time_messages` being nil bug
  app/runners/submission_runner.rb
Labels: bug

#4667 Revert rack-mini-profiler to version 3.0.0
  Gemfile
  Gemfile.lock
Labels: bug

#4668 Revert ddtrace to version 1.10.1
  Gemfile
  Gemfile.lock
Labels: bug

#4675 Fix combination of line highlight and annotation color
  app/assets/javascripts/i18n/translations.json
  app/assets/stylesheets/components/code_listing.css.scss
Labels: bug

#4686 Replace mentions of 'master' and 'develop' by 'main'
  .github/release-drafter.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/lint.yml
  .github/workflows/release-drafter.yml
  .github/workflows/test.yml
  README.md
  bin/hotfix
  bin/release
  config/deploy.rb
  config/deploy/mestra.rb
  config/deploy/production.rb
  config/deploy/staging.rb
Labels: chore

#4694 Inherit secrets for workflows that use them
  .github/workflows/deploy-production-safe.yml
Labels: bug, no-release-notes

#4695 Split up deployment queues and fix secret inheritance
  .github/workflows/deploy-production-safe.yml
Labels: bug, no-release-notes

#4697 Fix user nil error for saved annotations
  app/policies/saved_annotation_policy.rb
Labels: bug

#4698 Rename the safe deploy workflow
  .github/workflows/test-and-deploy-production.yml
Labels: chore, no-release-notes
