Repository dodona-edu/dodona, pull requests merged in 2023-03, with the labels that each got.

#4454 Remove dependency on glob
  config/webpack/webpack.config.js
  package.json
  yarn.lock
Labels: dependencies

#4457 Add code coverage for javascript
  .github/workflows/test.yml
  Gemfile
  Gemfile.lock
  codecov.yml
  test/test_helper.rb
Labels: chore

#4458 Add test for d-datalist-input
  app/assets/javascripts/components/datalist_input.ts
  package.json
  test/javascript/components/datalist_input.test.ts
  yarn.lock
Labels: chore

#4460 Add tests for d-pagination
  app/assets/javascripts/search.ts
  app/javascript/packs/search.js
  test/javascript/components/pagination.test.ts
Labels: chore

#4481 Fix course year dropdown on homepage
  app/javascript/packs/application_pack.js
  app/javascript/packs/search.js
  app/views/pages/home.html.erb
Labels: bug, high priority

#4484 Show series on public course pages
  app/policies/series_policy.rb
  test/system/courses_test.rb
Labels: bug

#4462 Add tests for search components
  app/assets/javascripts/components/filter_button.ts
  app/assets/javascripts/components/filter_collection_element.ts
  app/assets/javascripts/components/search_actions.ts
  app/assets/javascripts/components/search_field.ts
  app/assets/javascripts/components/sort_button.ts
  test/javascript/components/search/dropdown_filter.test.ts
  test/javascript/components/search/filter_button.test.ts
  test/javascript/components/search/filter_tabs.test.ts
  test/javascript/components/search/search_actions.test.ts
  test/javascript/components/search/search_field.test.ts
  test/javascript/components/search/search_token.test.ts
  test/javascript/components/search/sort_button.test.ts
  test/javascript/components/search/standalone-dropdown-filter.test.ts
Labels: chore

#4465 scoresheet.js: remove jquery and convert to typescript
  app/assets/javascripts/scoresheet.js
  app/assets/javascripts/scoresheet.ts
Labels: chore

#4487 Replace most_recent_correct by most_resent submissions filter
  app/controllers/submissions_controller.rb
  app/models/submission.rb
  app/views/submissions/index.html.erb
  config/locales/views/submissions/en.yml
  config/locales/views/submissions/nl.yml
  test/controllers/submissions_controller_test.rb
Labels: enhancement

#4488 Add copy code button to code fragments in descriptions
  app/assets/javascripts/components/copy_button.ts
  app/assets/javascripts/exercise.ts
  app/assets/stylesheets/components/btn.css.scss
  app/assets/stylesheets/models/activities.css.scss
  app/helpers/activity_helper.rb
  app/javascript/packs/description.js
  app/views/activities/description.html.erb
Labels: enhancement

#4498 Fix relative time indication for submission history
  app/assets/javascripts/i18n/translations.json
  app/controllers/submissions_controller.rb
  app/helpers/time_helper.rb
  config/locales/defaults/en.yml
  config/locales/defaults/nl.yml
  config/locales/views/submissions/en.yml
  config/locales/views/submissions/nl.yml
  test/helpers/time_helper_test.rb
Labels: bug

#4500 Check lower limit for memory_limit setting
  app/models/exercise.rb
  test/models/repository_test.rb
  test/testhelpers/remote_helper.rb
Labels: enhancement

#4485 Preload the latest submission in the editor on the activity show page
  app/assets/javascripts/exercise.ts
  app/assets/stylesheets/models/activities.css.scss
  app/controllers/activities_controller.rb
  app/views/activities/show.html.erb
  config/locales/views/activities/en.yml
  config/locales/views/activities/nl.yml
  test/system/activities_test.rb
Labels: enhancement, deploy naos

#4501 Do not show finished series as continue working on suggestion
  app/models/user.rb
  test/models/user_test.rb
Labels: enhancement

#4526 Take all javascript into account for coverage calculation
  .github/workflows/test.yml
  babel.config.js
  codecov.yml
  jest.config.js
  package.json
  test/application_system_test_case.rb
  yarn.lock
Labels: chore

#4529 Add scriptingtalen as beta course
  app/assets/javascripts/saved_annotation_beta.ts
  app/policies/saved_annotation_policy.rb
Labels: no-release-notes

#4510 Add extra motivational messages generated by chatGPT
  app/assets/javascripts/i18n/translations.json
  app/assets/javascripts/submission.ts
  config/locales/js/en.yml
  config/locales/js/nl.yml
Labels: enhancement
