Repository dodona-edu/dodona, pull requests merged in 2023-11, with the labels that each got.

#5098 Fix repo processing crash when labels contained an integer
  app/models/activity.rb
Labels: bug

#5100 Enable indents with tab in codemirror
  app/assets/javascripts/editor.ts
Labels: bug

#5118 Add uniqueness validation to repository remote url
  app/models/repository.rb
  db/migrate/20231107160330_add_unique_to_repository_remote.rb
  db/schema.rb
  db/seeds.rb
  test/controllers/repositories_controller_test.rb
Labels: bug

#5119 Only build js once during rails test
  .github/workflows/test.yml
Labels: chore

#5121 Revert "Add uniqueness validation to repository remote url"
  app/models/repository.rb
  db/migrate/20231107160330_add_unique_to_repository_remote.rb
  db/schema.rb
  db/seeds.rb
  test/controllers/repositories_controller_test.rb
Labels: bug

#5122 Fix ufora integration
  app/javascript/packs/application_pack.js
Labels: bug

#5124 Only return administrating courses in LTI picker
  app/controllers/lti_controller.rb
  test/controllers/lti_controller_test.rb
Labels: bug

#5095 Create task that destroys removed activities
  app/jobs/remove_activities_job.rb
  test/jobs/remove_activities_job_test.rb
Labels: enhancement

#5127 Never remove exercises that are part of an evaluation
  app/jobs/remove_activities_job.rb
  test/jobs/remove_activities_job_test.rb
Labels: bug

#5102 Rework the feedback table
  app/assets/javascripts/submission.ts
  app/assets/stylesheets/components/card.css.scss
  app/assets/stylesheets/components/tutor.css.scss
  app/assets/stylesheets/models/submissions.css.scss
  app/helpers/renderers/feedback_table_renderer.rb
  app/helpers/renderers/pythia_renderer.rb
  config/locales/views/submissions/en.yml
  config/locales/views/submissions/nl.yml
  test/system/annotations_test.rb
Labels: feature

#5131 Fix feedback table crash when there are no groups
  app/helpers/renderers/feedback_table_renderer.rb
Labels: bug

#5129 Rephrase evaluation finished toast
  app/assets/javascripts/i18n/translations.json
  config/locales/js/en.yml
  config/locales/js/nl.yml
Labels: bug

#5126 Do not send emails to github noreply
  app/models/repository.rb
  test/models/repository_test.rb
Labels: bug, chore

#5128 Add uniqueness validation to repository remote url
  app/models/repository.rb
  db/migrate/20231107160330_add_unique_to_repository_remote.rb
  db/schema.rb
  db/seeds.rb
  test/controllers/repositories_controller_test.rb
Labels: bug

#5149 Update add-remove-label action
  .github/workflows/deploy-mestra.yml
  .github/workflows/deploy-naos.yml
Labels: dependencies

#5136 Stop Sprockets from compressing JS
  Gemfile
  Gemfile.lock
  config/environments/production.rb
  config/environments/staging.rb
Labels: chore

#5150 Update the label action
  .github/workflows/deploy-mestra.yml
  .github/workflows/deploy-naos.yml
Labels: dependencies

#5151 Blur class progress in anonymous mode
  app/assets/stylesheets/components.css.scss
  app/views/activities/_series_activities_table.html.erb
Labels: enhancement

#5120 Add safety net for unresponsive docker containers
  app/runners/submission_runner.rb
Labels: bug

#5152 Don't send emails for slow requests and internal errors
  app/exceptions/internal_error_exception.rb
  app/exceptions/slow_request_exception.rb
  app/models/submission.rb
  config/environments/development.rb
  config/environments/production.rb
  config/environments/staging.rb
  config/initializers/exception_notification.rb
Labels: chore

#5159 Allow submitting the annotation form using Ctrl-Enter as well
  app/assets/javascripts/components/annotations/annotation_form.ts
Labels: enhancement

#5158 Make ctrl-f more usable on submissions
  app/assets/javascripts/components/annotations/line_of_code.ts
Labels: bug

#5157 Recalculate selected code upon copy in submission
  app/assets/javascripts/code_listing.ts
  app/assets/javascripts/components/annotations/selectionHelpers.ts
  test/javascript/components/annotations/select.test.ts
Labels: bug

#5161 Update CITATION.cff file to mention the recently published Dodona article
  CITATION.cff
Labels: chore

#5164 Fix input field layout for annotation form
  app/assets/javascripts/components/annotations/annotation_form.ts
Labels: bug

#5162 Make team explicit and add publications page
  app/assets/images/publications/maertens-2022.png
  app/assets/images/publications/maertens-2023.png
  app/assets/images/publications/strijbol-2022.png
  app/assets/images/publications/strijbol-2023.png
  app/assets/images/publications/vanpetegem-2022.png
  app/assets/images/publications/vanpetegem-2023-2.png
  app/assets/images/publications/vanpetegem-2023.png
  app/assets/stylesheets/pages.css.scss
  app/assets/stylesheets/pages/publications.css.scss
  app/controllers/pages_controller.rb
  app/views/layouts/_breadcrumbs.html.erb
  app/views/layouts/_footer.html.erb
  app/views/pages/_team.en.html.erb
  app/views/pages/_team.nl.html.erb
  app/views/pages/data.en.html.erb
  app/views/pages/data.nl.html.erb
  app/views/pages/publications.html.erb
  config/locales/views/defaults/en.yml
  config/locales/views/defaults/nl.yml
  config/locales/views/pages/en.yml
  config/locales/views/pages/nl.yml
  config/routes.rb
Labels: enhancement

#5163 Submit saved annotation form on enter
  app/assets/javascripts/components/saved_annotations/new_saved_annotation.ts
Labels: bug

#5167 Don't show saved annotations from other users to zeus
  app/policies/saved_annotation_policy.rb
  test/controllers/saved_annotation_controller_test.rb
Labels: bug

#5169 Partially remove saml monkey patch
  app/controllers/auth/saml_controller.rb
  lib/SAML/metadata.rb
  test/controllers/auth/saml_controller_test.rb
Labels: chore

#5172 Add KULeuven notice to sign in page
  app/views/auth/sign_in.html.erb
Labels: no-release-notes

#5173 Revert "Add KULeuven notice to sign in page"
  app/views/auth/sign_in.html.erb
Labels: no-release-notes

#5170 Remove css variables from email css
  app/assets/stylesheets/mails.sass.scss
  app/assets/stylesheets/theme/rouge-hardcoded-light.css.scss
Labels: bug

#5187 Add tests for saml metadata
  test/controllers/auth/ku_leuven_metadata.xml
  test/controllers/auth/saml_controller_test.rb
Labels: chore, no-release-notes

#5186 Update rails cache version
  config/application.rb
Labels: chore

#5189 Add year to course name in saved annotations filter
  app/views/layouts/_searchbar.html.erb
Labels: bug

#5191 Increase disc write rate limit
  app/runners/submission_runner.rb
Labels: bug

#5205 Fix line of code not shown on invalid judge output
  app/assets/javascripts/components/annotations/line_of_code.ts
Labels: bug
