Repository dodona-edu/dodona, pull requests merged in 2023-10, with the labels that each got.

#5022 Fix sorting for most recent submission per user
  app/controllers/submissions_controller.rb
  test/controllers/submissions_controller_test.rb
Labels: bug

#5024 Avoid git race conditions by allowing only one worker
  config/deploy/production.rb
Labels: bug

#5032 Add slack invite link to readme
  README.md
Labels: chore, no deploy

#5049 Mock fetch in js tests
  test/javascript/code_listing.test.ts
Labels: bug

#5051 Fix js tests
  test/javascript/code_listing.test.ts
Labels: bug

#5054 Set the color for active FABs
  app/assets/stylesheets/components/btn.css.scss
Labels: bug

#5057 Harmonize comment menu wording
  app/assets/javascripts/i18n/translations.json
  config/locales/js/en.yml
  config/locales/js/nl.yml
Labels: bug, no deploy

#5056 Tweak the wording of the "select submission" during evaluations
  app/views/feedbacks/show.html.erb
  config/locales/views/feedbacks/en.yml
  config/locales/views/feedbacks/nl.yml
Labels: bug, no deploy

#5058 Use correct language for exercise names in exports
  app/helpers/export_helper.rb
Labels: bug, no deploy

#5059 Fix submission table overflow
  app/assets/stylesheets/bootstrap_style_overrides.css.scss
  app/assets/stylesheets/models/submissions.css.scss
Labels: bug, no deploy

#5060 Fix score table overflow
  app/assets/stylesheets/models/score_items.css.scss
Labels: bug, no deploy

#5061 Refactor right request index from table to card list view
  app/assets/stylesheets/components/card.css.scss
  app/controllers/rights_requests_controller.rb
  app/views/rights_requests/_requests_table.html.erb
  app/views/rights_requests/approve.js.erb
  app/views/rights_requests/index.html.erb
  app/views/rights_requests/reject.js.erb
  config/locales/views/rights_requests/en.yml
  config/locales/views/rights_requests/nl.yml
Labels: enhancement

#5050 Allow python tutor for every judge
  app/assets/javascripts/file_viewer.ts
  app/assets/javascripts/tutor.ts
  app/helpers/renderers/feedback_table_renderer.rb
  app/helpers/renderers/pythia_renderer.rb
  app/javascript/packs/pythia_submission.js
  app/javascript/packs/submission.js
  app/runners/result_constructor.rb
  app/views/activities/show.html.erb
  app/views/feedbacks/show.html.erb
  app/views/submissions/_description.html.erb
  public/schemas/judge_output.json
  public/schemas/partial_output.json
  test/runners/result_constructor_test.rb
Labels: feature

#5076 Return valid json in mock method
  test/javascript/code_listing.test.ts
Labels: chore

#5078 Remove extra closing div on feedback show page
  app/views/feedbacks/show.html.erb
Labels: bug

#5052 Run python tutor backend in browser
  app/assets/javascripts/tutor.ts
  app/views/layouts/application.html.erb
  config/application.rb
  config/environments/development.rb
  config/environments/production.rb
  config/environments/staging.rb
  config/environments/test.rb
  config/initializers/content_security_policy.rb
  config/webpack/webpack.config.js
  package.json
  yarn.lock
Labels: feature

#5082 Fix assets not available in production
  config/deploy/staging.rb
  config/environments/staging.rb
  config/initializers/assets.rb
  config/webpack/webpack.config.js
  lib/tasks/assets.rake
Labels: bug

#4998 Add draft flag to activities
  app/assets/stylesheets/models/activities.css.scss
  app/controllers/activities_controller.rb
  app/controllers/pages_controller.rb
  app/models/activity.rb
  app/models/content_page.rb
  app/models/exercise.rb
  app/models/submission.rb
  app/models/user.rb
  app/policies/activity_policy.rb
  app/views/activities/_activities_table.html.erb
  app/views/activities/_draft_notice.html.erb
  app/views/activities/_form.html.erb
  app/views/activities/_repository_status.html.erb
  app/views/activities/_series_activities_add_table.html.erb
  app/views/activities/edit.html.erb
  app/views/activities/info.html.erb
  app/views/activities/show.html.erb
  app/views/pages/_user_card.html.erb
  config/locales/views/activities/en.yml
  config/locales/views/activities/nl.yml
  config/locales/views/pages/en.yml
  config/locales/views/pages/nl.yml
  db/migrate/20230922115708_add_draft_to_activities.rb
  db/migrate/20231026075353_make_draft_default_true.rb
  db/schema.rb
  db/seeds.rb
  test/controllers/activities_controller_test.rb
  test/factories/content_pages.rb
  test/factories/exercises.rb
  test/fixtures/exercises.yml
  test/models/activity_test.rb
  test/models/exercise_test.rb
Labels: feature

#5080 Upgrade to lit 3.0
  app/assets/javascripts/components/annotations/code_listing_row.ts
  app/assets/javascripts/components/annotations/hidden_annotations_dot.ts
  app/assets/javascripts/components/meta/shadowless_lit_element.ts
  app/assets/javascripts/punchcard.ts
  app/assets/javascripts/state/state_system/StateProperty.ts
  babel.config.js
  config/webpack/webpack.config.js
  package.json
  tsconfig.json
  yarn.lock
Labels: chore

#5083 Blur potentially sensitive info while in anonymous mode
  app/assets/stylesheets/components.css.scss
  app/views/activities/_series_activities_table.html.erb
  app/views/pages/_user_card.html.erb
Labels: enhancement

#4970 Replace Ace Editor with CodeMirror 6
  .eslintignore
  .github/dependabot.yml
  Gemfile
  Gemfile.lock
  app/assets/config/manifest.js
  app/assets/javascripts/ace_editor.js
  app/assets/javascripts/coding_scratchpad.ts
  app/assets/javascripts/editor.ts
  app/assets/javascripts/exercise.ts
  app/assets/stylesheets/base.css.scss
  app/assets/stylesheets/models/activities.css.scss
  app/assets/stylesheets/models/submissions.css.scss
  app/assets/stylesheets/theme/ace.css.scss
  app/assets/stylesheets/theme/codemirror.css.scss
  app/assets/stylesheets/theme/m3-theme-dark.css.scss
  app/assets/stylesheets/theme/m3-theme-light.css.scss
  app/assets/stylesheets/theme/rouge.css.scss
  app/controllers/concerns/.keep
  app/views/activities/show.html.erb
  app/views/announcements/_announcement.html.erb
  package.json
  tsconfig.json
  yarn.lock
Labels: enhancement

#5096 Add link to exercise docs in teacher mail
  app/views/rights_request_mailer/approved.en.html.erb
  app/views/rights_request_mailer/approved.en.text.erb
  app/views/rights_request_mailer/approved.nl.html.erb
  app/views/rights_request_mailer/approved.nl.text.erb
Labels: enhancement
