Repository dodona-edu/dodona, pull requests merged in 2023-12, with the labels that each got.

#5206 Always print judge output when encountering a ResultConstructorError
  app/runners/submission_runner.rb
Labels: enhancement

#5204 Update papyros to version 2.0.0
  app/assets/stylesheets/base.css.scss
  app/assets/stylesheets/components/scratchpad.css.scss
  app/controllers/activities_controller.rb
  app/controllers/application_controller.rb
  app/views/activities/_coding_scratchpad.html.erb
  config/locales/views/activities/en.yml
  config/locales/views/activities/nl.yml
  config/webpack/webpack.config.js
  package.json
  yarn.lock
Labels: chore

#5222 Unregister old serviceworkers manualy
  app/assets/javascripts/coding_scratchpad.ts
Labels: bug, high priority

#5221 Apply dodona theme to papyros
  app/assets/javascripts/coding_scratchpad.ts
  app/assets/javascripts/editor.ts
  app/assets/stylesheets/components/scratchpad.css.scss
  app/assets/stylesheets/theme/codemirror.css.scss
  app/views/activities/_coding_scratchpad.html.erb
Labels: enhancement

#5223 Reduce the number of days santa claus takes over dodona
  app/assets/stylesheets/base.css.scss
  app/assets/stylesheets/seasonal/december.css.scss
  app/helpers/seasonal_helper.rb
Labels: enhancement

#5235 Fix broken pythia submission if data is not present in group
  app/helpers/renderers/pythia_renderer.rb
  test/controllers/submissions_controller_test.rb
Labels: bug

#5190 Add edit submission link when evaluating a submission
  app/assets/javascripts/code_listing.ts
  app/assets/javascripts/components/annotations/annotation_options.ts
  app/assets/javascripts/i18n/translations.json
  app/assets/javascripts/state/Submissions.ts
  app/assets/javascripts/state/Users.ts
  app/assets/stylesheets/components/card.css.scss
  app/assets/stylesheets/models/activities.css.scss
  app/assets/stylesheets/models/submissions.css.scss
  app/helpers/renderers/feedback_code_renderer.rb
  app/policies/submission_policy.rb
  app/views/feedbacks/show.html.erb
  app/views/submissions/show.html.erb
  config/locales/js/en.yml
  config/locales/js/nl.yml
  test/javascript/code_listing.test.ts
Labels: enhancement

#5249 Require valid token to view series activities
  app/controllers/activities_controller.rb
  app/controllers/series_controller.rb
  app/policies/series_policy.rb
  test/controllers/activities_controller_test.rb
Labels: bug
