Repository dodona-edu/dodona, pull requests merged in 2023-09, with the labels that each got.

#4959 Fix dragging create annotation button for padding pixels
  app/assets/javascripts/components/annotations/create_annotation_button.ts
  test/system/annotations_test.rb
  test/system/questions_test.rb
  test/system/saved_annotation_test.rb
Labels: bug

#4933 Replace Ace Editor with CodeMirror
  .eslintignore
  .github/dependabot.yml
  Gemfile
  Gemfile.lock
  app/assets/config/manifest.js
  app/assets/javascripts/ace_editor.js
  app/assets/javascripts/coding_scratchpad.ts
  app/assets/javascripts/editor.ts
  app/assets/javascripts/exercise.ts
  app/assets/stylesheets/base.css.scss
  app/assets/stylesheets/models/activities.css.scss
  app/assets/stylesheets/models/submissions.css.scss
  app/assets/stylesheets/theme/ace.css.scss
  app/assets/stylesheets/theme/codemirror.css.scss
  app/assets/stylesheets/theme/rouge.css.scss
  app/controllers/concerns/.keep
  app/views/activities/show.html.erb
  app/views/announcements/_announcement.html.erb
  package.json
  tsconfig.json
  yarn.lock
Labels: deploy mestra, enhancement, deploy naos

#4963 Fix breaking of spaces at the end of a code line
  app/assets/stylesheets/components/code_listing.css.scss
Labels: bug

#4958 Only close annotation form on focus loss when empty
  app/assets/javascripts/components/annotations/annotation_form.ts
  test/javascript/code_listing.test.ts
Labels: bug

#4884 Allow creating a saved annotations with the same title
  app/assets/javascripts/components/annotations/annotation_form.ts
  app/assets/javascripts/components/saved_annotations/new_saved_annotation.ts
  app/assets/javascripts/components/saved_annotations/saved_annotation_form.ts
  app/assets/javascripts/components/saved_annotations/saved_annotation_title_input.ts
  app/assets/javascripts/i18n/translations.json
  app/assets/javascripts/state/SavedAnnotations.ts
  app/javascript/packs/saved_annotation.js
  app/models/saved_annotation.rb
  app/models/user.rb
  app/views/saved_annotations/edit.html.erb
  config/locales/js/en.yml
  config/locales/js/nl.yml
  db/migrate/20230810105908_remove_unique_key_on_saved_annotation_title.rb
  db/schema.rb
  test/controllers/saved_annotation_controller_test.rb
  test/factories/users.rb
  test/fixtures/users.yml
  test/models/user_test.rb
Labels: enhancement

#4906 Update browserlist
  .browserslistrc
  babel.config.js
  package.json
Labels: chore

#4964 Do not redirect to repository media after login
  app/controllers/repositories_controller.rb
Labels: bug

#4967 Fix search by username in account linking flow
  app/controllers/auth/omniauth_callbacks_controller.rb
  test/controllers/auth/omniauth_callbacks_controller_test.rb
Labels: bug

#4982 Group testing library updates
  .github/dependabot.yml
Labels: chore

#4987 Fix docker images not being shut down
  app/runners/submission_runner.rb
Labels: bug

#4988 Show submission numbers in evalution submission selection
  app/views/feedbacks/_submissions_table.html.erb
Labels: bug

#4990 Fix annotating part of a line
  app/assets/javascripts/components/annotations/selectionHelpers.ts
Labels: bug

#4989 Make wavy underline markings smaller
  app/assets/javascripts/components/annotations/annotation_marker.ts
  app/assets/javascripts/components/annotations/line_of_code.ts
  app/assets/stylesheets/base.css.scss
  app/assets/stylesheets/components/code_listing.css.scss
  app/assets/stylesheets/mixins.css.scss
  app/assets/stylesheets/theme/m3-theme-dark.css.scss
  app/assets/stylesheets/theme/m3-theme-light.css.scss
Labels: enhancement

#4991 Fix system test chromedriver version
  .github/workflows/test.yml
Labels: bug

#4965 Allow creating saved annotations by searching annotations
  app/assets/javascripts/components/annotations/annotation_form.ts
  app/assets/javascripts/components/annotations/user_annotation.ts
  app/assets/javascripts/components/saved_annotations/new_saved_annotation.ts
  app/assets/javascripts/components/saved_annotations/new_saved_annotation_link.ts
  app/assets/javascripts/components/saved_annotations/saved_annotation_form.ts
  app/assets/javascripts/components/saved_annotations/saved_annotation_input.ts
  app/assets/javascripts/components/saved_annotations/saved_annotation_title_input.ts
  app/assets/javascripts/i18n/translations.json
  app/assets/javascripts/state/SavedAnnotations.ts
  app/controllers/saved_annotations_controller.rb
  app/javascript/packs/saved_annotation.js
  app/models/annotation.rb
  app/policies/saved_annotation_policy.rb
  app/views/annotations/_annotations_table.html.erb
  app/views/saved_annotations/index.html.erb
  app/views/saved_annotations/new.html.erb
  app/views/saved_annotations/new.js.erb
  app/views/saved_annotations/show.html.erb
  app/views/saved_annotations/show.js.erb
  config/locales/js/en.yml
  config/locales/js/nl.yml
  config/locales/views/annotations/en.yml
  config/locales/views/annotations/nl.yml
  config/locales/views/saved_annotations/en.yml
  config/locales/views/saved_annotations/nl.yml
  config/routes.rb
Labels: enhancement

#4992 Make saved annotations available in all courses
  app/assets/javascripts/components/annotations/annotation_form.ts
  app/assets/javascripts/components/annotations/user_annotation.ts
  app/assets/javascripts/components/saved_annotations/saved_annotation_icon.ts
  app/assets/javascripts/saved_annotation_beta.ts
  app/assets/javascripts/state/UserAnnotations.ts
  app/policies/saved_annotation_policy.rb
  test/controllers/saved_annotation_controller_test.rb
  test/javascript/code_listing.test.ts
Labels: feature

#4995 Fix refreshing of course members page after actions
  app/views/courses/_reload_users.js.erb
Labels: bug

#4996 Fix infinite progress bar when filtering students in an evaluation
  app/views/evaluations/show.js.erb
Labels: bug

#5011 Fix occassional failure of javascript tests
  app/assets/javascripts/utilities.ts
Labels: chore

#5012 Show machine annotations on the last line if index out of range
  app/assets/javascripts/state/MachineAnnotations.ts
Labels: bug

#5013 Fix copying selected code without extra newlines
  app/assets/javascripts/code_listing.ts
Labels: bug
