Repository dodona-edu/dodona, pull requests merged in 2023-07, with the labels that each got.

#4806 Bump excon gem
  Gemfile.lock
Labels: dependencies, chore

#4807 Fix memory stats collection during submission running
  app/runners/submission_runner.rb
Labels: bug

#4823 Fix Ufora LTI integration
  lib/LTI/jwk.rb
Labels: bug

#4808 Create monthly release workflow
  .github/workflows/monthly-release.yml
Labels: chore, no deploy

#4844 Add alert for KULeuven
  app/views/auth/sign_in.html.erb
Labels: no-release-notes

#4643 Allow creating multiline annotations by dragging the create button
  app/assets/javascripts/code_listing.ts
  app/assets/javascripts/components/annotations/annotation_form.ts
  app/assets/javascripts/components/annotations/annotation_marker.ts
  app/assets/javascripts/components/annotations/annotation_options.ts
  app/assets/javascripts/components/annotations/annotations_cell.ts
  app/assets/javascripts/components/annotations/code_listing_row.ts
  app/assets/javascripts/components/annotations/create_annotation_button.ts
  app/assets/javascripts/components/annotations/select.ts
  app/assets/javascripts/components/annotations/thread.ts
  app/assets/javascripts/i18n/translations.json
  app/assets/javascripts/mark.ts
  app/assets/javascripts/state/UserAnnotations.ts
  app/assets/javascripts/util.js
  app/assets/stylesheets/components/code_listing.css.scss
  config/locales/js/en.yml
  config/locales/js/nl.yml
Labels: enhancement

#4617 Check if course id is provided for series create
  app/controllers/series_controller.rb
  test/controllers/series_controller_test.rb
Labels: bug

#4847 Avoid crash when calling a delayed job on a deleted question
  app/models/question.rb
  test/controllers/annotations_controller_test.rb
  test/models/annotation_test.rb
  test/testhelpers/delayed_job_helper.rb
Labels: bug

#4843 Make dodona.be the main host in all configs
  config/environments/production.rb
  config/environments/staging.rb
Labels: chore

#4852 Fix typo in monospace font variable
  app/assets/stylesheets/bootstrap_css_variable_overrides.css.scss
Labels: bug
