Repository dodona-edu/dodona, pull requests merged in 2023-01, with the labels that each got.

#4246 Always try to show three cards on homepage top
  app/models/user.rb
  app/views/pages/_important_homepage_links.html.erb
  app/views/pages/clickable_homepage_cards/_activity.html.erb
  app/views/pages/clickable_homepage_cards/_course.html.erb
  app/views/pages/clickable_homepage_cards/_series.html.erb
  config/locales/views/pages/en.yml
  config/locales/views/pages/nl.yml
  test/models/user_test.rb
Labels: feature

#4302 Sort activities of a series by their defined order in the series
  app/controllers/activities_controller.rb
  test/controllers/activities_controller_test.rb
Labels: bug

#4303 Prevent updating of datalist value when no initial filter was set
  app/assets/javascripts/components/datalist_input.ts
Labels: bug

#4283 Don't show activities from hidden series as jump-back in option
  app/models/user.rb
  test/models/user_test.rb
Labels: bug

#4312 Revert mail gem to 2.7.1
  Gemfile
  Gemfile.lock
Labels: bug

#4300 Make sure activity statuses always exist
  app/models/series.rb
  app/models/series_membership.rb
  config/environments/test.rb
  db/seeds.rb
  test/models/activity_status_test.rb
Labels: enhancement

#4298 repository.js: remove jquery and convert to typescript
  app/assets/javascripts/i18n/translations.json
  app/assets/javascripts/repository.js
  app/assets/javascripts/repository.ts
  app/controllers/repositories_controller.rb
  app/javascript/packs/repository.js
  app/views/repositories/_repository_admin_buttons.html.erb
  app/views/repositories/_repository_course_buttons.html.erb
  app/views/repositories/add_admin.js.erb
  app/views/repositories/add_course.js.erb
  app/views/repositories/remove_admin.js.erb
  app/views/repositories/remove_course.js.erb
  config/locales/js/en.yml
  config/locales/js/nl.yml
Labels: chore

#4247 Show class progress on series homepage cards for teachers
  app/assets/stylesheets/bootstrap_variable_overrides.css.scss
  app/models/series.rb
  app/views/pages/clickable_homepage_cards/_series.html.erb
  config/locales/views/pages/en.yml
  config/locales/views/pages/nl.yml
  test/models/series_test.rb
Labels: deploy, enhancement

#4267 export.js: remove jquery and convert to typescript
  app/assets/javascripts/export.js
  app/assets/javascripts/export.ts
  app/javascript/packs/export.js
Labels: chore

#4261 Homepage course cards redesign
  app/assets/javascripts/util.js
  app/assets/stylesheets/base.css.scss
  app/assets/stylesheets/components/action-card.css.scss
  app/assets/stylesheets/components/card.css.scss
  app/assets/stylesheets/components/progress-chart.css.scss
  app/assets/stylesheets/material_icons.css.scss
  app/assets/stylesheets/models/series.css.scss
  app/assets/stylesheets/seasonal/christmas.css.scss
  app/models/course.rb
  app/views/application/_progress_chart.html.erb
  app/views/pages/_course_card.html.erb
  app/views/pages/_popper.html.erb
  app/views/pages/clickable_homepage_cards/_series.html.erb
  app/views/series/_series_status.html.erb
  config/locales/views/pages/en.yml
  config/locales/views/pages/nl.yml
  db/migrate/20230103141404_add_indexes_to_activity_statuses.rb
  db/schema.rb
  test/models/course_test.rb
Labels: feature

#4333 Clear scores of empty feedback on submission select
  app/models/feedback.rb
  test/controllers/feedbacks_controller_test.rb
Labels: bug

#4337 Fix missing translation of search action titles
  app/assets/javascripts/components/search_actions.ts
Labels: bug

#4338 Only list unique elements in dropdowns on the repository page
  app/models/repository.rb
Labels: bug

#4339 Fix test badge link
  README.md
Labels: chore

#4341 Add "cite this repo" to GitHub repo
  CITATION.cff
Labels: chore

#4299 Show more relevant info for teachers on course cards
  app/assets/javascripts/components/loading_bar.ts
  app/assets/javascripts/components/progress_bar.ts
  app/assets/javascripts/i18n/i18n.ts
  app/assets/javascripts/i18n/translations.json
  app/assets/javascripts/search.ts
  app/assets/javascripts/util.js
  app/assets/stylesheets/base.css.scss
  app/assets/stylesheets/components.css.scss
  app/assets/stylesheets/components/action-card.css.scss
  app/assets/stylesheets/components/card.css.scss
  app/assets/stylesheets/components/progress_bar.css.scss
  app/assets/stylesheets/components/table-toolbar.css.scss
  app/assets/stylesheets/material_icons.css.scss
  app/controllers/pages_controller.rb
  app/helpers/pages_helper.rb
  app/javascript/packs/application_pack.js
  app/models/course.rb
  app/models/series.rb
  app/views/layouts/_progress-filter.html.erb
  app/views/layouts/_searchbar.html.erb
  app/views/pages/_course_card.html.erb
  app/views/pages/clickable_homepage_cards/_series.html.erb
  app/views/pages/home.html.erb
  app/views/series/_series_status.html.erb
  config/locales/defaults/en.yml
  config/locales/defaults/nl.yml
  config/locales/js/en.yml
  config/locales/js/nl.yml
  config/locales/views/pages/en.yml
  config/locales/views/pages/nl.yml
  db/migrate/20230119083641_add_index_to_activity_statusses.rb
  db/schema.rb
  test/helpers/pages_helper_test.rb
  test/models/course_test.rb
  test/models/series_test.rb
Labels: feature

#4342 Fix error messages when uploading incorrect user labels
  app/assets/javascripts/course.ts
  app/controllers/course_members_controller.rb
  app/views/course_members/upload_labels_csv.js.erb
  config/locales/views/course_members/en.yml
  config/locales/views/course_members/nl.yml
Labels: bug

#4352 Don't process mathjax math in the code editor
  app/assets/javascripts/exercise.ts
Labels: bug

#4354 Always display score items in a fixed order
  app/models/score.rb
  app/models/score_item.rb
  app/views/evaluations/overview.html.erb
Labels: bug

#4353 Hide output if it is much longer than expected to avoid browser crashes
  app/helpers/renderers/text_differ.rb
  config/locales/views/submissions/en.yml
  config/locales/views/submissions/nl.yml
Labels: bug

#4357 Fix translation missing on submission export
  app/helpers/export_helper.rb
Labels: bug

#4358 Allow submitting an annotation with shortcut from title edit field
  app/assets/javascripts/code_listing/code_listing.ts
  app/assets/javascripts/components/annotations/annotation_form.ts
Labels: enhancement

#4359 Add unique index to series_id for evaluations
  db/migrate/20230127090704_add_unique_index_to_evaluations.rb
  db/schema.rb
Labels: bug

#4374 Rename application_old and only include where relevant
  .eslintignore
  app/assets/config/manifest.js
  app/assets/javascripts/ace_editor.js
  app/assets/javascripts/application_old.js
  app/views/activities/show.html.erb
  app/views/layouts/application.html.erb
  app/views/layouts/frame.html.erb
  app/views/layouts/lti.html.erb
Labels: chore

#4373 Limit the number of notifications requests
  Gemfile
  Gemfile.lock
  app/assets/javascripts/auto_reload.ts
  app/assets/javascripts/code_listing/question_annotation.ts
  app/assets/javascripts/notification.ts
  app/models/question.rb
  app/models/user.rb
  app/views/layouts/_navbar.html.erb
  db/migrate/20230130132327_add_open_questions_count_to_users.rb
  db/schema.rb
  test/factories/users.rb
  test/fixtures/users.yml
  test/models/user_test.rb
Labels: chore
