Repository dodona-edu/dodona, pull requests merged in 2023-08, with the labels that each got.

#4850 question_table.ts: remove jquery
  app/assets/javascripts/question_table.ts
Labels: chore

#4848 Prevent crash on series creation without course
  app/controllers/series_controller.rb
  test/controllers/series_controller_test.rb
Labels: bug

#4618 modal.js: remove jquery and convert to typescript
  app/assets/javascripts/modal.js
  app/assets/javascripts/modal.ts
  app/assets/javascripts/pythia_submission.ts
Labels: chore

#4860 score_item.ts: remove unused functions
  app/assets/javascripts/score_item.ts
  app/javascript/packs/score_item.js
Labels: chore

#4861 Get rid of html encode method
  app/assets/javascripts/components/datalist_input.ts
  app/assets/javascripts/util.js
Labels: chore

#4864 Fix selections growing to include annotations after selection end
  app/assets/javascripts/components/annotations/selectionHelpers.ts
  app/assets/stylesheets/components/code_listing.css.scss
Labels: bug

#4866 Fix github action system test chromedriver version
  .github/workflows/test.yml
Labels: chore, no-release-notes, no deploy

#4862 Reintroduce highlighting annotations on hover
  app/assets/javascripts/components/annotations/annotation_marker.ts
  app/assets/javascripts/components/annotations/annotation_tooltip.ts
  app/assets/javascripts/components/annotations/annotations_cell.ts
  app/assets/javascripts/components/annotations/hidden_annotations_dot.ts
  app/assets/javascripts/components/annotations/line_of_code.ts
  app/assets/javascripts/components/annotations/machine_annotation.ts
  app/assets/javascripts/components/annotations/thread.ts
  app/assets/javascripts/components/annotations/user_annotation.ts
  app/assets/javascripts/state/Annotations.ts
  app/assets/javascripts/state/MachineAnnotations.ts
  app/assets/javascripts/state/UserAnnotations.ts
  app/assets/javascripts/state/state_system/CreateStateFromInterface.ts
  test/javascript/code_listing.test.ts
Labels: enhancement

#4865 Auto expand annotation button when a selection is active
  app/assets/javascripts/components/annotations/create_annotation_button.ts
Labels: enhancement

#4849 util.js: remove jquery and convert to typescript
  app/assets/javascripts/components/annotations/annotation_tooltip.ts
  app/assets/javascripts/components/annotations/annotations_toggles.ts
  app/assets/javascripts/components/annotations/code_listing_row.ts
  app/assets/javascripts/components/annotations/create_annotation_button.ts
  app/assets/javascripts/components/annotations/hidden_annotations_dot.ts
  app/assets/javascripts/components/annotations/user_annotation.ts
  app/assets/javascripts/components/copy_button.ts
  app/assets/javascripts/components/course_labels_search_bar.ts
  app/assets/javascripts/components/meta/i18n_mixin.ts
  app/assets/javascripts/components/progress_bar.ts
  app/assets/javascripts/components/search/filter_button.ts
  app/assets/javascripts/components/search/search_actions.ts
  app/assets/javascripts/components/search/search_field.ts
  app/assets/javascripts/components/sign_in_search_bar.ts
  app/assets/javascripts/copy.ts
  app/assets/javascripts/course.ts
  app/assets/javascripts/drag_and_drop.ts
  app/assets/javascripts/evaluation.ts
  app/assets/javascripts/exercise.ts
  app/assets/javascripts/favorite_course_buttons.ts
  app/assets/javascripts/feedback/actions.ts
  app/assets/javascripts/feedback/score.ts
  app/assets/javascripts/institution.ts
  app/assets/javascripts/lti.ts
  app/assets/javascripts/notification.ts
  app/assets/javascripts/pythia_submission.ts
  app/assets/javascripts/question_table.ts
  app/assets/javascripts/repository.ts
  app/assets/javascripts/score_item.ts
  app/assets/javascripts/search.ts
  app/assets/javascripts/series.ts
  app/assets/javascripts/state/SavedAnnotations.ts
  app/assets/javascripts/state/SearchQuery.ts
  app/assets/javascripts/state/Theme.ts
  app/assets/javascripts/state/UserAnnotations.ts
  app/assets/javascripts/state/Users.ts
  app/assets/javascripts/submission.ts
  app/assets/javascripts/utilities.ts
  app/assets/javascripts/visualisations/series_graph.ts
  app/javascript/packs/announcement.js
  app/javascript/packs/application_pack.js
  app/javascript/packs/course.js
  app/javascript/packs/evaluation.js
  app/javascript/packs/frame.js
  app/javascript/packs/series.js
  test/javascript/components/search/search_actions.test.ts
  test/javascript/utilities.test.js
Labels: chore

#4867 Fix title of create annotation button
  app/assets/javascripts/code_listing.ts
  app/assets/javascripts/components/annotations/code_listing_row.ts
  app/helpers/renderers/feedback_code_renderer.rb
  test/javascript/code_listing.test.ts
Labels: bug

#4869 Remove KULeuven sign in warning
  app/views/auth/sign_in.html.erb
Labels: chore, no-release-notes

#4875 Update hogent saml provider
  app/controllers/auth/authentication_controller.rb
Labels: bug, no-release-notes

#4876 Fix new HOGent SAML sign in method
  lib/SAML/settings.rb
Labels: bug, high priority

#4851 rails views: start removing jQuery
  app/assets/javascripts/utilities.ts
  app/javascript/packs/application_pack.js
  app/views/activities/available.js.erb
  app/views/activities/index.js.erb
  app/views/activities/read.js.erb
  app/views/api_tokens/create.js.erb
  app/views/api_tokens/delete.js.erb
  app/views/course_members/index.js.erb
  app/views/courses/index.js.erb
  app/views/courses/new.js.erb
  app/views/courses/scoresheet.js.erb
  app/views/institutions/index.js.erb
  app/views/institutions/merge.js.erb
  app/views/labels/index.js.erb
  app/views/series/scoresheet.js.erb
  app/views/submissions/index.js.erb
  app/views/users/available_for_repository.js.erb
  app/views/users/index.js.erb
Labels: chore

#4877 Replace jquery html calls by setHTMLExecuteScripts
  app/javascript/packs/frame.js
  app/views/activity_read_states/index.js.erb
  app/views/annotations/question_index.js.erb
  app/views/evaluations/add_users.js.erb
  app/views/evaluations/create.js.erb
  app/views/evaluations/edit.js.erb
  app/views/evaluations/show.js.erb
  app/views/events/index.js.erb
  app/views/feedbacks/edit.js.erb
  app/views/feedbacks/show.js.erb
  app/views/notifications/index.js.erb
  app/views/rights_requests/approve.js.erb
  app/views/rights_requests/reject.js.erb
  app/views/score_items/add_all.js.erb
  app/views/score_items/index.js.erb
Labels: chore

#4881 Introduce blockqoute styling
  app/assets/stylesheets/components.css.scss
Labels: bug

#4880 Fix saving an annotation after editing it
  app/assets/javascripts/components/annotations/user_annotation.ts
Labels: bug

#4883 Replace all mentions of dodona.ugent.be
  .github/FUNDING.yml
  README.md
  app/models/user.rb
  app/views/pages/_about.html.erb
  config/environments/production.rb
  lib/SAML/metadata.rb
  test/remotes/exercises/lasagna/exercises/series/ISBN/description/description.nl.html
Labels: chore

#4886 Remove saved annotations sidecard
  app/assets/javascripts/components/saved_annotations/saved_annotations_sidecard.ts
  app/assets/stylesheets/models/submissions.css.scss
  app/javascript/packs/application_pack.js
  app/views/feedbacks/show.html.erb
  app/views/submissions/show.html.erb
  test/system/saved_annotation_test.rb
Labels: enhancement

#4701 Update annotation form
  app/assets/javascripts/components/annotations/annotation_form.ts
  app/assets/javascripts/components/datalist_input.ts
  app/assets/javascripts/components/saved_annotations/saved_annotation_input.ts
  app/assets/javascripts/components/saved_annotations/saved_annotation_list.ts
  app/assets/javascripts/i18n/translations.json
  app/assets/javascripts/state/SavedAnnotations.ts
  app/assets/stylesheets/bootstrap_style_overrides.css.scss
  app/assets/stylesheets/components/code_listing.css.scss
  config/locales/js/en.yml
  config/locales/js/nl.yml
  test/system/saved_annotation_test.rb
Labels: enhancement

#4885 Create separate show and edit page for saved-annotations
  app/assets/javascripts/components/saved_annotations/edit_saved_annotation.ts
  app/assets/javascripts/components/saved_annotations/saved_annotation_icon.ts
  app/assets/javascripts/components/saved_annotations/saved_annotation_list.ts
  app/assets/javascripts/state/SavedAnnotations.ts
  app/assets/stylesheets/bootstrap_css_variable_overrides.css.scss
  app/assets/stylesheets/theme/m3-theme-dark.css.scss
  app/assets/stylesheets/theme/m3-theme-light.css.scss
  app/controllers/saved_annotations_controller.rb
  app/models/saved_annotation.rb
  app/policies/saved_annotation_policy.rb
  app/views/saved_annotations/edit.html.erb
  app/views/saved_annotations/index.json.jbuilder
  app/views/saved_annotations/show.html.erb
  app/views/saved_annotations/show.json.jbuilder
  config/locales/models/en.yml
  config/locales/models/nl.yml
  config/locales/views/saved_annotations/en.yml
  config/locales/views/saved_annotations/nl.yml
  config/routes.rb
  test/controllers/saved_annotation_controller_test.rb
  test/system/saved_annotation_test.rb
Labels: enhancement

#4887 Make saved annotations filterable and sortable
  app/assets/javascripts/components/saved_annotations/saved_annotation_list.ts
  app/assets/javascripts/i18n/translations.json
  app/assets/javascripts/state/SavedAnnotations.ts
  app/assets/stylesheets/components/token.css.scss
  app/controllers/activities_controller.rb
  app/controllers/concerns/sortable.rb
  app/controllers/institutions_controller.rb
  app/controllers/saved_annotations_controller.rb
  app/controllers/submissions_controller.rb
  app/models/saved_annotation.rb
  app/views/layouts/_searchbar.html.erb
  app/views/saved_annotations/index.html.erb
  app/views/saved_annotations/index.json.jbuilder
  config/locales/js/en.yml
  config/locales/js/nl.yml
Labels: enhancement

#4902 Avoid 403 errors when a user cannot access linked saved annotations
  app/views/annotations/_annotation.json.jbuilder
Labels: bug

#4903 Allow more retries on activity_status deadlock errors
  app/models/activity.rb
Labels: bug

#4915 Group dependabot PRs
  .github/dependabot.yml
Labels: chore

#4917 Rotate office365 OAuth client secret for 2023-2024
  config/credentials.yml.enc
  config/credentials/staging.yml.enc
Labels: chore
