Repository dodona-edu/dodona, pull requests merged in 2023-02, with the labels that each got.

#4266 series.js: remove jquery and convert to typescript
  app/assets/javascripts/series.js
  app/assets/javascripts/series.ts
  app/assets/stylesheets/models/series.css.scss
  app/javascript/packs/evaluation.js
  app/javascript/packs/series.js
Labels: chore

#4377 Perform less repository requests on the course page
  app/views/activities/_series_activities_table.html.erb
Labels: chore

#4376 Keep programming languages in memory
  app/models/exercise.rb
  app/models/programming_language.rb
Labels: chore

#4379 Cache submission `annotated?` as boolean
  app/helpers/renderers/feedback_code_renderer.rb
  app/models/annotation.rb
  app/models/evaluation.rb
  app/models/submission.rb
  app/policies/annotation_policy.rb
  db/migrate/20230202123413_add_annotated_to_submission.rb
  db/schema.rb
  test/factories/submissions.rb
  test/models/submission_test.rb
Labels: chore

#4380 Only show own repositories on the index page for teachers
  app/assets/stylesheets/components/table.css.scss
  app/controllers/repositories_controller.rb
  app/models/user.rb
  app/views/repositories/index.html.erb
  config/locales/views/repositories/en.yml
  config/locales/views/repositories/nl.yml
Labels: enhancement

#4381 Allow editing repositories for repository admins
  app/policies/repository_policy.rb
Labels: enhancement

#4385 Add callout success
  app/assets/stylesheets/components/callout.css.scss
Labels: bug

#4384 Add deploy by label for naos
  .github/workflows/deploy-mestra.yml
  .github/workflows/deploy-naos.yml
Labels: chore

#4386 Fix spelling and grammar
  config/locales/views/activities/en.yml
  config/locales/views/annotations/en.yml
  config/locales/views/announcements/en.yml
  config/locales/views/api_tokens/en.yml
  config/locales/views/auth/en.yml
  config/locales/views/course_members/en.yml
  config/locales/views/courses/en.yml
  config/locales/views/defaults/en.yml
  config/locales/views/error_mailer/en.yml
  config/locales/views/evaluations/en.yml
  config/locales/views/exports/en.yml
  config/locales/views/feedbacks/en.yml
  config/locales/views/institutions/en.yml
  config/locales/views/judges/en.yml
  config/locales/views/lti/en.yml
  config/locales/views/pages/en.yml
  config/locales/views/rights_request_mailer/en.yml
  config/locales/views/rights_requests/en.yml
  config/locales/views/score_items/en.yml
  config/locales/views/series/en.yml
  config/locales/views/submissions/en.yml
  config/locales/views/users/en.yml
  config/locales/views/visualisations/en.yml
Labels: enhancement

#4382 Limit the amount of users exposed by the repository admin screen
  app/controllers/users_controller.rb
  app/views/repositories/admins.html.erb
  app/views/users/_repository_users_table.html.erb
  app/views/users/available_for_repository.js.erb
  config/locales/views/users/en.yml
  config/locales/views/users/nl.yml
Labels: bug

#4383 Fix multiple repository related paper cuts
  app/controllers/repositories_controller.rb
  app/models/concerns/gitable.rb
  app/models/repository.rb
  app/views/activities/_activities_table.html.erb
  app/views/judges/_form.html.erb
  app/views/repositories/_form.html.erb
  app/views/repositories/show.html.erb
  config/locales/models/en.yml
  config/locales/models/nl.yml
  config/locales/views/activities/en.yml
  config/locales/views/activities/nl.yml
  test/controllers/repositories_controller_test.rb
Labels: bug

#4406 Fix big activity repo processing in the db seed
  db/seeds.rb
Labels: bug

#4403 Reprocess repository after editing the default judge
  app/controllers/repositories_controller.rb
  app/models/repository.rb
  app/views/repositories/_form.html.erb
  config/locales/views/repositories/en.yml
  config/locales/views/repositories/nl.yml
  test/controllers/repositories_controller_test.rb
  test/factories/repositories.rb
Labels: enhancement

#4415 Fix overlap in question table
  app/assets/stylesheets/models/questions.css.scss
  app/views/courses/_question_table.html.erb
Labels: bug

#4405 Remove Indianio support
  app/controllers/series_controller.rb
  app/helpers/export_helper.rb
  app/models/series.rb
  app/policies/series_policy.rb
  app/views/series/_form.html.erb
  app/views/series/edit.html.erb
  config/locales/models/en.yml
  config/locales/models/nl.yml
  config/locales/views/series/en.yml
  config/locales/views/series/nl.yml
  config/routes.rb
  db/migrate/20230213084858_remove_indianio_token_from_series.rb
  db/schema.rb
  test/controllers/series_controller_test.rb
  test/factories/series.rb
  test/models/series_test.rb
Labels: enhancement

#4419 Only show icons if course is closed or hidden on home and course page
  app/helpers/courses_helper.rb
  app/views/courses/_grouped_course_cards.html.erb
  app/views/courses/show.html.erb
  app/views/pages/_course_card.html.erb
Labels: bug

#4430 Fix options undefined on user label edit
  app/assets/javascripts/components/datalist_input.ts
Labels: bug, high priority

#4418 Fix comma's at the end of activity labels
  app/views/activities/_labels.html.erb
Labels: bug

#4432 Fix the 'hide learning activities' checkbox for series
  app/views/series/_form.html.erb
Labels: bug

#4445 Fix second divider in profile menu for different fonts
  app/assets/stylesheets/bootstrap_style_overrides.css.scss
Labels: bug

#4431 Ask for confirmation when making series visible
  app/views/series/_series.html.erb
  config/locales/views/series/en.yml
  config/locales/views/series/nl.yml
Labels: feature
