Repository dodona-edu/dodona, pull requests merged in 2024-02, with the labels that each got.

#5330 Require at least one correct submission and a valid config before publishing
  app/assets/stylesheets/models/activities.css.scss
  app/models/activity.rb
  app/views/activities/_draft_notice.html.erb
  config/locales/models/en.yml
  config/locales/models/nl.yml
  config/locales/views/activities/en.yml
  config/locales/views/activities/nl.yml
  test/controllers/activities_controller_test.rb
  test/models/activity_test.rb
Labels: enhancement

#5351 Replace checkboxes with icons in draft notice
  app/assets/stylesheets/models/activities.css.scss
  app/views/activities/_draft_notice.html.erb
Labels: enhancement

#5360 Make copy course button more prominent for featured courses
  app/helpers/courses_helper.rb
  app/views/courses/show.html.erb
  config/locales/views/courses/en.yml
  config/locales/views/courses/nl.yml
Labels: enhancement

#5358 Avoid duplicate series icon when favoring a course
  app/assets/javascripts/favorite_course_buttons.ts
Labels: bug

#5336 Use papyros to debug testcases
  app/assets/javascripts/coding_scratchpad.ts
  app/assets/javascripts/i18n/translations.json
  app/assets/javascripts/modal.ts
  app/assets/javascripts/tutor.ts
  app/assets/stylesheets/components.css.scss
  app/assets/stylesheets/components/btn.css.scss
  app/assets/stylesheets/components/scratchpad.css.scss
  app/assets/stylesheets/components/tutor.css.scss
  app/controllers/feedbacks_controller.rb
  app/controllers/submissions_controller.rb
  app/helpers/renderers/feedback_table_renderer.rb
  app/helpers/renderers/pythia_renderer.rb
  app/views/activities/_coding_scratchpad.html.erb
  app/views/feedbacks/show.html.erb
  app/views/submissions/show.html.erb
  config/locales/js/en.yml
  config/locales/js/nl.yml
  config/routes.rb
  package.json
  public/tutorviz/css/basic.css
  public/tutorviz/css/jquery-ui-1.8.24.custom.css
  public/tutorviz/css/pytutor.css
  public/tutorviz/images/ui-bg_diagonals-thick_18_b81900_40x40.png
  public/tutorviz/images/ui-bg_diagonals-thick_20_666666_40x40.png
  public/tutorviz/images/ui-bg_flat_10_000000_40x100.png
  public/tutorviz/images/ui-bg_glass_100_f6f6f6_1x400.png
  public/tutorviz/images/ui-bg_glass_100_fdf5ce_1x400.png
  public/tutorviz/images/ui-bg_glass_65_ffffff_1x400.png
  public/tutorviz/images/ui-bg_gloss-wave_35_f6a828_500x100.png
  public/tutorviz/images/ui-bg_highlight-soft_100_eeeeee_1x100.png
  public/tutorviz/images/ui-bg_highlight-soft_75_ffe45c_1x100.png
  public/tutorviz/images/ui-icons_222222_256x240.png
  public/tutorviz/images/ui-icons_228ef1_256x240.png
  public/tutorviz/images/ui-icons_ef8c08_256x240.png
  public/tutorviz/images/ui-icons_ffd27a_256x240.png
  public/tutorviz/images/ui-icons_ffffff_256x240.png
  public/tutorviz/javascript/d3.v2.min.js
  public/tutorviz/javascript/iframe.min.js
  public/tutorviz/javascript/jquery-ui-1.8.24.custom.min.js
  public/tutorviz/javascript/jquery.ba-bbq.min.js
  public/tutorviz/javascript/jquery.jsPlumb-1.3.10-all-min.js
  public/tutorviz/javascript/jsPlumb-2.1.0-min.js
  public/tutorviz/javascript/pytutor.js
  public/tutorviz/tutorviz.html
  test/controllers/activities_controller_test.rb
  yarn.lock
Labels: feature, deploy naos

#5362 Stop previous papyros execution on new debug run
  app/assets/javascripts/tutor.ts
Labels: bug

#5359 Make sandbox button more prominent
  app/assets/javascripts/coding_scratchpad.ts
  app/assets/stylesheets/components/scratchpad.css.scss
  app/views/activities/_coding_scratchpad.html.erb
  app/views/activities/show.html.erb
  config/locales/views/activities/en.yml
  config/locales/views/activities/nl.yml
Labels: enhancement

#5368 Add extra validation when editing all labels by CSV
  app/controllers/course_members_controller.rb
  config/locales/views/course_members/en.yml
  config/locales/views/course_members/nl.yml
Labels: bug

#5366 Add debug state to papyros editor
  app/assets/javascripts/coding_scratchpad.ts
  app/assets/javascripts/tutor.ts
  package.json
  yarn.lock
Labels: enhancement

#5160 Tweak the new feedback table UI
  app/assets/javascripts/submission.ts
  app/assets/stylesheets/models/submissions.css.scss
  app/helpers/renderers/feedback_table_renderer.rb
Labels: enhancement

#5380 Replace doctest hack by different module name
  package.json
  yarn.lock
Labels: bug

#5369 Accept autocomplete suggestions using tab
  app/assets/javascripts/editor.ts
Labels: enhancement

#5386 Add tips that nudge users to better use of Dodona
  app/assets/javascripts/series.ts
  app/models/judge.rb
  app/policies/judge_policy.rb
  app/views/activities/show.html.erb
  app/views/judges/_form.html.erb
  app/views/series/edit.html.erb
  app/views/submissions/_description.html.erb
  config/locales/models/en.yml
  config/locales/models/nl.yml
  config/locales/views/activities/en.yml
  config/locales/views/activities/nl.yml
  config/locales/views/series/en.yml
  config/locales/views/series/nl.yml
  config/locales/views/submissions/en.yml
  config/locales/views/submissions/nl.yml
  db/migrate/20240226090515_add_deprecated_to_judges.rb
  db/schema.rb
  test/factories/judges.rb
  test/fixtures/judges.yml
  test/models/judge_test.rb
Labels: feature

#5400 Create card with a link to our documentation to help teachers get started
  app/assets/stylesheets/bootstrap_css_variable_overrides.css.scss
  app/views/pages/_teacher_intro_card.html.erb
  app/views/pages/home.html.erb
  config/locales/views/pages/en.yml
  config/locales/views/pages/nl.yml
Labels: feature

#5404 Fix iframe theme switch from system theme
  app/assets/javascripts/state/Theme.ts
Labels: bug
