Repository dodona-edu/dodona, pull requests merged in 2024-01, with the labels that each got.

#5271 Disable selection of line numbers in submission result
  app/assets/stylesheets/models/submissions.css.scss
Labels: bug

#5273 Fix display of escaped characters in 'restore boilerplate'
  app/views/activities/show.html.erb
  test/system/activities_test.rb
Labels: bug

#5274 Translate exercise names in search results
  app/assets/javascripts/state/SavedAnnotations.ts
  test/system/saved_annotation_test.rb
Labels: bug

#5276 Fix ctrl click for notifications
  app/assets/javascripts/notification.ts
Labels: bug

#5275 Fix redirect to series show from overview page of hidden series
  app/controllers/series_controller.rb
Labels: bug

#5272 Fix user label disappearing on global feedback update
  app/controllers/feedbacks_controller.rb
  app/models/feedback.rb
  app/views/feedbacks/_feedback_actions.html.erb
Labels: bug

#5214 Always use svg series icon
  app/assets/javascripts/components/series_icon.ts
  app/assets/javascripts/course.ts
  app/helpers/series_helper.rb
  app/javascript/packs/application_pack.js
  app/views/series/_series.html.erb
  app/views/series/_series_status.html.erb
Labels: bug

#5269 Always show navigation on submission pages
  app/assets/stylesheets/components/card.css.scss
  app/assets/stylesheets/models/submissions.css.scss
  app/views/evaluations/overview.html.erb
  app/views/feedbacks/_score_card.html.erb
  app/views/feedbacks/_score_link.html.erb
  app/views/feedbacks/_score_table.html.erb
  app/views/submissions/_description.html.erb
  config/locales/views/evaluations/en.yml
  config/locales/views/evaluations/nl.yml
  config/locales/views/feedbacks/en.yml
  config/locales/views/feedbacks/nl.yml
Labels: bug

#5287 Add new support method and improve support visibility
  app/assets/stylesheets/layout/footer.css.scss
  app/assets/stylesheets/layout/navbar.css.scss
  app/views/layouts/_breadcrumbs.html.erb
  app/views/layouts/_footer.html.erb
  app/views/layouts/_navbar.html.erb
  app/views/pages/support.html.erb
  config/locales/views/pages/en.yml
  config/locales/views/pages/nl.yml
Labels: enhancement

#5289 Remove "actions" for labels for users who can't do actions on labels
  app/views/labels/_labels_table.html.erb
Labels: bug

#5236 Update to papyros version with debugger
  app/assets/javascripts/coding_scratchpad.ts
  app/assets/javascripts/i18n/translations.json
  app/assets/stylesheets/base.css.scss
  app/assets/stylesheets/bootstrap_css_variable_overrides.css.scss
  app/assets/stylesheets/components/btn.css.scss
  app/assets/stylesheets/components/scratchpad.css.scss
  app/assets/stylesheets/theme/m3-theme-dark.css.scss
  app/assets/stylesheets/theme/m3-theme-light.css.scss
  app/assets/stylesheets/theme/trace-component.css.scss
  app/helpers/activity_helper.rb
  app/views/activities/_coding_scratchpad.html.erb
  config/locales/js/en.yml
  config/locales/js/nl.yml
  config/locales/views/activities/en.yml
  config/locales/views/activities/nl.yml
  package.json
  yarn.lock
Labels: feature

#5308 Add basic styling for details html element
  app/assets/stylesheets/components.css.scss
  app/assets/stylesheets/components/details.css.scss
Labels: enhancement

#5320 Don't show zeus messages on submissions when in demo mode
  app/assets/stylesheets/models/submissions.css.scss
  app/views/layouts/_main_container.html.erb
Labels: enhancement

#5332 Add latest Dodona-related publication to publications page
  app/assets/images/publications/zhidkikh-2024.png
  app/assets/stylesheets/pages/publications.css.scss
  app/views/pages/publications.html.erb
Labels: enhancement
