Repository dodona-edu/dodona, pull requests merged in 2024-06, with the labels that each got.

#5556 Add sentry
  .gitignore
  app/assets/javascripts/sentry.ts
  app/javascript/packs/application_pack.js
  config/initializers/content_security_policy.rb
  config/webpack/webpack.config.js
  package.json
  yarn.lock
Labels: chore

#5573 Don't try to show timezone or iframe warning if not present
  app/assets/javascripts/utilities.ts
Labels: bug

#5576 Add option to deselect only submission for evaluation
  app/views/feedbacks/show.html.erb
  config/locales/views/feedbacks/en.yml
  config/locales/views/feedbacks/nl.yml
Labels: bug

#5578 Only init submitbutton when logged in
  app/assets/javascripts/exercise.ts
Labels: bug

#5579 Create sentry release upon build
  .github/workflows/deploy-naos.yml
  .github/workflows/deploy-production.yml
Labels: chore

#5580 Don't try to enable submit button when not logged in
  app/assets/javascripts/exercise.ts
Labels: bug

#5582 Fix sentry release information
  .github/workflows/deploy-naos.yml
  .github/workflows/deploy-production.yml
  app/assets/javascripts/sentry.ts
  app/javascript/packs/frame.js
  app/views/layouts/application.html.erb
  app/views/layouts/frame.html.erb
  app/views/layouts/lti.html.erb
Labels: chore

#5586 Only init editor for exercises
  app/views/activities/show.html.erb
Labels: bug

#5587 Update PR review strategy
  .github/CODEOWNERS
Labels: chore

#5581 Make iframe methods available on submissions page
  app/javascript/packs/series_overview.js
  app/javascript/packs/submission.js
Labels: bug

#5588 Replace clipboardjs by webcomponent
  app/assets/javascripts/components/copy_button.ts
  app/assets/javascripts/components/copy_container.ts
  app/assets/javascripts/copy.ts
  app/assets/javascripts/exercise.ts
  app/assets/stylesheets/models/activities.css.scss
  app/helpers/application_helper.rb
  app/helpers/renderers/feedback_code_renderer.rb
  app/javascript/packs/application_pack.js
  app/javascript/packs/frame.js
  app/javascript/packs/submission.js
  app/views/api_tokens/_show.html.erb
  app/views/application/_token_field.html.erb
  app/views/courses/_form.html.erb
  app/views/judges/show.html.erb
  app/views/repositories/show.html.erb
  app/views/series/edit.html.erb
  package.json
  test/renderers/feedback_code_renderer_test.rb
  yarn.lock
Labels: bug

#5605 Fix 'visible after start time' when creating series
  app/assets/javascripts/series.ts
  app/javascript/packs/series.js
  app/views/series/_form.html.erb
Labels: bug

#5607 Disable plagiarism detection when language is not supported by dolos
  app/assets/javascripts/dolos.ts
  app/assets/javascripts/i18n/translations.json
  app/assets/stylesheets/components/btn.css.scss
  app/views/evaluations/_exercises_progress_table.html.erb
  app/views/submissions/index.html.erb
  config/locales/js/en.yml
  config/locales/js/nl.yml
Labels: bug

#5608 Update list of languages supported by dolos
  app/assets/javascripts/dolos.ts
Labels: chore

#5638 Group sentry dependabot prs
  .github/dependabot.yml
Labels: chore

#5640 Allow for multiple selection in editor
  app/assets/javascripts/editor.ts
Labels: enhancement

#5641 Separate series activity icons into columns
  app/assets/stylesheets/models/activities.css.scss
  app/views/activities/_series_activities_table.html.erb
Labels: enhancement

#5642 Allow expand/collapse of targeted feedback groups
  app/assets/javascripts/submission.ts
  app/assets/stylesheets/models/submissions.css.scss
Labels: bug, no deploy

#5645 Only upload source maps to sentry in production and staging
  config/webpack/webpack.config.js
Labels: chore, no deploy

#5646 Add ctrl+enter/cmd+enter keyboard shortcut to submit code from editor
  app/assets/javascripts/editor.ts
Labels: enhancement

#5644 Revert to original motivational messages
  app/assets/javascripts/i18n/translations.json
  app/assets/javascripts/submission.ts
  config/locales/js/en.yml
  config/locales/js/nl.yml
Labels: enhancement
