Repository dodona-edu/dodona, pull requests merged in 2024-04, with the labels that each got.

#5462 Add Blink article to publications page
  app/assets/images/publications/strijbol-2024.png
  app/views/pages/publications.html.erb
Labels: enhancement

#5458 Convert github https clone urls to ssh clone urls
  app/models/concerns/gitable.rb
  test/models/repository_test.rb
Labels: bug

#5460 Fix sticky next button when evaluating
  app/assets/stylesheets/components/evaluations.css.scss
Labels: bug

#5411 Add export of course users
  app/assets/javascripts/components/search/search_actions.ts
  app/controllers/course_members_controller.rb
  app/models/course.rb
  app/views/annotations/question_index.html.erb
  app/views/course_members/index.csv.erb
  app/views/course_members/index.html.erb
  app/views/submissions/index.html.erb
  config/locales/views/course_members/en.yml
  config/locales/views/course_members/nl.yml
  config/routes.rb
  test/javascript/components/search/search_actions.test.ts
Labels: feature

#5479 Fix tab scrollbar in chrome
  app/assets/stylesheets/components/card.css.scss
Labels: bug

#5481 Only show feedback count for unreleased evaluations
  app/helpers/pages_helper.rb
  app/models/course.rb
  test/models/course_test.rb
Labels: bug

#5482 Fix styling for close button of sandbox
  app/views/activities/_coding_scratchpad.html.erb
Labels: bug

#5421 Improve discoverability of evaluations and scoresheets
  app/views/series/_series.html.erb
Labels: enhancement

#5430 Make search actions and options more discoverable
  app/assets/javascripts/components/search/dropdown_filter.ts
  app/assets/javascripts/components/search/filter_tabs.ts
  app/assets/javascripts/components/search/loading_bar.ts
  app/assets/javascripts/components/search/search_actions.ts
  app/assets/javascripts/components/search/search_option.ts
  app/assets/javascripts/components/search/search_token.ts
  app/assets/javascripts/course.ts
  app/assets/javascripts/i18n/translations.json
  app/assets/stylesheets/components/dropdown-filter.css.scss
  app/assets/stylesheets/components/table-toolbar.css.scss
  app/assets/stylesheets/components/token.css.scss
  app/assets/stylesheets/material_icons.css.scss
  app/assets/stylesheets/models/course.css.scss
  app/javascript/packs/search.js
  app/views/activity_read_states/index.html.erb
  app/views/annotations/question_index.html.erb
  app/views/course_members/index.html.erb
  app/views/courses/index.html.erb
  app/views/courses/scoresheet.html.erb
  app/views/layouts/_searchbar.html.erb
  app/views/series/scoresheet.html.erb
  app/views/submissions/index.html.erb
  config/locales/js/en.yml
  config/locales/js/nl.yml
  test/javascript/components/search/search_actions.test.ts
  test/javascript/components/search/search_options.ts
Labels: deploy mestra, enhancement
